### ISSUE TITLE
feature request: auto-sorting bookmarks into lists

### ISSUE THREAD

**Issue by asg0451** [hoarder-app/hoarder#11]
the readme suggests this functionality exists but it doesnt seem to...

**Comment by MohamedBassem** [comment]
Sorry if the readme isn't clear. Right now items are automatically "tagged". Lists are manually created and managed by the user.

**Comment by asg0451** [comment]
Ah gotcha. That might be a neat feature though... ;)

**Comment by asg0451** [comment]
something like this maybe -- https://chat.openai.com/share/b1e1c49e-5595-4524-9146-a88a2efa020e

**Comment by MohamedBassem** [comment]
That's cool indeed. Lists and tags are already quite similar. Basically, everything that you can do with tags, you can do with lists. The only difference is that lists are manual and intentional by humans.

At the same time, I really like the suggested grouping in your example. One idea can be for the app to suggest "Lists" for the user to accept based on the tags. It'll require some more thought though.

**Comment by asg0451** [comment]
totally. "suggested lists" or something.

**Comment by mp-strachan** [comment]
I am coming from Raindrop and bringing over a lot of my bookmarks. In raindrop, I make heavy use of their lists to logically sort a collection of things... for example `Vintage Computer Networking` might many articles related to a few different but adjacent topics.

It would be super amazing to be able to set a list to include dynamic tags... eg: `Vintage Computer Networking` -> `56k`, `ADSL`, `Dialup`.... almost like a list can be a "group" of tags.

Raindrop also let you nest lists, which was handy ("Vintage Computers" -> "Networking") to help keep large libraries (3000+ links) under control - but this is probably its own feature request :D (I'm currently using "Vintage Computers - Networking" and "Vintage Computers - Hardware" etc etc.)

Thanks for this great tool - can't wait to see where it heads over the coming months!

**Comment by MohamedBassem** [comment]
@mp-strachan I really like the idea of "automatic lists" based on tags. It makes a lot of sense. Can you open a separate feature request issue for it? :)

**Comment by kamtschatka** [comment]
I am closing this issue as duplicate, as there is already an idea that will solve this. Please have a look at this comment: https://github.com/hoarder-app/hoarder/issues/65#issuecomment-2142707271
With those searches, you would be able simply save a smart list, which has a filter that would always match the bookmarks you want.

If you have any concerns about this, please post in the other issue, so we can keep the discussion together.
