### ISSUE TITLE
[Feature Request] Create Testing dataset and evaluation workflows for AI Tasks

### ISSUE THREAD

**Issue by medo** [hoarder-app/hoarder#113]
The project has a big potential for various AI workflows that can use the saved data to do different useful tasks for users.

To ease the development of different AI workflows and enable collaboration, I suggest creation of different golden test datasets that simulates the behaviour of different users. This will enable eveyone to run experiments on those golden datasets and share results (on jupyter notebooks?)

I think this could be a starting point for developers to showcase different ideas on typical Hoarder data.

**Comment by kamtschatka** [comment]
Can you elaborate a bit more? I honestly have no idea what you are asking.
