### ISSUE TITLE
[Feature request] Show 'Lists" Bookmark is Part of

### ISSUE THREAD

**Issue by MikeKMiller** [hoarder-app/hoarder#124]
Currently a 'Bookmark' Card show the tags associated with the Bookmark, it would be helpful to also list the 'Lists' the bookmark is in.

**Comment by MohamedBassem** [comment]
Hello, in the next release the lists will be available in a new `Manage Lists` dialog. I think it might be a bit too tight to add them all in the bookmark cards. What do you think?

<img width="513" alt="Screenshot 2024-04-25 at 4 34 19 PM" src="https://github.com/MohamedBassem/hoarder-app/assets/2418637/2c280d9e-52b2-4534-b922-9e7fb40a9164">

**Comment by MikeKMiller** [comment]
Interested to see how it works.

**Comment by MohamedBassem** [comment]
@MikeKMiller did you check out the last update? Is that good enough or do you still think it's useful to show the lists inline in the bookmark card?
