### ISSUE TITLE
Suggestion: move archive category to the bottom of the list

### ISSUE THREAD

**Issue by zunjae** [hoarder-app/hoarder#130]
Reason: archive is a list you don't visit often, so it would make more sense to put it somewhere at the bottom.

I've looked at the source code and I think it's here https://github.com/MohamedBassem/hoarder-app/blob/afefbe3cb46fdb9155b4b00d0fcb88a4c7fc9cd0/apps/mobile/app/dashboard/(tabs)/lists.tsx#L70

I think it can be solved by appending the archive at the end of ListLink[] when you're done iterating through all custom lists

**Comment by MohamedBassem** [comment]
Hey, thanks for the suggestion! I understand your point, but I checked other apps (raindrop, omnivore and pocket) and they all seem to have it with the rest of the predefined items, so to be honest, I prefer leaving it where it is :)

**Comment by kamtschatka** [comment]
I agree, Archive is the Archive, so stuff that you don't really need/the exact oppossite of "Favourites", so it doesn't really deserve a spot so high up in the list.
A feature that is missing would be the reordering of lists, as currently it just depends on when you created the list.
I was thinking maybe it makes sense to also allow reordering of the special lists "Favourites"/"Archive", but that would be harder to implement than the reordering of custom lists.

**Comment by kamtschatka** [comment]
Archive has been relocated to be outside of the lists now

![image](https://github.com/user-attachments/assets/eaa4e24d-6695-4e7d-a848-491ea9ec70b7)
