### ISSUE TITLE
[Feature request] Store local copy of webpages

### ISSUE THREAD

**Issue by lardissone** [hoarder-app/hoarder#132]
Like Raindrop does, allow to store a copy of the webpage.

There's a bunch of options to accomplish this.
Here's a nice list of tools to use for inspiration: [awesome web archiving](https://github.com/iipc/awesome-web-archiving)

**Comment by scubanarc** [comment]
Monolith might be a good choice here... it's CLI and works well.

**Comment by MohamedBassem** [comment]
btw, hoarder already stores a local copy of the crawled content. That's what you see in the bookmark preview page.

But it as of right now, doesn't include the images. It's also only the readable parts of the page, not the entire page.

I've seen monolith before and I think it's cool, I might give it a try :)

**Comment by lardissone** [comment]
@MohamedBassem yes, I've seen that, but in fact the images are a must. I usually store articles with explanation figures embedded, and the text only turns it useless.

**Comment by MohamedBassem** [comment]
@lardissone that makes sense. I think I can give monolith a try and see how it goes. Will see if I can include it in the next release.

**Comment by lardissone** [comment]
Awesome! You rock!

**Comment by MohamedBassem** [comment]
I got a basic version of monolith working! The output pages are huge though and because everything is inlined, they take sometimes to load. I think I'll ship it disabled by default, and maybe in the future add a button to archive pages on demand.

**Comment by lardissone** [comment]
@MohamedBassem this is great! thanks for adding this!
