### ISSUE TITLE
Please add this to your README! I tried to add but failed to commit!

### ISSUE THREAD

**Issue by mwalid207** [hoarder-app/hoarder#133]
[![ReadMeSupportPalestine](https://raw.githubusercontent.com/Safouene1/support-palestine-banner/master/banner-support.svg)](https://techforpalestine.org/learn-more)

**Comment by kamtschatka** [comment]
Considering that this issue is old and it has not been added yet, I don't think it is going to happen. 
This is a project for everyone and I don't think we should politicize it.
