### ISSUE TITLE
hoarder --version reports version 0.0.0

### ISSUE THREAD

**Issue by skirmess** [hoarder-app/hoarder#139]
The npm CLI reports

```
$ hoarder --version
0.0.0
```

but installed version is 0.13.2:

```
$ more package.json
{
  "dependencies": {
    "@hoarderapp/cli": "^0.13.2"
  }
}
```

**Comment by kamtschatka** [comment]
So the reason is that the version is taken from `process.env.npm_package_version` and if that does not exist, it takes 0.0.0.
I guess a replacement step during the build that bakes this version in would make sense? @MohamedBassem?
