### ISSUE TITLE
Bug: Failed to store svg

### ISSUE THREAD

**Issue by dyslexicjedi** [hoarder-app/hoarder#141]
Latest version of docker, checked this morning.

Logs: 

`2024-05-07T13:25:30.448Z info: [Crawler][34] Downloading image from "https://wiki.archlinux.org/images/1/19/Tango-view-fullscreen.svg"
2024-05-07T13:25:30.975Z error: [Crawler][34] Failed to download and store image: Error: Unsupported asset type
`

**Comment by MohamedBassem** [comment]
Yeah, currently svgs are not yet supported. Will probably add support soon.

**Comment by kamtschatka** [comment]
TBH in this case I don't think you want the svg to be stored anyways. 
I added https://archlinux.org/ to hoarder and allowed it to download svgs. The only thing that happened was that the preview looks like this:
![image](https://github.com/hoarder-app/hoarder/assets/22147234/92c70504-fedb-4f52-9648-fa9f64a4f75e)

Granted, I did not fix the rendering of the preview, but it would simply show the svg it found on the page, this tiny rss feed svg:
https://archlinux.org/static/rss.ca03bf98a65a.svg

So for bookmark previews this sounds like a rather useless addition^^.

**Comment by kamtschatka** [comment]
This is pretty much the same as https://github.com/hoarder-app/hoarder/issues/128, which is also about adding support for other image formats, so I'll mark this one as duplicate. Please follow the other one for updates
