### ISSUE TITLE
[Feature Request] Automatic tags based on metadata + adjusting image tag extraction prompt

### ISSUE THREAD

**Issue by mape** [hoarder-app/hoarder#15]
It would be neat if it was possible to define rules that add tags based on metadata.

For example:
https://www.bukowskis.com/sv/lots/1540548-matbord-bento-hem-2000-tal
I'd want the tag `furniture` added because the URL contains `bukowskis.com`.

https://www.nordiskagalleriet.se/nemo-lighting/escargot?variant=10213172
I'd want the tag `mid-century-modern` added because the body contains the text `Le Corbusier`.

Building on-top that, it would be nice if it was possible to trigger changes in the image tag extraction prompt based on existing tags.

So if the tag `furniture` is present from the text extraction pass (or through metadata rules) the image prompt would append suggestions focusing on describing the item vs more generic tags.

**Comment by MohamedBassem** [comment]
I like the idea of having rule-based tagging. Can't promise I'll be able to get to it soon though as it's not trivial :)

**Comment by MohamedBassem** [comment]
Adding tagging rules (and customizing the prompt) is implemented in https://github.com/hoarder-app/hoarder/commit/36fb5a4c63aada8e8107b8e9d97a6ba128d13494 and will be available in the next release.
