### ISSUE TITLE
Allow adding multiple URLs at once

### ISSUE THREAD

**Issue by kamtschatka** [hoarder-app/hoarder#158]
When you have a lot of URLs at hand, it would be great if you can put them all into hoarder at once.
A simple solution would be, if you drop a list of URLs in the "new item" and press "Save", it checks if this is just a list of URLs separated by new-line characters. If it is, then ask if it should be a note, or if the URLs should be imported as separate Bookmarks.

**Comment by MohamedBassem** [comment]
hmmm, I haven't so far implemented any mass importing functionality in the app itself because you can do it with the CLI (https://docs.hoarder.app/import). Though I understand that probably not everyone would be familiar with how to use CLIs.

**Comment by MohamedBassem** [comment]
Implemented by @kamtschatka in #167!
