### ISSUE TITLE
Alternative Port

### ISSUE THREAD

**Issue by aaroneden** [hoarder-app/hoarder#166]
Thanks for what looks to be a really great app!   I installed on my synology using port 3022 and confirmed that port forwarding is working and I can access Hoarder externally and sign in.

When I try to use the iPhone app or the Chrome plugin to sign in to Hoarder it tells me it cannot connect.  I'm providing exactly the same domain mydomain.com:3022  as I do in my browser.   CAn you please tell me what I am doing wrong?

**Comment by MohamedBassem** [comment]
Did you include the protocol in chrome and the app? As in: `http://mydomain.com:3022` or only `mydomain.com:3022`?

**Comment by aaroneden** [comment]
I tried both formats

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by aaroneden** [comment]
@MohamedBassem Okay - I must have made a typo in the Chrome extension -- I was able to get it to work with "http://mydomain.com:3022"  ... Working on the iPhone app now to see if I can do similarly.

**Comment by aaroneden** [comment]
@MohamedBassem No, not a reverse proxy.  Just used port forwarding to pass 3022 through my router and wifi.

**Comment by MohamedBassem** [comment]
Which ios version are you using btw? Can you make sure you're on the latest version (0.15.0)?
Can you also make sure that the same address is accessible from your phone's browser?

**Comment by aaroneden** [comment]
I'm on an iPhone 15 Pro Max with IOS 17.4.1 and Hoarder 1.5.0.  

Confirmed I can hit the 3022 URL via the browser on the phone.

**Comment by aaroneden** [comment]
Also - I confirmed that I can use a Shortcut to post to hoarder via my phone at the same URL, but the iPhone app is not working.

**Comment by MohamedBassem** [comment]
@aaroneden that's very weird.I'll need to add some extra debugging capabilities to the mobile app to be able to debug this further :(

**Comment by aaroneden** [comment]
Okay — please let me know how I can help.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by genggng** [comment]
I encountered the same problem, and I manually set up the dns rules on my iPhone to ensure that I could resolve the domain name to the ip of my own server. On the iPhone's safari browser, everything works fine. But in the app, the network request will fail.

**Comment by MohamedBassem** [comment]
The new versions of the mobile app currently come with a new debugging functionality. If you're still facing the issue, please give it a shot and share the debug logs in a new issue.
