### ISSUE TITLE
Improve handling of failed crawling jobs

### ISSUE THREAD

**Issue by kamtschatka** [hoarder-app/hoarder#169]
I have a few bookmarks imported from chrome that fail due to 404/500... errors. They get added (which is fine), but since they also get a response, they go through ollama for tagging and can't really be filtered for in the UI (no indication that something went "wrong" during crawling as in received a statuscode that indicates an error).
Would be great if there was a filter that shows bookmarks that failed and exclude them from AI tagging (400+ status code)

**Comment by MohamedBassem** [comment]
hmmm, not sure I understand what you mean by not found in the UI? Even if the crawler fails, the bookmark will be shown in the UI.

**Comment by MohamedBassem** [comment]
For that one, let's start storing status codes in the link entity. And then we can build a new tab in the settings page to show dead links.
