### ISSUE TITLE
Allow customizing the AI prompt

### ISSUE THREAD

**Issue by kamtschatka** [hoarder-app/hoarder#170]
I just wanted to create a ticket for the short side discussion in the [previous PR](https://github.com/MohamedBassem/hoarder-app/pull/162#discussion_r1605374946_)

The idea is to allow users to customize the AI prompt to change the behavior.
The existing prompt is not so bad and it makes sense to have a good prompt shipped with Hoarder, but for tinkering it might be a good idea.

In the PR the suggestion was to enable adding additional information at the end of the prompt, maybe it would also make sense to have access to some placeholders like existing tags or existing list names.

**Comment by jbvioix** [comment]
It's a great idea. I've done some testing with Mistral (and I think it's generalizable to other LLMs) and it gives better results when the query is in the same language as the expected keywords.
