### ISSUE TITLE
Web server redirects to the wrong address at logout

### ISSUE THREAD

**Issue by hubleyku** [hoarder-app/hoarder#173]
I've got Hoarder set up in Docker along with a reverse proxy. When I log out, it redirects to the address that's defined for NextAuth, in my case, localhost:3000. It's a small issue, but it would be nicer if the redirect was back to the domain I've set up for Hoarder.

**Comment by MohamedBassem** [comment]
Hi, the redirect after logout goes to what you've setup in your next auth url. NextAuth's url should point to your publicly facing address of the service.

**Comment by MohamedBassem** [comment]
I'll close this and you can re-open it if you still facing problems :)
