### ISSUE TITLE
ghcr.io/hoarder-app/hoarder-web dont work

### ISSUE THREAD

**Issue by Famku** [hoarder-app/hoarder#175]
Hi,

ghcr.io/hoarder-app/hoarder-web dont work for me 

KeyError: 'ContainerConfig'

the old one works fine.

**Comment by MohamedBassem** [comment]
Can you share the exact command you're running? Is that in docker compose? Did you try manually running "docker pull"?

**Comment by Famku** [comment]
docker-compose

docker-compose pull && sudo docker-compose up -d

**Comment by MohamedBassem** [comment]
Can you run 'docker pull ghcr.io/hoarder-app/hoarder-web:release' and share the output?

Can you also share the value of "HOARDER_RELEASE" env variable?

**Comment by Famku** [comment]
release: Pulling from hoarder-app/hoarder-web
Digest: sha256:b42c3362b0ba4d48c696807814df8524ea2525cd399c1482844d5afbc4e3361f
Status: Downloaded newer image for ghcr.io/hoarder-app/hoarder-web:release
ghcr.io/hoarder-app/hoarder-web:release

HOARDER_VERSION=release

**Comment by MohamedBassem** [comment]
Ok, so pulling it works makes me wonder if it's a typo or something in the compose file. Can you share the lines in the compose file where you specify those images?

**Comment by Famku** [comment]
`version: "3.8"
services:
  web:
    image: ghcr.io/mohamedbassem/hoarder-web:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - data:/data
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      DATA_DIR: /data
  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis:/data
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
      - --disable-dev-shm-usage
  meilisearch:
    image: getmeili/meilisearch:v1.6
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - meilisearch:/meili_data
  workers:
    image: ghcr.io/hoarder-app/hoarder-workers:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - data:/data
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
      # OPENAI_API_KEY: ...
    depends_on:
      web:
        condition: service_started

volumes:
  redis:
  meilisearch:
  data:`

**Comment by MohamedBassem** [comment]
hmmm, the docker compose looks good to me. Did you manage to get this solved? I've been personally using the `hoarder-app` images and they seem to be working just fine.

**Comment by Famku** [comment]
I stay with the old repo for now.

And if nobody complain, maybe it is just on my side

I just wanted to inform you

**Comment by kamtschatka** [comment]
closing this issue as it is very old and nobody else complained. If you still encounter issues, let us know
