### ISSUE TITLE
Add Hoarder as an option in share sheet on iOS

### ISSUE THREAD

**Issue by jbuitt** [hoarder-app/hoarder#177]
Thank you for this app, superb work!!

The feature that would be awesome is to have Hoarder as an option when you are in Safari on iPhone and click Share. That would save folks a few steps, since now you have to copy the link in Safari, switch over to Hoarder, and then add the link.

Thanks!

**Comment by MohamedBassem** [comment]
Hi 👋 Hoarder is already available in the share sheet, you just need to enable it. When you open the share sheet, scroll all the way to `More`, and add `Hoarder` to the list of suggested apps in the position you want.

**Comment by jbuitt** [comment]
Hey! Thanks for your response!

It wasn't showing up in the share sheet but after I rebooted my phone, now it's there. Weird.

Anyway, thank you!
