### ISSUE TITLE
Web page shows generic error message if you try to add a duplicate bookmark

### ISSUE THREAD

**Issue by skirmess** [hoarder-app/hoarder#179]
Trying to add a bookmark, which already exists, from the web page shows this error message:

![image](https://github.com/hoarder-app/hoarder/assets/8441536/bc4dd16f-2b71-4b01-ba69-15bc8ed0c981)

The server log shows:

```
web-1          | s [TRPCError]: Bookmark e8kgxwkflas1hw75h92v7303 is already in the list saq2f0uqazppijovqcqbezj8
web-1          |     at /app/apps/web/.next/server/chunks/838.js:1:20346
web-1          |     at async c.middlewares (/app/apps/web/.next/server/chunks/673.js:4823:10163)
web-1          |     at async a (/app/apps/web/.next/server/chunks/673.js:4823:9557)
web-1          |     at async a (/app/apps/web/.next/server/chunks/673.js:4823:9557)
web-1          |     at async a (/app/apps/web/.next/server/chunks/673.js:4823:9557)
web-1          |     at async a (/app/apps/web/.next/server/chunks/673.js:4823:9557)
web-1          |     at async a (/app/apps/web/.next/server/chunks/673.js:4823:9557)
web-1          |     at async a (/app/apps/web/.next/server/chunks/673.js:4823:9557)
web-1          |     at async t (/app/apps/web/.next/server/chunks/673.js:4823:9896)
web-1          |     at async /app/apps/web/.next/server/app/api/trpc/[trpc]/route.js:1:4281 {
web-1          |   code: 'BAD_REQUEST',
web-1          |   [cause]: undefined
```

Ideally, the web page should mention the reason why the bookmark wasn't added.

**Comment by kamtschatka** [comment]
are you using the latest version? (0.14) You can check on the admin page.
That has link deduplication and should look like this:
![image](https://github.com/hoarder-app/hoarder/assets/22147234/40bdff3e-0f6e-4589-b6ab-61c8eac370ce)

If yes, how did you add it?

**Comment by skirmess** [comment]
Yes, I'm using 0.14.0.

Steps to reproduce:

- Click on Home
- Create a bookmark, e.g.: `https://duckduckgo.com/`

The bookmark is added

![image](https://github.com/hoarder-app/hoarder/assets/8441536/59b313d4-d84b-475b-a97a-29c4428f13bc)

- Create a new list, e.g.: `test list`
- In the list, add the bookmark
![image](https://github.com/hoarder-app/hoarder/assets/8441536/c82ef08f-b161-456b-a203-c690d744e9da)

- You get the message you mentioned and the existing bookmark is added to this list (this is awesome!!!)
![image](https://github.com/hoarder-app/hoarder/assets/8441536/7bffee83-68a1-4c3e-8c47-a830d5a72ef4)

- Now try to add the bookmark again to the list and you get my error message:

![image](https://github.com/hoarder-app/hoarder/assets/8441536/e2c155a8-7d39-4766-9986-aed274d43a1a)

**Comment by skirmess** [comment]
I guess you could also just say "Bookmark is already in this list"

**Comment by kamtschatka** [comment]
I also considered that, but there is now also multi url import, so it might become a bit confusing if you try to add multiple bookmarks and you only get 10 messages with "Bookmark is already in this list".
Maybe "bookmark <id> is already in this list"?

**Comment by skirmess** [comment]
I'm also fine with the cryptic message. :-) It does show that the issue is the user and not the software. :-)
