### ISSUE TITLE
AI infered tags can contain " " at the beginning

### ISSUE THREAD

**Issue by kamtschatka** [hoarder-app/hoarder#184]
Might also be happening on the end, I haven't tried that, but when I looked at the database, I can see the tag being named " DIY" instead of "DIY".
This leads to the scenario where you can actually create tags, that seemingly already exist:
![image](https://github.com/hoarder-app/hoarder/assets/22147234/83e3d421-debe-4e3c-a00d-9f283f199b8d)

![image](https://github.com/hoarder-app/hoarder/assets/22147234/7c4010f9-23ce-4fb2-bbe1-bd2bcb44394d)

I guess just a quick trim() would be a good idea before creating tags?

**Comment by MohamedBassem** [comment]
Good catch

> I guess just a quick trim() would be a good idea before creating tags?

Yup, let's do it!
