### ISSUE TITLE
Feature request: Browser extension "Open your Hoarder saves"

### ISSUE THREAD

**Issue by Deathproof76** [hoarder-app/hoarder#188]
I have one QoL/feature request for the browser extension: Would it be possible to integrate a link to ones own hoarder page? Similar to the pocket extension.

Like, right click on the addon in the toolbar and the second selection is something like "Open your Hoarder saves" -> click it -> and a new tab opens the hoarder instance. The url link used should be the same the addon already knows.

**Comment by MohamedBassem** [comment]
Sounds like something we can easily support indeed :)
