### ISSUE TITLE
Text that contains single and double quotes produces invalid YAML

### ISSUE THREAD

**Issue by skirmess** [hoarder-app/hoarder#190]
I am using the hoarder server version 0.14.0.

Paste the following text in the the new item field

`"hello world, how's it going"`

This produces invalid YAML:

```
$ hoarder bookmarks list --list-id njk89ftpg0643vy5626wimxt
[
  {
    id: 'rxjf0qniaqfiusgqaroc7v8g',
    createdAt: 2024-06-01T13:18:07.000Z,
    title: null,
    archived: false,
    favourited: false,
    taggingStatus: 'success',
    note: null,
    tags: [],
    content: { type: 'text', text: `"hello world, how's it going"` }
  }
]
```

If you check it with [https://www.yamllint.com/](https://www.yamllint.com/) you get:

`Plain value cannot start with reserved character ` at line 11, column 36`

**Comment by MohamedBassem** [comment]
As mentioned in another issue, the output of the CLI is not meant to be a YAML. @kamtschatka added JSON support in https://github.com/hoarder-app/hoarder/commit/cde97267a90802c6a367aa61ff157983506deead. So if you want to get a parsable output, use --json.
