### ISSUE TITLE
Too long lines are truncated which produces invalid YAML

### ISSUE THREAD

**Issue by skirmess** [hoarder-app/hoarder#191]
I am using the hoarder server version 0.14.0.

Add the following link to the new item field on the web page: [I am using the hoarder server version 0.14.0.](https://skirmess.github.io/hoarder-invalid-yaml-test/test2.html). This page contains an image included in the HTML code.

The preview correctly shows the page:

![image](https://github.com/hoarder-app/hoarder/assets/8441536/8ece2f33-18ef-49d1-a227-5225872c6a59)

But dumping the bookmark with the CLI with `hoarder bookmarks list --list-id njk89ftpg0643vy5626wimxt
` produces garbled output:

![image](https://github.com/hoarder-app/hoarder/assets/8441536/a31eedda-9d1c-4389-be31-99d3ba46fba1)

**Comment by kamtschatka** [comment]
The output is invalid yaml, but it is also not supposed to be yaml, but json. Take a look at #150, which is what you are seeing as well. There is already a PR open to create proper JSON output if you provide the `- - json` commandline argument.

**Comment by MohamedBassem** [comment]
The PR that adds `--json` just landed: https://github.com/hoarder-app/hoarder/commit/cde97267a90802c6a367aa61ff157983506deead. Closing this as I hope JSON is good enough :)
