### ISSUE TITLE
Any plans to support copy to clipboard (markdown code) for notes?

### ISSUE THREAD

**Issue by ItsNoted** [hoarder-app/hoarder#195]
Love this but I’m curious if there will ever be an option to past code into notes we can easily copy to clipboard. I like to save snippets and compose stacks.

**Comment by kamtschatka** [comment]
are you talking about the whole note, or about separate code blocks you have added using markdown? (with 3 `)
I like both ideas actually.

**Comment by ItsNoted** [comment]
Just the code blocks with copy to clipboard. 😊

**Comment by kamtschatka** [comment]
I managed to do this:
![image](https://github.com/hoarder-app/hoarder/assets/22147234/1e8432c8-8925-4272-8c55-4c80795bdac8)
![image](https://github.com/hoarder-app/hoarder/assets/22147234/c8f7f9e6-2bc4-4339-819c-fcef24398d00)

When you copy it, you get a short indicator: 
![image](https://github.com/hoarder-app/hoarder/assets/22147234/f329e563-b7fd-4b71-847e-ea0c7a8538f4)

The black border around the syntax highlighter is not perfect, but tbh, i have no idea how to get rid of it^^.
Maybe @MohamedBassem or someone else knows.

I will create a PR so people can have a look.

**Comment by ItsNoted** [comment]
Looking good!

**Comment by ItsNoted** [comment]
What version can I grab to try it out for docker or do I need to build it myself?

**Comment by kamtschatka** [comment]
I have only opened the PullRequest so far. Right now you would need to pull from that branch and build it yourself to try it out.
To have it in the docker image, the PR needs to be merged and a new version needs to be released.

**Comment by ItsNoted** [comment]
This really could replace the amazing project Snippet-Box which has been abandoned for quite some time now. https://github.com/pawelmalak/snippet-box. Take a look at that project and you can see how Hoarder has some similar attributes. This is why I love this project so much because it reminds me a lot of Snippet-Box. I'm excited to see where it goes :)

**Comment by ItsNoted** [comment]
Thanks for adding this! It didn't work locally but when I tried it on my cloudflare tunnel it worked. Not sure why but maybe something to do with my update process.

**Comment by MohamedBassem** [comment]
@ItsNoted chrome doesn't allow accessing the clipboard except when using https or localhost. So it won't work on http unfortunately.

**Comment by kamtschatka** [comment]
there should be a tooltip though, that explains this?
