### ISSUE TITLE
[Feature Request] Share specific notes publicly

### ISSUE THREAD

**Issue by ItsNoted** [hoarder-app/hoarder#200]
There are a couple things I was wondering.

1. Any plans to allow note sharing? This would make the note public so people don't have to register to see it.
2. Any plans to make it a choice to make all of your notes public so anyone viewing your hoarder page can see them all? Basically makes it public rather than private.

**Comment by ItsNoted** [comment]
Maybe the same as https://github.com/hoarder-app/hoarder/issues/37

**Comment by MohamedBassem** [comment]
Yeah, this looks similar to #126. Let's track it there instead.

**Comment by MohamedBassem** [comment]
I think having public lists is useful, and I'm sure one day I'll do it. It's just a bit tricky implementation wise to handle all the privacy checks, so I want to do it right. Same challenges with the "shared" lists.
