### ISSUE TITLE
Do you plan to allow this to consume RSS feeds?

### ISSUE THREAD

**Issue by Romanmir** [hoarder-app/hoarder#202]
One of the biggest things that I use is RSS. I'm currently using Wallabag in this space and while it can produce an RSS feed, it can not consume an RSS feed.

My biggest use case for this is Reddit. I currently point TTRSS to my Saved and Upvoted Reddit feeds, and I can interact with articles on a more or less one time basis using this workflow. I'd like to be able to point something like this to my Reddit feed and have at least the Saved stuff be captured by this application.

Thoughts?

**Comment by MohamedBassem** [comment]
Wait a second. I didn't know you can get an RSS feed for your reddit saves and upvotes! That's actually a very cool idea.

So far, I wanted to keep the core of Hoarder simple and allow importing stuff to it with sidecars (or other IFTTT services). You can still write a simple workflow from [n8n](https://n8n.io/integrations/rss-read/) to post items to Hoarder whenever something appears on RSS.

On the other hand, supporting RSS natively also kinda feels natural for Hoarder. Will need to think a bit more about it.

**Comment by Romanmir** [comment]
More information: Reddit has a page of various account based rss feeds found here: https://ssl.reddit.com/prefs/feeds/ 

Naturally you'll need to log in first.

**Comment by A-Byte-Sized** [comment]
I'll also pitch in and say this could be what makes Hoarder really stand out among the rest. There are plenty of RSS feed managers and bookmark managers, but neither of them support both. 

With how crappy Google has gotten, I'm dying for an "internet of things" dashboard for consuming new media/research/etc (RSS feed), and an easy way to bookmark things if later reference is needed (because Googling is unreliable now). Right now the only way is to host two difference services - which means tags, organizing, etc are separate. 

If you don't want it as a full base feature, maybe it can be a Plugin for Hoarder?

**Comment by danielslyman** [comment]
> Wait a second. I didn't know you can get an RSS feed for your reddit saves and upvotes! That's actually a very cool idea.
> 
> 
> 
> So far, I wanted to keep the core of Hoarder simple and allow importing stuff to it with sidecars (or other IFTTT services). You can still write a simple workflow from [n8n](https://n8n.io/integrations/rss-read/) to post items to Hoarder whenever something appears on RSS.
> 
> 
> 
> On the other hand, supporting RSS natively also kinda feels natural for Hoarder. Will need to think a bit more about it.

How would you propose to connect n8n to Hoarder? I was waiting for the REST API but if there is a better way, please share.

**Comment by afischer211** [comment]
I have the same question - how can I access my local Hoarder instance with my local n8n instance for adding new entries?

**Comment by MohamedBassem** [comment]
@danielslyman @afischer211 while Hoarder currently doesn't have a "REST" API, it does have an API:

You can use it as:

1. Get an API key from the settings page of Hoarder.
2. Send a POST request to `https://demo.hoarder.app/api/trpc/bookmarks.createBookmark`:
  a. Set the `Authorization` header to `Bearer <api_key>`.
  b. Set the body to `{"json": {"type": "link", "url": "<URL HERE>"}}`

Here's an example curl command to add a new URL to hoarder:

```
curl -v -X POST http://localhost:3000/api/trpc/bookmarks.createBookmark -H 'Authorization: Bearer ak1_7a559b48bb86b5740f3f_47f38c9bfb841f45ec09' --json '{"json": {"type": "link", "url": "https://google.com" }}'
```

**Comment by afischer211** [comment]
> @danielslyman @afischer211 while Hoarder currently doesn't have a "REST" API, it does have an API:
> 
> 
> 
> You can use it as:
> 
> 
> 
> 1. Get an API key from the settings page of Hoarder.
> 
> 2. Send a POST request to `https://demo.hoarder.app/api/trpc/bookmarks.createBookmark`:
> 
>   a. Set the `Authorization` header to `Bearer <api_key>`.
> 
>   b. Set `Content-Type` header to `application/json`.
> 
>   c. Set the body to `{"json": {"type": "link", "url": "<URL HERE>"}}`
> 
> 
> 
> Here's an example curl command to add a new URL to hoarder:
> 
> 
> 
> ```
> 
> curl -v -X POST http://localhost:3000/api/trpc/bookmarks.createBookmark -H 'Authorization: Bearer ak1_7a559b48bb86b5740f3f_47f38c9bfb841f45ec09' --json '{"json": {"type": "link", "url": "https://google.com" }}'
> 
> ```

Thanks for your answer! Are there any more API methods/URLs for calling from a client?

**Comment by MohamedBassem** [comment]
This is happening in the next release!
