### ISSUE TITLE
Feature request: possibility to paste image into a note

### ISSUE THREAD

**Issue by shalak** [hoarder-app/hoarder#203]
Would be great to be able to simply cmd+v a picture that I have in a clipboard into a note.

**Comment by shalak** [comment]
Sorry, only now I noticed that the "Discussions" page is enabled here, I'll close this and recreate the request there

**Comment by ItsNoted** [comment]
Just here to say the copy to clipboard button is showing but does not work on Chrome. When clicked nothing happens. It doesn't even appear when I use Firefox.
