### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by bstone108** [hoarder-app/hoarder#219]
Got a few suggestions,  ability to set upload limits on file sizes,  right now they are set much too low for my needs.

Second, mobile uploads have quality reduced significantly which is not ideal.  would like to upload original quality.

third, a bulk upload option from mobile device would be nice.

Last, integration with phones share function, so a link, image or images, or whatever can be directly shared with hoarder and uploaded in background.  Support for more than just pictures would be nice too.  Parsing pdf's, word documents and so on would be very helpful.

**Comment by kamtschatka** [comment]
1. Are you not setting the MAX_ASSET_SIZE_MB config, or is it not working? See: https://docs.hoarder.app/configuration
2. Agreed^^
3. True
4. Link/Image sharing works already for me(Android), by just clicking share and then selecting the hoarder app. (Not multiple images though)

**Comment by bstone108** [comment]
found the max asset size tag after I sent the message.  using the unraid template which didn't have it already added.  fixed that.  and on 4, my suggestion was meant for bulk upload sharing as well :) and expanding formats it can deal with.  plenty of text extraction tools out there that could be used for handling documents.

**Comment by bstone108** [comment]
additional feature request.  tapping on a picture in mobile app does nothing.  can we have it bring up a full size view like on the webpage?

**Comment by MohamedBassem** [comment]
Most of those are solved by now (except maybe the bulk upload option). So closing this for now, and we can file a separate issue for that if it's really needed.
