### ISSUE TITLE
Empty bookmark

### ISSUE THREAD

**Issue by arobase-che** [hoarder-app/hoarder#225]
Hello,

What about empty bookmark?
I have the feeling that I should not be able to « Save » an empty bookmark.
Maybe the Save button and ||Ctrl||  + ||Enter||  should be disabled when the « New item » textbox is empty?

Or maybe en empty bookmark should not be processed and early discarded ?

Thank you

**Comment by MohamedBassem** [comment]
This is good call. We shouldn't allow empty bookmarks :)
