### ISSUE TITLE
Local tags

### ISSUE THREAD

**Issue by mrbreil** [hoarder-app/hoarder#226]
Hello, first of all thank you for this software. I have a suggestion for a feature. I think that it is one of the most important features, along with the option to authenticate externally. If you host your own bookmarks and your own llm, you also have your own authentication (my two cents). So now to my feature wish:
An English web UI is OK, but I speak and think in a different language. Even bookmarks in my native language are given English tags. It would be great if you could set the language in which OLLAMA creates the tags.

**Comment by mrbreil** [comment]
I think similar https://github.com/hoarder-app/hoarder/issues/170

**Comment by MohamedBassem** [comment]
Regarding the inference language, you can already configure that in hoarder by setting `INFERENCE_LANG` on the workers container to whatever language you want. You can find all the settings here (https://docs.hoarder.app/configuration).

For the authentication, Oauth is indeed coming :)

**Comment by mrbreil** [comment]
Man, I'm stupid. Excuse me.
