### ISSUE TITLE
Function suggestions, webpage snapshot

### ISSUE THREAD

**Issue by hongruilin** [hoarder-app/hoarder#229]
Sometimes we encounter such a situation: we suddenly see an interesting article and want to read it after work, but when we have time to read it after work, the article has already been deleted. If there is a web snapshot that can be turned on or off according to user needs, when it is turned on, it can cache a bookmarked page, so that even if the original article is deleted, it can still be viewed. This seems very useful

**Comment by kamtschatka** [comment]
There are multiple options already:
* Extracting the content. Does not work perfectly all the time
* Taking a screenshot. Some articles need scrolling, so it is possible to enable full page screenshot (as in: while taking the screenshot it will scroll all the way down). See CRAWLER_STORE_SCREENSHOT and CRAWLER_FULL_PAGE_SCREENSHOT
* Saving an archive: This stores the full page as an archive for you to load later. See CRAWLER_FULL_PAGE_ARCHIVE

The configuration can be seen here: https://docs.hoarder.app/configuration

Is your suggestion to any of the available suggestions?

**Comment by hongruilin** [comment]
> There are multiple options already:
> 
> * Extracting the content. Does not work perfectly all the time
> * Taking a screenshot. Some articles need scrolling, so it is possible to enable full page screenshot (as in: while taking the screenshot it will scroll all the way down). See CRAWLER_STORE_SCREENSHOT and CRAWLER_FULL_PAGE_SCREENSHOT
> * Saving an archive: This stores the full page as an archive for you to load later. See CRAWLER_FULL_PAGE_ARCHIVE
> 
> The configuration can be seen here: https://docs.hoarder.app/configuration
> 
> Is your suggestion to any of the available suggestions?

I hope to cache only some label copies

**Comment by kamtschatka** [comment]
I am sorry, I don't understand what that means, can you please go into more details or show an example or something like that?

**Comment by hongruilin** [comment]
> I am sorry, I don't understand what that means, can you please go into more details or show an example or something like that?

For example, there are a total of 4 bookmarks, and we can choose to cache only the web page copy of bookmark a

**Comment by undaunt** [comment]
@kamtschatka I think @hongruilin is suggesting leveraging a tag based system indicating which links should be fully locally cached (with either/or full page archive/screenshot) or not, instead of only globally at the environmental variable level.

**Comment by kamtschatka** [comment]
I think this is the same as https://github.com/hoarder-app/hoarder/issues/398, right? You'll be able to select which bookmark to do a full crawl on

**Comment by kamtschatka** [comment]
from what I understand, this is now handled with #398, where you can select which bookmark to make available as archive, without having to make all of them available offline.
