### ISSUE TITLE
Function suggestion: config of the maximum number of registrations or config of enable the registration function

### ISSUE THREAD

**Issue by MarkOverthinker** [hoarder-app/hoarder#231]
It seems that anyone can access my website and register and log in. I don't think it is elegant. Can I add configuration options so that it can only be logged in by a few users?

**Comment by MohamedBassem** [comment]
Hey, you can disable new account creations with `DISABLE_SIGNUPS=true`, you can find more configs in https://docs.hoarder.app/configuration

**Comment by MarkOverthinker** [comment]
> Hey, you can disable new account creations with `DISABLE_SIGNUPS=true`, you can find more configs in https://docs.hoarder.app/configuration

Thanks, sir. I missed it when I read configuration,

**Comment by MohamedBassem** [comment]
No worries!
