### ISSUE TITLE
[Feature Request] Support for adding Images by URL

### ISSUE THREAD

**Issue by mutschler** [hoarder-app/hoarder#246]
I know there's image Upload by drag & drop which i currently use, but there are 2 things bothering me:
1. The Original Source is lost (im putting it in notes atm)
2. I have to save download the image and drag it to hoarder

When adding the URL directly it acts exactly as in #28 (image seems to be downloaded, stored, shown in preview) but is not viewable when opening detail view

since there's alread #28 with an additional `Content-Type` for display... maybe consider support for multiple `Content-Types` in the detail view.

**Comment by kamtschatka** [comment]
Yeah i already have that on the radar
