### ISSUE TITLE
Bookmark Import results in Unsupported Asset Type

### ISSUE THREAD

**Issue by node-daemon** [hoarder-app/hoarder#255]
Dragging and dropping an .html file through the UI results in an Unsupported Asset Type error
![bookmark_fail](https://github.com/hoarder-app/hoarder/assets/156556640/5a192b55-67fe-418e-b16d-e159a0dd79bf)

**Comment by kamtschatka** [comment]
What exactly is the issue you are having? Importing html files is not possible, except for bookmark exports from browsers.

**Comment by node-daemon** [comment]
I closed this as this is not an issue, just my lack of understanding on how releases work. If there's a way to delete it outright by an admin, please feel free to do so.
