### ISSUE TITLE
[Feature Request] Custom Images

### ISSUE THREAD

**Issue by EkanaStone** [hoarder-app/hoarder#260]
### Requested Feature
The ability to attach a photo of my choosing to a bookmark.

### Explanation 
I personally came to this looking for a self-hosted Pinterest replacement as well as bookmarker. One of the key features of Pinterest is the ability to attach links to pictures and vice-versa. It can also do that automatically from its extension. 

Now I would love to have all that functionality but my most basic ask is the ability to expand the bookmark and add a photo, and maybe upon creating the bookmark in the extension it has an option to paste an image link or directly upload one.

**Comment by kamtschatka** [comment]
Is this the same as https://github.com/hoarder-app/hoarder/issues/106 or is it different?

**Comment by EkanaStone** [comment]
Its similar for sure. Would have the same outcome all the same. I just suggest copying what pinterest does.

**Comment by MohamedBassem** [comment]
I think this is a reasonable ask, let me merge your request into #106 and generalize #106 a bit. @kamtschatka have don't some recent refactoring that can make this a lot easier.

**Comment by MohamedBassem** [comment]
Done updating #106, let's track this request there.
