### ISSUE TITLE
feature request: pdf support

### ISSUE THREAD

**Issue by asg0451** [hoarder-app/hoarder#28]
I'd like to be able to capture a pdf url, eg https://gavinadair.files.wordpress.com/2017/03/baker-changes-of-mind.pdf

currently, it is captured but no tags or added nor is text extracted
![image](https://github.com/MohamedBassem/hoarder-app/assets/4358545/3f31cbf2-4b34-4f1f-9698-3833e5685a91)

logs:

```
hoarder-workers 2024-03-27T16:53:27.624Z info: [Crawler][9] Will crawl "https://gavinadair.files.wordpress.com/2017/03/baker-changes-of-mind.pdf" for link with id "h03n4dihn2gp0kn8giwiyir7"                                                                                           hoarder-workers 2024-03-27T16:53:27.813Z info: [search][30] Completed successfully                                                                                                                                                                                                      hoarder-workers 2024-03-27T16:53:27.822Z error: [Crawler][9] Crawling job failed: {}                               
```

**Comment by MohamedBassem** [comment]
Yeah, only html `Content-Type` currently works. PDF support is a reasonable feature request though. Will add it to the backlog. Thanks!

**Comment by MarkLuk** [comment]
Exactly my use-case! I research & bookmark a lot of PDF files. Would like to have support to view their content in the preview.
