### ISSUE TITLE
last version bookmarks import error 

### ISSUE THREAD

**Issue by nsk** [hoarder-app/hoarder#281]
hi ,
on the latest pull version, still impossible to import a list of favorites in drag and drop mode from chrome, it says that something is going wrong?

![chrome_7uBi5VRQ5r](https://github.com/hoarder-app/hoarder/assets/1135867/70abf0e0-b148-4815-91a5-c6c3b178e0d9)

**Comment by kamtschatka** [comment]
Please post the logs, the screenshot alone does not help.

**Comment by nsk** [comment]
@kamtschatka I have nothing in the logs

**Comment by kamtschatka** [comment]
There is either something in the logs of the "web" container or in the devtools. 
alternatively you can also provide the file you want to import (i am also in discord, if you do not want to share it publicly)

**Comment by carduswork** [comment]
got the same error,here is the log in chrome,maybe helpful
![image](https://github.com/hoarder-app/hoarder/assets/17943894/639fb0ac-c1b4-4e02-b9c4-c375bbe71588)
![image](https://github.com/hoarder-app/hoarder/assets/17943894/10194280-8068-4f48-82c0-bffb06a9c766)

**Comment by kamtschatka** [comment]
I just tried it with my installation and everything works fine, so must have to do with your state/bookmark file.
What happens? Does it not import anything at all, or are some of them skipped?
Can you provide the bookmarks file?

**Comment by carduswork** [comment]
I exported my bookmark file from a platform like raindrop,it works fine after i changed my bookmark file to the file exported from my chrom,thanks!

> I just tried it with my installation and everything works fine, so must have to do with your state/bookmark file. What happens? Does it not import anything at all, or are some of them skipped? Can you provide the bookmarks file?

**Comment by kamtschatka** [comment]
from a platform like raindrop, or raindrop? 
I would like to try that out when I am back home. There is a safeguard against importing completely random bookmark files, but maybe there is a slight difference between the browser exported format and whatever you tried.

**Comment by nsk** [comment]
hi I did the conversion to .txt via the CLI do you think it would be possible to directly import the all-linx.txt directly into the interface without going through the CLI, I tried the other way to do it too but it doesn't work

**Comment by kamtschatka** [comment]
At some point you'll have to provide the file or some instructions for me to reproduce what you are doing, otherwise whis discussion will go nowhere

**Comment by nsk** [comment]
I have a raindrop account I'm trying this way I'll come back and tell you if it works later

**Comment by nsk** [comment]
the same problem via raindrop, I'll send you my export file with
[export.zip](https://github.com/user-attachments/files/16132172/export.zip)

**Comment by kamtschatka** [comment]
seems like the file simply has too many URLs in there, causing the requests to get too big. 
I would also recommend deleting the export.zip again

**Comment by nsk** [comment]
how many links max in the file?? do you think ? thx

**Comment by kamtschatka** [comment]
The maximum length the URL can get is 15000 characters, after that this error happens. 
each bookmark adds 26 characters to the URL length + whatever you use to access your installation. This leads to a maximum of around 600 for my installation. 
Go for roughly 500 and you should be fine.

I have also opened a PR to limit the length automatically

**Comment by Snuupy** [comment]
I was only able to batch add ~150 urls on my instance

I had ~350 to add so I had to split up adding them

can we increase the character length on the web form?

the error was also not very helpful "Failed to fetch"

**Comment by MohamedBassem** [comment]
@Snuupy How did you get your list of links? There's a better importing UI now in the settings than just adding them to the editor box.

**Comment by Snuupy** [comment]
@MohamedBassem I had ~500 open tabs in Firefox and used https://addons.mozilla.org/en-US/firefox/addon/export-tabs-urls-and-titles/ to add each window (subject) to each collection. One of my windows had 350 tabs open. It was not an import of any other tools (although I have another 4k+ in raindrop I have yet to import)

**Comment by MohamedBassem** [comment]
@Snuupy As you figured out, importing 350 links from the editor box doesn't give you the best experience. You might be better off using the CLI for such list instead (https://docs.hoarder.app/import#import-using-the-cli), if you're comfortable with using CLIs.
