### ISSUE TITLE
[Feature Request] OCR search text in images

### ISSUE THREAD

**Issue by lethefrost** [hoarder-app/hoarder#296]
It would be especially helpful when you have a lot of screenshots, diagrams, photo of slides, etc., embedded in documents or as stand alone image files. Text in images may contain a large amount of information. However, it's not very easy to retrieve them in the traditional ways of file management. It would be greatly appreciated if you could consider making them searchable.

**Comment by MohamedBassem** [comment]
hmmm, OCR is a cool idea indeed. My only concern is finding a good OCR tool that would work with different languages.

**Comment by MohamedBassem** [comment]
[tesseract.js](https://github.com/naptha/tesseract.js) looks cool indeed. We can probably add it to the roadmap at some point

**Comment by akshara-tg** [comment]
Without OCR (which allows for searching text within images), the hoarding images become somewhat pointless.

**Comment by MohamedBassem** [comment]
@Arcturuss OCR for uploaded images is something on our roadmap and I'm definitely planning to do it pretty soon.

**Comment by MohamedBassem** [comment]
OCR is now implemented and will be available in the next release.

**Comment by drycounty** [comment]
Can you tell me how this is implemented?  Do I need to specify any of the ENV variables for it to work?  Can't seem to get it to work from photos of pages of text.

**Comment by MohamedBassem** [comment]
@drycounty it's enabled by default. Currently, we don't expose the extracted text, but we only index it for search. Try searching for the content of the page and see if it'll showup.

**Comment by radonmiser** [comment]
Is the extracted text forced into the inference lang? My inference lang is English and I'm unable to find any of my Japanese bookmarks with Japanese
