### ISSUE TITLE
[Feature Request] inside an item, add the Memos "checkbox" feature to do a check list into an item

### ISSUE THREAD

**Issue by adorsch59** [hoarder-app/hoarder#300]
In Memos, we can use - [ ] or - [x] to create a list of checkboxes inside a note.
It will be very usefull in Hoarder.
I really like this feature.
![image](https://github.com/user-attachments/assets/bf15c5c1-9003-4fa1-9482-839472686106)
Thank You in advance.

**Comment by adorsch59** [comment]
Memos:
![image](https://github.com/user-attachments/assets/d462f489-e9b2-4b6b-9da5-8a23b70617f0)
https://www.usememos.com/docs/getting-started/content-syntax

**Comment by kamtschatka** [comment]
Sounds like this? https://github.com/hoarder-app/hoarder/issues/45

**Comment by kamtschatka** [comment]
I opened a PR to add this feature.
Looks like this:
![image](https://github.com/user-attachments/assets/1b930d25-c12e-4fc0-8829-39ff19e60682)

Unfortunately it is not very tight and that is because of the way those markdowns are displayed in general. They are using tailwindcss with prose, which adds a lot of margin/padding to the items.
I think that styling is something that should be discussed in general though, so I did not make any effort to fix that now.

**Comment by adorsch59** [comment]
> I opened a PR to add this feature. Looks like this: ![image](https://private-user-images.githubusercontent.com/22147234/348465088-1b930d25-c12e-4fc0-8829-39ff19e60682.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNTI4ODYsIm5iZiI6MTcyMTA1MjU4NiwicGF0aCI6Ii8yMjE0NzIzNC8zNDg0NjUwODgtMWI5MzBkMjUtYzEyZS00ZmMwLTg4MjktMzlmZjE5ZTYwNjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE0MDk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjNDgyMjdjYzlmYjlhMzE4ZDVlZWEyZTNhNTcxMTE5OGRkNGI0M2MwMDMwODk1Y2UzOGQ1ODIzNGY1NTQ5ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AdevCstVO8l_ng-h6suG1Otj4Z7C36bOahiXVUT3OPg)
> 
> Unfortunately it is not very tight and that is because of the way those markdowns are displayed in general. They are using tailwindcss with prose, which adds a lot of margin/padding to the items. I think that styling is something that should be discussed in general though, so I did not make any effort to fix that now.

Yes! this is exactly that.
Need to handle checklist/checkbox.
Creation using markdown or not, on my side I don't care, I think the memos checkbox syntax is easy to use.
And, yes, we must be able to interact with the checkbox with the mouse.

I thing your PR will answer my need, so this ticket can be closed when the release is done.
Thank you.

**Comment by MohamedBassem** [comment]
This got released in the last release

**Comment by wiso** [comment]
> This got released in the last release

Is the mouse interaction working? Doesn't seem so in 0.26.0

**Comment by ArnoldDeRuiter** [comment]
I also am facing the limitation of not being able to click/check/toggle the Markdown checkboxes, which would be incredibly helpful.
