### ISSUE TITLE
ios app not showing any list

### ISSUE THREAD

**Issue by echo-saurav** [hoarder-app/hoarder#311]
![image](https://github.com/user-attachments/assets/40e61e25-529c-4b2a-8922-db888cc5d105)

**Comment by echo-saurav** [comment]
ok i fixed it by removing `/` at the end of host address. though, hoarder should trim address by itself

**Comment by MohamedBassem** [comment]
Sounds like we do trim the slash in the extension (https://github.com/hoarder-app/hoarder/blob/main/apps/browser-extension/src/NotConfiguredPage.tsx#L25) but not in the mobile app, sounds like a bug indeed.
