### ISSUE TITLE
unable to log in on the chrome extension

### ISSUE THREAD

**Issue by asg0451** [hoarder-app/hoarder#313]
when i try and configure server in the chrome extension, it fails with an error. the extension's console prints this error:
(url redacted)
```
Access to fetch at 'https://REDACTED.xxx/api/trpc/apiKeys.exchange?batch=1' from origin 'chrome-extension://kgcjekpmcjjogibpjebkhaanilehneje' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by MohamedBassem** [comment]
Are you using a reverse proxy in front of hoarder? Any special setup for this reverse proxy?

**Comment by asg0451** [comment]
yes, i have it running both over tailscale and with a traefik reverse proxy. it works fine in my browser and definitely used to work in the extension.

**Comment by asg0451** [comment]
HM ok i got it working by manually specifying http:// and adding a slash at the end. not sure which of those did it but 🤷 

thx for the quick response anyway!
