### ISSUE TITLE
Lost password but still logged in

### ISSUE THREAD

**Issue by kjgcoop** [hoarder-app/hoarder#314]
First off, thank you, Hoarder creator(s), for making such a nice piece of software!

I got a new phone and discovered that my browser hadn't saved my Hoarder password. I'm still logged in on my laptop, so I'm not totally locked out. In the interest of keeping things interesting, my server doesn't send email, so if there's an option to trigger a password reset email, I can't use it. 

It's a docker instance. If I can get my bookmarks out, I don't mind torpedoing it and starting again. I didn't see any way to export my data, although I did see that I could list my links at the CLI (https://docs.hoarder.app/command-line about changing a password).

My end game is being able to log into my phone. I figure either I can get CLI access to one of the Hoarder docker instances (I'm not sure which one) to go in and manually monkey with whatever database Hoarder relies on, or export my data then re-import it into a new install. I don't have a preference. Then as step two, save the password somewhere. 

I don't mind doing some scripting if it makes the process simpler. 

Any help would be much appreciated. Thank you!

**Comment by kjgcoop** [comment]
I've gotten this far:

```
sqlite> .schema account
CREATE TABLE `account` (
	`userId` text NOT NULL,
	`type` text NOT NULL,
	`provider` text NOT NULL,
	`providerAccountId` text NOT NULL,
	`refresh_token` text,
	`access_token` text,
	`expires_at` integer,
	`token_type` text,
	`scope` text,
	`id_token` text,
	`session_state` text,
	PRIMARY KEY(`provider`, `providerAccountId`),
	FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade
);
```

I wasn't able to rainbow table the password column into its original value, so I assume it's salted, but I don't see any clue as to what the salt might be. 

Any insight would be much appreciated. Thank you!

**Comment by kjgcoop** [comment]
Sorry, I should have done this all as one post. I looked at `packages/trpc/auth.ts` and noted that it's hashed with bcrypt. I went to https://bcrypt-generator.com/ and generated a new password and put it in db.db, but when I tried to put it into the web UI, it rejected my new password.

**Comment by MohamedBassem** [comment]
Hi @kjgcoop, we should probably add a reset password functionality in the admin CLI indeed. But for now, since seem to be comfortable with tinkering with the database, your easiest route is just creating a new user, and then updating the database row of your original user with the password of your new user. Hoarder doesn't currently use salts (known gap), so just copying the passwords hash between accounts should do the trick.

**Comment by kjgcoop** [comment]
Awesome! I'm all set. Thank you!

**Comment by raviwarrier** [comment]
> Hi @kjgcoop, we should probably add a reset password functionality in the admin CLI indeed. But for now, since seem to be comfortable with tinkering with the database, your easiest route is just creating a new user, and then updating the database row of your original user with the password of your new user. Hoarder doesn't currently use salts (known gap), so just copying the passwords hash between accounts should do the trick.

Is there a way for non-techie guys to be able to do this? I am in the same boat today as kjgcoop was.
