### ISSUE TITLE
Redirects to localhost:3000 on sign out

### ISSUE THREAD

**Issue by alexkutsan** [hoarder-app/hoarder#323]
When I acces hoader by specific IP address on specific port. 
Then logout my account - it redirects me to `localhost:3000`
May be there is ENV variable where I can put a a host:port of the service? 

https://github.com/user-attachments/assets/34ff9d9a-f964-4832-8831-03a98b31328d

**Comment by kamtschatka** [comment]
Did you not set the NEXTAUTH_URL correctly? This exact problem is mentioned in the documentation: https://docs.hoarder.app/configuration

**Comment by MohamedBassem** [comment]
@alexkutsan As @kamtschatka mentioned, setting up `NEXTAUTH_URL` will solve the problem :)
