### ISSUE TITLE
[FR] Adding Healthchecks do the dockerfiles

### ISSUE THREAD

**Issue by wuast94** [hoarder-app/hoarder#326]
would be nice if healthchecks would be added to the containers 😊 im running a swam cluster and containers without a healtheck can make problems

**Comment by MohamedBassem** [comment]
@wuast94 Makes sense. You can define the healthchecks manually from the compose file as well btw.

**Comment by wuast94** [comment]
yeah i know, the thing is on the worker part i dont even know how to define the healthcheck. 

on the web part it should be an extra endpoint that just return a json or something like that if the web part and all sub parts are working as intended (redis db and so on), its more efficient than just checking a rendered html page.

**Comment by MohamedBassem** [comment]
@wuast94 makes sense. The good news is that the worker container is going away in the next release. For the web container, I can add a dummy ping endpoint.

**Comment by wuast94** [comment]
well than it can be a thing i can do maybe. im in the beginning of development (atm im building a web app with svelte), but an healtheck endpoint seams like a nice thing to do for learning 😊

**Comment by MohamedBassem** [comment]
@wuast94 Sure! Hoarder uses Next.js. You can drop a `ping/route.ts` here (https://github.com/hoarder-app/hoarder/tree/main/apps/web/app/api) and implement a dummy endpoint (using this docs: https://nextjs.org/docs/app/api-reference/file-conventions/route) to return a plain text containing "PONG" for example. Then you should be able to call it with `http://localhost:3000/api/ping`

**Comment by wuast94** [comment]
yeah sounds like a nice starting point. if i can i will also return if the redis and db connection are ok 😊

**Comment by MohamedBassem** [comment]
Redis is going away, and the db is sqlite db, so it's usually always ok :)

**Comment by wuast94** [comment]
my bad i meaned meilisearch

**Comment by MohamedBassem** [comment]
This is now done with your PR, thanks!

**Comment by huyz** [comment]
Should the Dockerfile and/or docker-compose.yml files be updated to include the healthcheck?

**Comment by wuast94** [comment]
i will do a PR

**Comment by wuast94** [comment]
@huyz #508 will add this
