### ISSUE TITLE
Reconsider `gpt-3.5-turbo-0125` default

### ISSUE THREAD

**Issue by lnicola** [hoarder-app/hoarder#334]
According to the [pricing](https://openai.com/api/pricing/) page, `gpt-4o-mini` is much cheaper, but still better than `gpt-3.5-turbo-0125`. Is there any reason not to use that instead?

**Comment by MohamedBassem** [comment]
Hi, already did the change in (https://github.com/hoarder-app/hoarder/commit/b74bee82baada515bcd0e4401d8ba12225e0f7a9). It's going to be available in the next release. In the meanwhile, you can easier switch to `latest` tag, or just update `INFERENCE_TEXT_MODEL` and `INFERENCE_IMAGE_MODEL` to `gpt-4o-mini`
