### ISSUE TITLE
OPENAI key not working

### ISSUE THREAD

**Issue by rserbitar** [hoarder-app/hoarder#336]
openai key does not seem to work. I re-created the key several times just to make sure that its not a copy and paste error . . .

`
2024-07-29T09:56:20.405Z error: [inference][6] inference job failed: Error: 401 Incorrect API key provided: .... You can find your API key at https://platform.openai.com/account/api-keys.`

Whats the best way to debug this? Whats the best place to check what is being sent to the API?

**Comment by lnicola** [comment]
FWIW, I've just set up Hoarder, OpenAI seems to be working fine. I was getting "Error: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors." in the begging, but it sorted itself out after 10 minutes or so.

**Comment by rserbitar** [comment]
Because of whaterver reason inside the worker node printenv looks like that (just showing parts of it):

```
YARN_VERSION=1.22.19
SHLVL=1
HOME=/root
OPENAI_API_KEY=...
DATA_DIR=/data
container=podman
HOARDER_VERSION=release
DISABLE_SIGNUPS=true
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SERVER_VERSION=0.15.0
```

All other secrets are shown normally and not like ... (removed them for security reasons obviously).

**Comment by rserbitar** [comment]
got it. own stupidity. 
I commented out:

`# OPENAI_API_KEY: ...`

in the default docker-compose.yaml and added the correct value in addition to an .env file. The .yaml took precedence . . .
