### ISSUE TITLE
Hoarder CLI failes to connect using HTTPS, but works for HTTP

### ISSUE THREAD

**Issue by Antebios** [hoarder-app/hoarder#340]
I am following instructions to upload my large HTML export.  When trying to use the Hoarder CLI using HTTP works, but failes when using HTTPS.

![image](https://github.com/user-attachments/assets/2aa64034-e1db-49e4-868e-28663a94643f)

The web interface is working great over HTTPS.

**Comment by kamtschatka** [comment]
Do you have a proper SSL certificate? Since it works via HTTP, it must have something to do with the secure connection, so maybe you have a self signed certificate?

**Comment by Antebios** [comment]
Yes.  Though this is my homelab, I have DNS and home domain's certificate server working perfectly.  I was running this command from the machine that is on the domain with the root certificate loaded.  And the HTTPS URL works perfectly.

![image](https://github.com/user-attachments/assets/de7af3fb-56d6-4eca-ba27-51bd30188466)

**Comment by kamtschatka** [comment]
Did you get it to work?
My guess would be that the self signed certificate is simply not accepted in node. Your screenshot is showing that The browser accepts the certificate, but node.js seems to have its own certificate store, where it would need to be accepted.

Seems like if you set "NODE_TLS_REJECT_UNAUTHORIZED", you can cause node to ignore self signed certificate errors.
https://stackoverflow.com/questions/68592669/how-to-set-value-for-node-tls-reject-unauthorized-0-in-mac

**Comment by kamtschatka** [comment]
closing as there was no response. We can reopen if there is a response
