### ISSUE TITLE
Failed to read DnsConfig

### ISSUE THREAD

**Issue by aubreyskingdom** [hoarder-app/hoarder#343]
I'm attempting to install Hoarder for the first time and I'm getting

Failed to read DnsConfig error and I cannot access the Hoarder site at all.

docker-compose:
`version: "3.8"
services:
  web:
    image: ghcr.io/hoarder-app/hoarder-web:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - data:/data
    ports:
      - 23000:23000
    env_file:
      - /share/Plex/plugins/Hoarder/hoarder.env
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      DATA_DIR: /data
  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis:/data
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.6
    restart: unless-stopped
    env_file:
      - /share/Plex/plugins/Hoarder/hoarder.env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data
  workers:
    image: ghcr.io/hoarder-app/hoarder-workers:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - data:/data
    env_file:
      - /share/Plex/plugins/Hoarder/hoarder.env
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
      # OPENAI_API_KEY: ...
    depends_on:
      web:
        condition: service_started

volumes:
  redis:
  meilisearch:
  data:`

hoarder.env:
`HOARDER_VERSION=release
NEXTAUTH_SECRET=key
MEILI_MASTER_KEY=key
NEXTAUTH_URL=http://ip:38930
DATA_DIR=/share/Plex/plugins/Hoarder
REDIS_HOST=http://ip
REDIS_PORT=6379
OPENAI_API_KEY=key`

**Comment by MohamedBassem** [comment]
The DNS config error is a red herring and irrelevant. What error are you seeing when you access hoarder from the browser? Can you also share the logs from the different containers?

**Comment by aubreyskingdom** [comment]
`hoarder-meilisearch-1  | 
hoarder-meilisearch-1  | 888b     d888          d8b 888 d8b                                            888
hoarder-meilisearch-1  | 8888b   d8888          Y8P 888 Y8P                                            888
hoarder-meilisearch-1  | 88888b.d88888              888                                                888
hoarder-meilisearch-1  | 888Y88888P888  .d88b.  888 888 888 .d8888b   .d88b.   8888b.  888d888 .d8888b 88888b.
hoarder-meilisearch-1  | 888 Y888P 888 d8P  Y8b 888 888 888 88K      d8P  Y8b     "88b 888P"  d88P"    888 "88b
hoarder-meilisearch-1  | 888  Y8P  888 88888888 888 888 888 "Y8888b. 88888888 .d888888 888    888      888  888
hoarder-meilisearch-1  | 888   "   888 Y8b.     888 888 888      X88 Y8b.     888  888 888    Y88b.    888  888
hoarder-meilisearch-1  | 888       888  "Y8888  888 888 888  88888P'  "Y8888  "Y888888 888     "Y8888P 888  888
hoarder-meilisearch-1  | 
hoarder-meilisearch-1  | Config file path:      "none"
hoarder-meilisearch-1  | Database path:         "./data.ms"
hoarder-meilisearch-1  | Server listening on:   "http://0.0.0.0:7700"
hoarder-meilisearch-1  | Environment:           "development"
hoarder-meilisearch-1  | Commit SHA:            "1a083d54fc2840ac59530e5395397211cace35be"
hoarder-meilisearch-1  | Commit date:           "2024-02-13T14:47:34+00:00"
hoarder-meilisearch-1  | Package version:       "1.6.2"
hoarder-meilisearch-1  | Anonymous telemetry:   "Disabled"
hoarder-meilisearch-1  | 
hoarder-meilisearch-1  | A master key has been set. Requests to Meilisearch won't be authorized unless you provide an authentication key.
hoarder-meilisearch-1  | 
hoarder-meilisearch-1  | Check out Meilisearch Cloud!   https://www.meilisearch.com/cloud?utm_campaign=oss&utm_source=engine&utm_medium=cli
hoarder-meilisearch-1  | Documentation:                 https://www.meilisearch.com/docs
hoarder-meilisearch-1  | Source code:                   https://github.com/meilisearch/meilisearch
hoarder-meilisearch-1  | Discord:                       https://discord.meilisearch.com
hoarder-meilisearch-1  | 
hoarder-meilisearch-1  | [2024-08-04T16:57:44Z INFO  actix_server::builder] starting 4 workers
hoarder-meilisearch-1  | [2024-08-04T16:57:44Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
hoarder-workers-1      | Corepack is about to download https://registry.npmjs.org/pnpm/-/pnpm-9.6.0.tgz.
hoarder-workers-1      | 
hoarder-workers-1      | > @hoarder/workers@0.1.0 start:prod /app/apps/workers
hoarder-workers-1      | > tsx index.ts
hoarder-workers-1      | 
hoarder-workers-1      | 2024-08-04T16:58:08.180Z info: Workers version: 0.15.0
hoarder-workers-1      | 2024-08-04T16:58:08.194Z info: [Crawler] Connecting to existing browser instance: http://chrome:9222
hoarder-workers-1      | (node:34) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
hoarder-workers-1      | (Use `node --trace-deprecation ...` to show where the warning was created)
hoarder-workers-1      | 2024-08-04T16:58:08.226Z info: [Crawler] Successfully resolved IP address, new address: http://172.29.144.2:9222/
hoarder-redis-1        | 1:C 04 Aug 2024 16:57:46.517 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
hoarder-workers-1      | 2024-08-04T16:58:10.717Z info: Starting crawler worker ...
hoarder-workers-1      | 2024-08-04T16:58:10.719Z info: Starting inference worker ...
hoarder-redis-1        | 1:C 04 Aug 2024 16:57:46.517 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
hoarder-workers-1      | 2024-08-04T16:58:10.719Z info: Starting search indexing worker ...
hoarder-redis-1        | 1:C 04 Aug 2024 16:57:46.517 * Redis version=7.2.5, bits=64, commit=00000000, modified=0, pid=1, just started
hoarder-redis-1        | 1:C 04 Aug 2024 16:57:46.517 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
hoarder-redis-1        | 1:M 04 Aug 2024 16:57:46.521 * monotonic clock: POSIX clock_gettime
hoarder-redis-1        | 1:M 04 Aug 2024 16:57:46.522 * Running mode=standalone, port=6379.
hoarder-redis-1        | 1:M 04 Aug 2024 16:57:46.531 * Server initialized
hoarder-web-1          |    ▲ Next.js 14.1.4
hoarder-chrome-1       | [0804/165747.011189:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
hoarder-web-1          |    - Local:        http://localhost:3000
hoarder-chrome-1       | [0804/165747.021965:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
hoarder-chrome-1       | [0804/165747.024185:WARNING:dns_config_service_linux.cc(427)] Failed to read DnsConfig.
hoarder-chrome-1       | [0804/165747.038914:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
hoarder-chrome-1       | [0804/165749.764528:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping mandatory platform policies because no policy file was found at: /etc/chromium/policies/managed
hoarder-chrome-1       | [0804/165749.764747:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping recommended platform policies because no policy file was found at: /etc/chromium/policies/recommended
hoarder-chrome-1       | 
hoarder-chrome-1       | DevTools listening on ws://0.0.0.0:9222/devtools/browser/9525767a-4390-4372-9a3b-f6dcf0866f23
hoarder-chrome-1       | [0804/165749.773200:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
hoarder-chrome-1       | [0804/165749.900179:WARNING:dns_config_service_linux.cc(427)] Failed to read DnsConfig.
hoarder-chrome-1       | [0804/165750.130240:WARNING:sandbox_linux.cc(418)] InitializeSandbox() called with multiple threads in process gpu-process.
hoarder-redis-1        | 1:M 04 Aug 2024 16:57:46.638 * Loading RDB produced by version 7.2.5
hoarder-redis-1        | 1:M 04 Aug 2024 16:57:46.638 * RDB age 351 seconds
hoarder-web-1          |    - Network:      http://0.0.0.0:3000
hoarder-web-1          | 
hoarder-web-1          |  ✓ Ready in 4.8s
hoarder-redis-1        | 1:M 04 Aug 2024 16:57:46.638 * RDB memory usage when created 1.27 Mb
hoarder-redis-1        | 1:M 04 Aug 2024 16:57:46.638 * Done loading RDB, keys loaded: 3, keys expired: 0.
hoarder-redis-1        | 1:M 04 Aug 2024 16:57:46.638 * DB loaded from disk: 0.107 seconds
hoarder-redis-1        | 1:M 04 Aug 2024 16:57:46.638 * Ready to accept connections tcp`

**Comment by aubreyskingdom** [comment]
When I try to access via browser I get a Unable to connect message

**Comment by MohamedBassem** [comment]
@aubreyskingdom did you figure this out?

**Comment by kamtschatka** [comment]
No response from Author, but a response from someone else who managed to fix it. We can reopen if the issue persist and there is a response
