### ISSUE TITLE
iOS Share Sheet Gone

### ISSUE THREAD

**Issue by StackShard** [hoarder-app/hoarder#354]
Been using the app for a few days now and things are going well. Today I lost ability to share to the app from the share sheet (Default iOS sharing). I’ve rebooted the phone, but the share sheet is missing. I can send to mymind, etc but Hoarder is gone… Might need to reinstall the app. I haven’t done that yet.

**Comment by StackShard** [comment]
Speak of the devil, it’s back again…

**Comment by MohamedBassem** [comment]
hmmm, can't really debug that without repro steps :)

**Comment by StackShard** [comment]
> hmmm, can't really debug that without repro steps :)

Agreed. Was strange. Attribute to Apple thing. Still, I echo the other comment. Wish we could administer lists on mobile.

**Comment by MohamedBassem** [comment]
Let's track it as part of #353 then. Planning to work on it soon 👍
