### ISSUE TITLE
[Feature Request] Hide Items From Main Page

### ISSUE THREAD

**Issue by royaltongue** [hoarder-app/hoarder#356]
For more "sensitive" bookmarks, it would be nice to hide them from the main page and only show them in whatever lists they're added to

**Comment by MohamedBassem** [comment]
do you want this to happen automatically or manually? If what you need is "manual", this is exactly what the "archive" feature does.

**Comment by royaltongue** [comment]
Ah yes I did mean manually. I thought Archive was a sort of trash, my mistake
