### ISSUE TITLE
Data missing after upgrade

### ISSUE THREAD

**Issue by aubreyskingdom** [hoarder-app/hoarder#360]
I recently updated Hoarder and all my data is not syncing with the app, it appears as a freshly installed app.  Is there a way to get the data to sync back up?

Also, is there a way I can reset a lost password?

**Comment by kamtschatka** [comment]
the database is in your data folder. make sure it is mounted to the worker and web container

**Comment by aubreyskingdom** [comment]
Ah thanks! I was able to get it working :)
