### ISSUE TITLE
Crawler Failed

### ISSUE THREAD

**Issue by techdixie** [hoarder-app/hoarder#362]
`hoarder_workers      | 2024-08-23T19:24:44.650Z error: [Crawler] Failed to connect to the browser instance, will retry in 5 secs
hoarder_workers      | 2024-08-23T19:24:49.651Z info: [Crawler] Connecting to existing browser instance: http://chrome:9222`

I was getting some errors so I upgraded to the latest release.  Now I am getting a Crawler error. I haven't touched chrome. I am not using kubernetes. 

`services:
  web:
    image: ghcr.io/hoarder-app/hoarder-web:latest
    container_name: hoarder_web
    restart: unless-stopped
    volumes:
      - data:/data
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      DATA_DIR: /data
      HOARDER_VERSION: release
      NEXTAUTH_SECRET: generated_key
      MEILI_MASTER_KEY: second_generated_key
      NEXTAUTH_URL: http://ip:3000
  redis:
    image: redis:7.2-alpine
    container_name: hoarder_redis
    restart: unless-stopped
    volumes:
      - redis:/data
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: hoarder_chrome
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.6
    container_name: hoarder_meilisearch
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data
  workers:
    image: ghcr.io/hoarder-app/hoarder-workers:latest
    container_name: hoarder_workers
    restart: unless-stopped
    volumes:
      - data:/data
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
      OPENAI_API_KEY: open_ai_key
      INFERENCE_TEXT_MODEL: gpt-4o-mini
      INFERENCE_IMAGE_MODEL: gpt-4o-mini
    depends_on:
      web:
        condition: service_started
volumes:
  redis: null
  meilisearch: null
  data: null
networks:
  synobridge:
    external: true
`

Thanks! (edit: no clue how to keep formatting :/)

**Comment by MohamedBassem** [comment]
Hey, I see that you changed the container name of chrome to `hoarder_chrome`, in that case, you'll need to change the `BROWSER_WEB_URL` to `http://hoarder_chrome:9222`

**Comment by techdixie** [comment]
I'm wondering if my container rename is messing more than that up.  I'll remove those. I'm not getting tagging, homepage now says "Something went wrong".  The app says its failing at crawling.

**Comment by techdixie** [comment]
ok, this corrected ai tagging and the crawlers.  Only thing that looks like its not working is the homepage that says "Something went Wrong"

**Comment by MohamedBassem** [comment]
Can you share the logs of the web container?

**Comment by techdixie** [comment]
`hoarder-web-1          |       at async d (/app/apps/web/.next/server/chunks/624.js:4:32967)
hoarder-web-1          |       at async p (/app/apps/web/.next/server/chunks/624.js:4:33306)
hoarder-web-1          |       at async p (/app/apps/web/.next/server/app/dashboard/bookmarks/page.js:1:10468) {
hoarder-web-1          |     issues: [ [Object] ],
hoarder-web-1          |     addIssue: [Function (anonymous)],
hoarder-web-1          |     addIssues: [Function (anonymous)],
hoarder-web-1          |     errors: [ [Object] ]
hoarder-web-1          |   }
hoarder-web-1          | }
hoarder-web-1          | [Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
hoarder-web-1          |   digest: '2631817619'
hoarder-web-1          | }
hoarder-web-1          | m [TRPCError]: Output validation failed
hoarder-web-1          |     at p (/app/apps/web/.next/server/chunks/624.js:4:32429)
hoarder-web-1          |     at async d (/app/apps/web/.next/server/chunks/624.js:4:32967)
hoarder-web-1          |     ... 4 lines matching cause stack trace ...
hoarder-web-1          |     at async p (/app/apps/web/.next/server/app/dashboard/bookmarks/page.js:1:10468) {
hoarder-web-1          |   code: 'INTERNAL_SERVER_ERROR',
hoarder-web-1          |   [cause]: o [ZodError]: [
hoarder-web-1          |     {
hoarder-web-1          |       "code": "invalid_type",
hoarder-web-1          |       "expected": "string",
hoarder-web-1          |       "received": "undefined",
hoarder-web-1          |       "path": [
hoarder-web-1          |         "bookmarks",
hoarder-web-1          |         2,
hoarder-web-1          |         "content",
hoarder-web-1          |         "url"
hoarder-web-1          |       ],
hoarder-web-1          |       "message": "Required"
hoarder-web-1          |     }
hoarder-web-1          |   ]
hoarder-web-1          |       at get error [as error] (/app/apps/web/.next/server/chunks/917.js:63:14269)
hoarder-web-1          |       at Q.parseAsync (/app/apps/web/.next/server/chunks/917.js:63:16752)
hoarder-web-1          |       at async p (/app/apps/web/.next/server/chunks/624.js:4:32378)
hoarder-web-1          |       at async d (/app/apps/web/.next/server/chunks/624.js:4:32967)
hoarder-web-1          |       at async d (/app/apps/web/.next/server/chunks/624.js:4:32967)
hoarder-web-1          |       at async d (/app/apps/web/.next/server/chunks/624.js:4:32967)
hoarder-web-1          |       at async d (/app/apps/web/.next/server/chunks/624.js:4:32967)
hoarder-web-1          |       at async p (/app/apps/web/.next/server/chunks/624.js:4:33306)
hoarder-web-1          |       at async p (/app/apps/web/.next/server/app/dashboard/bookmarks/page.js:1:10468) {
hoarder-web-1          |     issues: [ [Object] ],
hoarder-web-1          |     addIssue: [Function (anonymous)],
hoarder-web-1          |     addIssues: [Function (anonymous)],
hoarder-web-1          |     errors: [ [Object] ]
hoarder-web-1          |   }
hoarder-web-1          | }`

**Comment by MohamedBassem** [comment]
@techdixie did you figure this out?

**Comment by techdixie** [comment]
Mine works perfectly now, but I did nothing to fix it unless there was an update at some point.  Sorry I can't be of more assistance.

**Comment by kamtschatka** [comment]
closing as it works now
