### ISSUE TITLE
[Feature Request] Rules for auto managing lists?

### ISSUE THREAD

**Issue by Mandrake158** [hoarder-app/hoarder#363]
It would be very convenient if we could add rules like
Twitter/pixiv = art list

So every new link goes straight to that list and not need manual input on each one

**Comment by Mandrake158** [comment]
> So basically what https://github.com/hoarder-app/hoarder/issues/11 and https://github.com/hoarder-app/hoarder/issues/65 are about, or is your idea different?

Ahh yes, didn't see the #11
And about the #65, that feature is around tags, what I mean is about URLs but I guess it can be the same thing tbh, just a way to auto add to lists instead of manually sorting each time we add

**Comment by kamtschatka** [comment]
I am closing this issue as duplicate, as there is already an idea that will solve this. Please have a look at this comment: https://github.com/hoarder-app/hoarder/issues/65#issuecomment-2142707271
With those searches, you would be able simply save a smart list, which has a filter that would always match the bookmarks you want.

If you have any concerns about this, please post in the other issue, so we can keep the discussion together.
