### ISSUE TITLE
Improve tagging behavior

### ISSUE THREAD

**Issue by kamtschatka** [hoarder-app/hoarder#368]
I just added a bunch of links and moved them to a list. After that I noticed a few things:
* Moving multiple bookmarks to a list is an absolute pain. We really should add that to the bulk edit mechanism
* Editing tags has a few issues:
  * List of tags is not scrollable --> doesn't show all tags
  * Deleting all tags 1 by 1 is painful. In any other application if you press backspace, you can delete tags from the end of the tag list
  * I could have used a clear tags button, but that might have been too special to implement
  * What would also be nice would be to see all the tags assigned to the bookmarks in the current list, similar to what we have in the "tags" section(including merging). I would have been able to merge tags here as well (All bookmarks were of a similar topic, but i somehow ended up with 224 different tags for 14 different bookmarks)

**Comment by MohamedBassem** [comment]
Sent a quick commit to support adding to lists in bulk actions.

Regarding editing tags. Which list of tag are not scrollable? For me, both the one in `Manage Lists` and the one in `Bookmark Preview` are scrollable. As for the backspace, that makes sense and will probably remove the need for a "clear all tags".

**Comment by kamtschatka** [comment]
if you press the "..." menu and then "Edit Tags". Turns out the list is actually scrollable, when it gets too long, but there is just no scroll bar, so it cuts off the top of the tags.

**Comment by MohamedBassem** [comment]
So how do you suggest we improve this scroll behavior?

**Comment by kamtschatka** [comment]
I think we just have to make sure a scrollbar is shown, so it is obvious that it is a longer list.
