### ISSUE TITLE
Possible to set List via API?

### ISSUE THREAD

**Issue by crosbyh** [hoarder-app/hoarder#371]
Hello, first I want to say thanks for creating this app!

Is it possible to set the list of an item at the time it's added, via the API?

Context is, I am using Node-Red to consume some RSS feeds of my Reddit saved items into Hoarder, and I would like to automatically move these items into a specific list upon import.

Thanks again!

**Comment by kamtschatka** [comment]
is it not working? Should already be implemented with https://github.com/hoarder-app/hoarder/pull/211

**Comment by crosbyh** [comment]
This is likely me being dense, as it does appear you have the functionality. I am trying to call it via a CURL request. I have the following code in Node-Red, which works correctly for just sending a bookmark to my Hoarder instance:

```
const apiKey = 'api_key';

// Assuming the URL is passed to this function node's topic
const url = msg.topic;

// Define the request options
msg.method = 'POST';
msg.url = 'https://hoarder.example.net/api/trpc/bookmarks.createBookmark';
msg.headers = {
    'Authorization': `Bearer ${apiKey}`,
    'Content-Type': 'application/json'
};

// Set the request body
msg.payload = {
    json: {
        type: 'link',
        url: url,

    }

return msg;

```

Based on the issue you linked, I've tried adding the list-id parameter to the JSON payload a couple of different ways, both as `list-id` and `listid`, and by sending the plain text name of my list "Reddit" as well as the `listid` that appears in the body of the request when I inspect it from my browser when manually adding to the list, which looks something like `sroxe11ufh1brw8ygs9zbocd`, but nothing seems to work.

Am I missing something obvious?

**Comment by kamtschatka** [comment]
If you look at the cli, there is no call that allows creating a bookmark AND assigning it to a list in 1 go.
There is an API call to create the Bookmark and there is an API call to add it to a list. 
The CLI simply makes it easier for the user to do it with 1 command.

If you have a look at the API calls the WebUI makes, when you add a bookmark to a list, you can see how it is done. 
The API call is to "lists.addToList" and takes the parameters of the listId and the bookmarkId. If you don't have the id of the list, there is also "lists.list" to get a list of all lists, with the name and the id, as well as the parentId if it exists.

**Comment by kamtschatka** [comment]
closing, as it should be possible already
