### ISSUE TITLE
[Feature Request] - Sorting for all the bookmarks (not lists)

### ISSUE THREAD

**Issue by raviwarrier** [hoarder-app/hoarder#377]
It would be nice if we could sort the bookmarks in alphabetical and chronological order (in both directions).

**Comment by kamtschatka** [comment]
I am closing this issue as duplicate, as there is already an idea that will solve this. Please have a look at this comment: https://github.com/hoarder-app/hoarder/issues/65#issuecomment-2142707271
With those searches you would also be able to specify your search direction and get pagination working correctly.

If you have any concerns about this, please post in the other issue, so we can keep the discussion together.
