### ISSUE TITLE
[Feature Request] Bare minimum list view

### ISSUE THREAD

**Issue by raviwarrier** [hoarder-app/hoarder#379]
While the thumbnail and descriptions are good, sometimes, you just want to quickly scroll through the list for any number of reasons. A bare minimum view like just the title of the bookmark, with domain name and date added would be nice.

Example:

How to make Baileys Irish Cream [epicurious.com] [23rd Dec 2023]

**Comment by MohamedBassem** [comment]
hmmm, I'm wondering. How do you expect to see the "notes" and "images" in such ultra compact view?

**Comment by raviwarrier** [comment]
The whole point of the compact view is to just see the important details. A compact view helps in two scenarios - 1) when you have thousands of bookmarks and want to quickly traverse them, and 2) you know exactly what you are searching or looking for and don't want to be bogged down by images and notes. Very much like the browser manager of any Chromium browser.

I really hope you do implement this. Just as an option for people who want a clean list view.

**Comment by MohamedBassem** [comment]
@raviwarrier this is already implemented and will be available in the next release :)

**Comment by MohamedBassem** [comment]
Here's a screenshot for how it's going to look like:

<img width="986" alt="Screenshot 2024-09-15 at 3 54 49 PM" src="https://github.com/user-attachments/assets/71ea6632-6781-4c62-9f52-9549208ae138">

**Comment by Sylvio82** [comment]
When will this list view be available in the Android app?

**Comment by MohamedBassem** [comment]
@Sylvio82 oh, didn't know that this was something people are asking for on the mobile apps :) The mobile apps currently don't have customizable layouts. If that's something you're interested in, please open a new issue for it :)
