### ISSUE TITLE
[Feature Request] Bulk Edit in Tags or Lists or Search Results view

### ISSUE THREAD

**Issue by raviwarrier** [hoarder-app/hoarder#380]
It would be nice to bulk edit bookmarks in tag, list or search results view as well.

One might want to do any number of operations - change tags of all the bookmarks, delete them, add them to a list, add a new tag, etc., on the collective.

**Comment by kamtschatka** [comment]
So this issue is about adding new bulk edit features and not about adding bulk edit, right?
Because you can already use bulk edit on lists or search results view. What exactly would you want to bulk edit in the tags view?

**Comment by MohamedBassem** [comment]
@raviwarrier Yeah, feature is already implemented in https://github.com/hoarder-app/hoarder/commit/ddc7e5dbfc31b3e5b189c61883e1cc737fefd2ee and https://github.com/hoarder-app/hoarder/commit/67729c131c92a2fab6d1422db34aa000c348af07 and will be available in the next release.
