### ISSUE TITLE
[Bug] Network Request Failed

### ISSUE THREAD

**Issue by marco-studer-srf** [hoarder-app/hoarder#381]
I cannot log in using the mobile app. URL is correct.

Could it be that you cannot handle passwords with ridiculous length and number of special characters?

![Screenshot_20240909_094304_Hoarder App](https://github.com/user-attachments/assets/763d1a14-5abf-46fd-b70b-605d0d5f5a0a)

**Comment by MohamedBassem** [comment]
No this is unlikely to be a password issue. This is usually the server address being unreachable from the phone or incorrectly setup (e.g invalid certs). 
Can you tell us if you're using http/https, is Hoarder behind a reverse proxy? Any special setup there?

**Comment by hubono** [comment]
Hi
I'm having the same issue. I installed hoarder on oracle free tier. All went ok. 
I installed the app on Android and it's working good. 
Now I installed on iphone, made a new user thought the web browser on the iphone, inputted the same details on the app and i get network request failed. I tried on the wifi and 5g, both fail.

**Comment by MohamedBassem** [comment]
I'll release a hoarder mobile update soon that hopefully can help us debug those network connection issues and show exactly the kind of errors that are being reported.

**Comment by MohamedBassem** [comment]
I've sent (https://github.com/hoarder-app/hoarder/commit/3452e47c94a55a525620c244f57edb9482989d1c) to add a new "Test connection" page to debug server connection issue. I hope this help figure out why the app is not working for you. I've submitted this to apple/google for review, should hopefully be available for download by Monday.

**Comment by marco-studer-srf** [comment]
> Running connection test ...
Using address: https://xxx
Network connection failed: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

Okay, it seems to be the certificate. However, I added the certificates to the root certificates of the phone. Accessing Hoarder via browser on the phone is working.

**Comment by chrishoage** [comment]
I am experiencing this issue using http - I get the same error 

> Network connection failed: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

Except that I'm using `http` specifically, and the debug output indicates this. 

Is the app trying to upgrade to an https connection? 

If so - then I'm hitting the same self signed cert error - however I do not wish to add this cert to the root certificates of my phone. 

Can there be an option to allow self signed certs?

**Comment by marco-studer-srf** [comment]
@MohamedBassem In one of my own projects, I happened to face the same issue. Adding the following network security config to the application makes it accept user-added CAs. It also allows cleartext traffic (http), since self-hosters will usually go one of these two ways.

In `res/xml/network_security_config.xml`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
            <certificates src="user" /> <!-- this is the part that makes it work -->
        </trust-anchors>
    </base-config>
</network-security-config>
```

And in your manifest, add:

```xml
android:networkSecurityConfig="@xml/network_security_config"
android:usesCleartextTraffic="true"
```

**Comment by cevatkerim** [comment]
this is also an issue when using cloudflare proxy connections.

**Comment by MohamedBassem** [comment]
I'm really sorry this took that long... Thanks for the fix!

**Comment by Raizel-thebloodstorm** [comment]
Bro where to add what ...please explain a little more

**Comment by MohamedBassem** [comment]
@Raizel-thebloodstorm this is going to be fixed in the next mobile app release. You won't be able to fix it yourself.

**Comment by Ciucci666** [comment]
I had the same problem, i solved it just by adding the `https://` and then it worked

**Comment by jnskender** [comment]
> I had the same problem, i solved it just by adding the `https://` and then it worked

Also fixed my issue.

**Comment by ClausMunch** [comment]
> I had the same problem, i solved it just by adding the `https://` and then it worked

Came here for the cake. This helped! :)

**Comment by l3s2d** [comment]
I'm still seeing this issue on mobile app version 1.6.7 with a self-signed certificate.

**Comment by MohamedBassem** [comment]
I have submitted the release to apple yesterday with the fix. Hopefully it'll be out in a couple of days.

**Comment by aia832003** [comment]
Thanks for the update @MohamedBassem is the apk available for those that would like manually install before the Play Store?

**Comment by MohamedBassem** [comment]
The update is live on the play store. Please give it a try and let me know how it goes

**Comment by l3s2d** [comment]
Working for me now, thank you!

**Comment by aia832003** [comment]
GM @MohamedBassem even after the latest update, I'm getting network request failed on my reverse proxy setup via android app. Was working previously and can reach it on my same device via browser. Also seems to work on my iOS devices just fine. Any suggestions?

"Network connection failed: Failed to connect to"

**Comment by pixitha** [comment]
Just dropping a note for folks who are still having issues, even after installing your local roots, you need to go into the cert store settings and actually enable full trust for apps to properly trust the self signed root:

The option "Settings -> General -> About -> Certificate Trust Settings -> ENABLE FULL TRUST"

This layout for settings should be valid for anything iOS 18.0+ versions.

**Comment by thallada** [comment]
> GM [@MohamedBassem](https://github.com/MohamedBassem) even after the latest update, I'm getting network request failed on my reverse proxy setup via android app. Was working previously and can reach it on my same device via browser. Also seems to work on my iOS devices just fine. Any suggestions?
> 
> "Network connection failed: Failed to connect to"

I'm also getting the same. I have a self hosted instance I can access and log into my Android phone's browser over https. But the app is unable to connect:

```
Running connection test ...

Using address: https://redacted.net

Network connection failed: Failed to connect to redacted.net/72...redacted...:443
```

I'm using version 1.7.0. 

I was previously able to log in. In fact my app was logged in when I opened it for the first time in months but I got an infinite loading spinner until I cleared the app storage in settings.

My self hosted server uses a let's encrypt certificate, *not* a self-signed one.

**Comment by TylerSchmidtke** [comment]
For anyone else that comes along having issues with self-hosting and the iOS app, check the validity period of your certificate. Apple currently has a 398-day limit on the validity period for a leaf certificate. If your certificate is issued with a longer one, you'll need to recreate it with a shorter validity period.

https://support.apple.com/en-us/102028
