### ISSUE TITLE
long delay when selecting tags in UI

### ISSUE THREAD

**Issue by cirrusflyer** [hoarder-app/hoarder#382]
I have nearly 4000 bookmarks, so a lot of tags.  When I select the "Tags" on the left UI menu, it takes around 14 seconds to display the list.  Hoarder is running on a server with a  Celeron N5105, 16 GB RAM, and SSD storage.

**Comment by kamtschatka** [comment]
This is most likely not related to the database query/your server, but rather on the UI showing all those tags. 
How many tags do you have? Should you not have less tags than bookmarks, to keep everything grouped together?

**Comment by cirrusflyer** [comment]
I have too many tags to count.  Is there a way to get a count?

**Comment by cirrusflyer** [comment]
Looks like over 6000 tags based on a copy and paste to another file and counting the rows.

**Comment by kamtschatka** [comment]
yeah, i was able to reproduce the issue, with 4000 tags that I added directly in the datbase and rendering took about 5 seconds for me. 
I optimized the code and got it to below 2 seconds. Maybe someone else with more knowledge of React has better ideas, but at least it improved quite a bit already.

**Comment by cirrusflyer** [comment]
That's a big improvement! Will that be pushed to Docker soon?

**Comment by kamtschatka** [comment]
Depends on: 
* When it gets merged. I am a contributor, the maintainer needs to review and merge it
* Which docker container you are using. If you are using stable, then it usually takes more than a month to release new versions, so you'll have to wait. If you are using the latest docker container, it would be made available pretty fast after the merge, but you'd be using a development version of hoarder, which potentially has more bugs.
