### ISSUE TITLE
[feature request] rss feed agregator

### ISSUE THREAD

**Issue by 4383** [hoarder-app/hoarder#383]
Hey there,

That would be awesome if hoarder allow us to subscribe to rss feeds. I'm currently using freshrss, but I'd really appreciate to centralize all my news/bookmarks into a single place.

Please let me know if this is something feasible.

**Comment by kamtschatka** [comment]
Is this the same as this? https://github.com/hoarder-app/hoarder/issues/202

**Comment by 4383** [comment]
Hm... I already seen this issue but without digging too much I think that's not exactly the same use case.

My use case is:
1. I want to be able to subscribe to rss feeds in hoarder;
2. Once a feed seems interesting for me I want the ability to turn it into a new hoarder bookmark

I'd really appreciate to have the ability to track all my news things into one single place. 

Let me know if you want more details

**Comment by huyz** [comment]
So you want Hoarder to become part-Feedly?

**Comment by 4383** [comment]
yeah

**Comment by 4383** [comment]
Would be awesome

**Comment by MohamedBassem** [comment]
Thanks @4383 for the feature request. To be honest, it's unlikely that we'd implement browsing rss feeds in Hoarder. I understand the convenience of having everything in the same place, but it's kinda out of the scope for Hoarder. The one that might actually happen is the one mentioned in #202 which is to automatically ingest RSS feeds into hoarder.
Closing this for now. Sorry.

**Comment by 4383** [comment]
No problem, thanks for your time, much appreciated.
