### ISSUE TITLE
[Feature Request] Ability to change main image and some other ideas

### ISSUE THREAD

**Issue by phampyk** [hoarder-app/hoarder#397]
First of all, I have to start by saying big THANK YOU for creating hoarder, I use it daily and I'm over the moon with it, honestly. I'm migrating my 14+ years collection of bookmarks and snippets into hoarder and I'm enjoying it so much.

I've been using it for over two months and I've got some ideas that I would love you to consider, even tho I think some of them are already requested I think:
- Ability to change the main picture is my biggest one, I do save a lot of crochet patterns, craft and graphic design tutorials and as much as hoarder is pretty good at indexing things, sometimes it does choose banners, ads or random web interface images for the main image, so I would like to be able to change the image for the main one on the post, just as a better way to see what the bookmark is about.
- Being able to choose which pages you can store fully offline, I tried to set it as soon as it was available (I'm referring to  `CRAWLER_FULL_PAGE_ARCHIVE=true`) thinking it would let me choose which links to store, but it does crawl everything. I don't want to store everything I save, but maybe some key tutorials and fixes, some links I would like to keep for reference later on without having to worry about being offline.
- Customizable list icons. This one is a silly one, but one I really like from using raindrop, you can upload your own icon. I would love to be able to have my minecraft list with a minecraft icon, the linux list with a tux icon... I find it a bit frustrating not having emojis for the theme of my lists. Is not a massive deal, I would still use hoarder 100% but giving the idea in case it's something doable or something worth implementing. 
- Ability to edit the link. Sometimes I just paste the link from the phone and it has trackers, or other references on the link, sometimes with the years they change the url format and I like to add the new url to the same content... it would be nice to be able to edit the link.
- When I used Linkwarden, it has an option to crawl your bookmark to archive.org, so apart from your cached content and screenshot you could have an archive.org crawled copy too. I thought that was clever and handy, but not sure if that's something you would be happy to have or implement.

Thank you so much for the app and your time, I would be more than happy to help if you ever think of translating the app to other languages, I can translate to Spanish.

**Comment by MohamedBassem** [comment]
@phampyk thanks for your nice words and I'm really glad you're enjoying Hoarder so far! Regarding the ideas that you shared:

1. Custom banners are tracked in #106. This however doesn't let you pick from the other images of the article and instead let you upload a custom one. Is that good enough?
2. Choosing what to archive locally is a good suggestion. Can you file a separate issue for it for better tracking?
3. I can see the frustration of not finding the matching icon :D Let's create a separate issue for it. It's probably not hard, but to be honest, given the limited capacity, I can't promise we'll be able to get to it soon.
4. Editing the url is tracked in #375
5. The archive.org thing I'm not so sure about. Why is that better than the local archive that hoarder saves?

Thanks a lot for the ideas and feedback, let's open separate issues for the ideas that you suggested for better tracking. As for the translation, I really appreciate the offer, it's something that has been on my todo list for a while but still didn't get a chance to do :)

**Comment by phampyk** [comment]
Thank you so much for replying and considering my ideas, I'll open the separare issues right now.

Replying to your questions:
  1. Yes, uploading the banner myself would be even better, as I would have even more control over what the main image is. I'm so excited this is already planned!!
  3. No problem whatsoever, I'll gladly wait as long as it has to be! It's a nice addition but not a main concern.
  5. I was thinking this one could be beneficial in cases like people not wanting to do the full page crawler, for limit of space, also the fact that it's publicly available for everyone as it's on archive.org. But it's totally up to you.
 
Again, thank you for all!

**Comment by MohamedBassem** [comment]
Landed https://github.com/hoarder-app/hoarder/commit/a770e55520245b7afc2b7a30aa6127eebcb6ea0d which will allow you to change the banner of the links. Will be available in the next release. Thanks for filing separate issues for the other requests. Closing this issue for now.

**Comment by phampyk** [comment]
> Landed [a770e55](https://github.com/hoarder-app/hoarder/commit/a770e55520245b7afc2b7a30aa6127eebcb6ea0d) which will allow you to change the banner of the links. Will be available in the next release. Thanks for filing separate issues for the other requests. Closing this issue for now.

I just saw it, I'm about to spend a bit making my bookmarks pretty. THANK YOU so much!
