### ISSUE TITLE
OpenID Connect

### ISSUE THREAD

**Issue by Daniel15** [hoarder-app/hoarder#400]
It would be great if Hoarder supported OpenID Connect, so that users could log in with their existing auth service - a self-hosted one like Authentik, Keycloak, Authelia, or a public provider like Google Workspace / G Suite, Microsoft 365, etc.

I don't like needing a separate username and password for every self-hosted service :smiley:

**Comment by MohamedBassem** [comment]
Hey, this had already landed and will be available in the next release :)

**Comment by Daniel15** [comment]
Thanks! I just noticed that too (#92). I didn't find that because I was searching for "OpenID Connect" but it was actually written as "OIDC" there.

Do you have a dev build of the Docker container so that I can use this feature before the next release?

**Comment by MohamedBassem** [comment]
yes, if you use the "latest" docker tag instead of "release" you'll find it there. Just noticr that we still haven't landed the changes to the browser extension and mobile apps that would allow you to use them when sso is enabled just yet.

**Comment by MohamedBassem** [comment]
docs for setting them up are here: https://docs.hoarder.app/next/configuration#authentication--signup

**Comment by Daniel15** [comment]
Thanks. I'll wait until the browser extension and apps are updated. 

Thanks for the link to the docs. I'm happy to see projects that use Docusaurus! I worked on testing the initial release :smile:

**Comment by MohamedBassem** [comment]
Oh, that means we're colleagues :)
