### ISSUE TITLE
Feature: Retain title, date, and tags from Netscape bookmarks import

### ISSUE THREAD

**Issue by Daniel15** [hoarder-app/hoarder#401]
A Netscape-compatible bookmarks file (at least the one produced by Pinboard) has the timestamp of the bookmark, tags, title, and a description:

```html
<!DOCTYPE NETSCAPE-Bookmark-file-1>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<TITLE>Pinboard Bookmarks</TITLE>
<H1>Bookmarks</H1>
<DL><p>

<DT><A HREF="https://www.reddit.com/r/SanMateo/comments/1djs27o/touchless_car_washes_near_san_mateo/" ADD_DATE="1726850472" PRIVATE="0" TOREAD="0" TAGS="porsche,car">Touchless car washes near San Mateo : SanMateo</A>
<DD>&lt;blockquote&gt;Hello, has anyone been able to find any touchless car washes in or near San Mateo? I haven’t had success finding any so far but not sure if...&lt;/blockquote&gt;

<DT><A HREF="https://www.technologyreview.com/2024/09/11/1103838/why-a-ruling-against-the-internet-archive-threatens-the-future-of-americas-libraries/" ADD_DATE="1726850459" PRIVATE="0" TOREAD="0" TAGS="archive,copyright">Why a ruling against the Internet Archive threatens the future of America’s libraries | MIT Technology Review</A>
....
```

It would be nice for Hoarder to at least retain the date and tags, but ideally also the title and description.

I'd like to import several thousand bookmarks, but I don't want it to show them all as having a date of today :smile:

**Comment by MohamedBassem** [comment]
> but I don't want it to show them all as having a date of today

That's actually a very good point. I think I can get it done soon.

The description will be tricky though because Hoarder will re-crawl those links and will end up overriding their description with what it's going to extract itself.
