### ISSUE TITLE
[Feature Request] Allow to disable default password log in after SSO is configured

### ISSUE THREAD

**Issue by MFYDev** [hoarder-app/hoarder#406]
Reference: https://github.com/hoarder-app/hoarder/issues/92

Thank you for the wonderful project! And finally I can use SSO to secure my instance.

However after the SSO is set, can we add an env variable like DISABLE_DEFAULT_LOGIN or DISABLE_LOGIN_FORM to disable the default email and password log in form? Only through this way the SSO can properly protect the Hoarder itself.

Thank you so much for your effort again!

**Comment by IamTaoChen** [comment]
Maybe the `DISABLE_SIGNUPS` should be split for the local account and OIDC. OIDC account should be created automatically and the local account should be disable for signup.
