### ISSUE TITLE
Blank Icon when added to IOS homepage

### ISSUE THREAD

**Issue by tagdara** [hoarder-app/hoarder#41]
When “Add to home page” is selected on IOS from mobile safari, the icon is solid black.

**Comment by MohamedBassem** [comment]
Yeah, I've seen this problem before with the PWA. I'll fix it. Btw, I think you'll get a better experience using the ios app. The iOS app is pending apple's approval, but if you're interested, you can use the beta version via test flight (https://testflight.apple.com/join/QifpNxAT). The main advantage for the iOS app over the PWA is the ability to share to `Hoarder` from any other app.

**Comment by tagdara** [comment]
Thanks, I've got both but the app doesn't have Dark mode and it's still kinda early/janky in a couple ways.  

I'm sure once you have a little more dev time into it, I can drop the PWA!

**Comment by MohamedBassem** [comment]
I don't think this is an issue anymore at least in iOS 18
