### ISSUE TITLE
[Feature Request] - some sort of inbox concept, maybe a list?

### ISSUE THREAD

**Issue by ianepreston** [hoarder-app/hoarder#415]
Occasionally after adding links to hoarder I want to review the ones I added, maybe add some notes, custom tags, or put them in a particular list. Right now I can't figure out how to separate out the bookmarks I've done this with from the others. The only approach I can currently find that somewhat mirrors that is to archive everything once I process it, which means I can't make use of any other lists. Either having an inbox list or having some view of all bookmarks that aren't in any lists would allow me to track which bookmarks I've manually processed. Open to a number of approaches on this so I'm keeping the request somewhat vague but happy to clarify what I'm looking for or discuss more detailed approaches.

Thanks, loving this app!

**Comment by MohamedBassem** [comment]
I think as you mentioned, the "archive" functionality is meant to be exactly that. Your homepage is your inbox, and the "archive" button means remove from homepage (but they'll keep appearing everywhere else, lists, searches, etc).

> which means I can't make use of any other lists

Not sure what you mean with this.

**Comment by MohamedBassem** [comment]
I'm also open to the idea of having a "default" list that all newly added bookmarks get added to, but I want to only go that route if the current homepage based approach is not good enough for the usecase.

**Comment by ianepreston** [comment]
I think they key thing I missed was that lists aren't exclusive. I was still thinking of them as directories, hence my confusion about having things in archive and other lists. There might still be some value in being able to discover articles that aren't in any lists, but for my use case I think treating archive as you suggested will work. Thanks again.
