### ISSUE TITLE
[Feature Request] Add Puppeteer proxyServer Support

### ISSUE THREAD

**Issue by tdharris** [hoarder-app/hoarder#420]
Add support for a configuring a `PROXY_SERVER` address in the Hoarder configuration, which would pass through to [Puppeteer's proxyServer](https://pptr.dev/api/puppeteer.browsercontextoptions/#proxyserver) configuration. Puppetteer would then automatically use this for all requests. This would add a lot of support for other external proxy services with a seemingly straightforward approach. There is also a `proxyBypassList` if it's needed to ensure certain requests remain local.

**Comment by kamtschatka** [comment]
Do you already have an external proxy service in mind / what is your exact usecase?

**Comment by tdharris** [comment]
Sending requests through a [Privoxy](https://www.privoxy.org/) web proxy service using a container that has the VPN configured and opens up the Privoxy service for other clients to go through. For example, there are many popular containers that leverage Privoxy as the exposed web proxy service and then supporting various VPN clients within the image (OpenVPN, WireGuard, PIA, ProtonVPN, etc) that all traffic gets routed through:
- [binhex/arch-privoxyvpn](https://github.com/binhex/arch-privoxyvpn), [binhex/arch-delugevpn](https://github.com/binhex/arch-delugevpn)
- [walterl/proton-privoxy](https://github.com/walterl/proton-privoxy)
- [qmcgaw/gluetun](https://github.com/qdm12/gluetun)
- [haugene/docker-transmission-openvpn](https://github.com/haugene/docker-transmission-openvpn)

**Comment by kamtschatka** [comment]
tbh, i don't think this feature is needed. 
Hoarder is connecting to a chrome docker container already, so in the docker compose file, if you add `--proxy-server=<ip>:<port>` that should already work?
From what I saw so far, you can only pass the proxy server to puppetteer when launching the browser, but since chrome is already running in that container, that should not be necessary?
Works fine for me at least

**Comment by tdharris** [comment]
Sweet! That will be perfect, thanks for that info, I'll give that a try. 💯

**Comment by tdharris** [comment]
✔️ Verified this works for me perfectly. Thanks for such an awesome app!

**Comment by MohamedBassem** [comment]
@tareefdev I think at the docs of `--proxy-server`, it seems that the schema needs to be followed by an equal.

> --proxy-server=<scheme>=<uri>[:<port>][;...] | <uri>[:<port>] | "direct://"

So I think you need:

```
--proxy-server='http=groups-RESIDENTIAL:******@proxy.apify.com:8000'
```

**Comment by tareefdev** [comment]
Now Hoarder is able to fetch links again, however, it does not utilize the proxy, testing with https://4.myip.is/ returns my server's ip :) thank you Mohamed for your great efforts on developing this project and your help here

**Comment by MohamedBassem** [comment]
@tareefdev I think I miss understood the docs of proxy server. The way we configured it means that it'll use the proxy only for http requests. If you remove the 'http=' completely it shod use the proxy for everything.

**Comment by tareefdev** [comment]
Hoarder is not able to fetch links again!
````
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --proxy-server="groups-RESIDENTIAL:****@proxy.apify.com:8000"
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
````
Adding `https=` as a schema, Hoarder works, but does not use the proxy

**Comment by MohamedBassem** [comment]
Quick googling suggests that proxy servers flag doesn't support auth (https://superuser.com/questions/902620/google-chrome-proxy-settings-with-username-and-password).
You might have to run this proxy-login-automator that's mentioned, point the proxy server to it, and let it proxy to your final destination.
