### ISSUE TITLE
Update meilisearch to 1.10+

### ISSUE THREAD

**Issue by deurk** [hoarder-app/hoarder#426]
Any chance of supporting meilisearch 1.10+ rather than the current 1.6?

I have updated to 1.9.1 without issue but after that it does not seem to work.

Thanks :)

**Comment by MohamedBassem** [comment]
According to their docs (https://www.meilisearch.com/docs/learn/update_and_migration/updating) their updates are not backward compatible. So it's not safe to ask people to upgrade and we're stuck with the 1.6 version we currently have.

Any particular reason why you want to upgrade it?

**Comment by MohamedBassem** [comment]
Not much we can do about this for now unfortunately. Closing the issue.
