### ISSUE TITLE
Feature Request: REST API

### ISSUE THREAD

**Issue by georgzoeller** [hoarder-app/hoarder#43]
This is really great software, I love the clear motivation and where it fits into the ecosystem.

I'd be lovely to get an API for some common actions, primarily retrieving content, searching, and addition from outside the API.

Use case:
- Allow interaction from external channels such as slack/discord bots
- Ability to integrate with AI orchestration tooling (like mine - https://github.com/omnitool-ai/omnitool)

**Comment by MohamedBassem** [comment]
REST API is definitely planned, and you can even get an API key from the settings. It's just blocked on one of our dependencies getting updated for TRPC v11 :) If it takes too long, I'll just fork it and add the necessary modifications myself.

> Side note: You can actually right now interact with the TRPC based API today (by inspecting the requests that chrome does). It's actually not that hard. But I don't guarantee any backward compatibility there. So I'd recommend waiting for the REST API instead.

**Comment by georgzoeller** [comment]
Amazing, thank you!

**Comment by webserviceXXL** [comment]
A simple REST API with API key authentication would be saving items so much easier 😍

**Comment by zezretro** [comment]
Bump for being very enthusiastic to have a REST API

**Comment by georgzoeller** [comment]
Claude can synthesize an API client from the trpc definitions in like 20s,
so I just went that route

**Comment by MohamedBassem** [comment]
Just done implementing the API. It'll be available in the next release. The docs are here: https://docs.hoarder.app/api
