### ISSUE TITLE
[Feature Request] Add Openrouter support

### ISSUE THREAD

**Issue by prabhjotsbhatia-ca** [hoarder-app/hoarder#434]
It'd be great if Openrouter could be added as an alternative API provider. 

OpenRouter provides access to a huge number of AI models (including OpenAI GPT), which would provide a choice to have cheaper, more varied AI models for the inference, as well as more features (like image tagging, perhaps). 

Also, it uses a common API format across all providers, which is almost the same API format as the OpenAI API format, so not many changes are going to be needed on that front. (You could even consider switching at some point)

**Comment by kamtschatka** [comment]
I have tried that yesterday because of https://github.com/hoarder-app/hoarder/issues/424 and it worked just fine already, by simply adding it as the OpenAI endpoint. 
Have you tried it and ran into issues?

**Comment by kamtschatka** [comment]
Please try it out and let me know if something other than the issue in the link above does not work. For me it already works fine and the inference issue should be fixed with the PR that is already open

**Comment by peyloride** [comment]
I've just tried this and it works. I've just set those:
```
OPENAI_API_KEY=your-key
OPENAI_BASE_URL=https://openrouter.ai/api/v1/
```

Haven't tried to the change models because I think 4o-mini is just great for this but I think it'll work without a problem too.
