### ISSUE TITLE
[Android] Bad Add-Button position

### ISSUE THREAD

**Issue by JojiiOfficial** [hoarder-app/hoarder#439]
The "Add" button on android is always on top of the last entry in the list and moves down with ever further entry created.
This makes adding new entries and deleting the last entry a bit challenging.
<br>
<img src="https://github.com/user-attachments/assets/7fe3c6d5-d1ed-487b-b615-b73e48c42f7d" width="300">

**Comment by MohamedBassem** [comment]
Oh, this looks bad indeed. Didn't notice it during development because I have bookmarks that fill the screen. Thanks for reporting it, will send a fix.

**Comment by MohamedBassem** [comment]
Decided to drop the button altogether.
