### ISSUE TITLE
[CLI] Ability to get all bookmark IDs of a list

### ISSUE THREAD

**Issue by JojiiOfficial** [hoarder-app/hoarder#442]
It would be great to have the ability to list all bookmarks from a specific list using the Hoarder CLI tool.
This functionality would greatly improve the tool's usability and help with bookmark management.

**Comment by MohamedBassem** [comment]
Yeah, that makes sense. If you're interested in sending a PR, it shouldn't be too hard. You can add a "get" command here and use tRPC to fetch the list content (https://github.com/hoarder-app/hoarder/blob/main/apps/cli/src/commands/lists.ts#L94).
