### ISSUE TITLE
[Feature Request] Regenerate tags based on archived pages?

### ISSUE THREAD

**Issue by wbste** [hoarder-app/hoarder#443]
I have a number of bookmarks I imported and I used a pretty small model which resulted in pretty poor tagging, I'd like to rerun it based on a larger model using existing content so I don't have to recrawl pages. I don't think that's possible today, is there the ability to add it under the admin section?

On a slightly related, it'd be cool to auto generate summaries of the bookmarks as well to make potential future vector search easier 😅

**Comment by MohamedBassem** [comment]
Thanks for the feature request, I pushed https://github.com/hoarder-app/hoarder/commit/5281531d6f4aab4605c407d5167dd8e44f237f0d which should allow you to regenerate AI tags for all bookmarks. It's going to be available in the next release, or you can use the nightly build if you want it faster.
