### ISSUE TITLE
Latest: 2024-09-30 - Lists when Editing not Saving.

### ISSUE THREAD

**Issue by jabaran** [hoarder-app/hoarder#447]
I was unable to save an `Edit` made on a list in the `latest` [[image](https://github.com/hoarder-app/hoarder/pkgs/container/hoarder/281250757)]; however, when image was changed to `release` [[v0.17.1](https://github.com/hoarder-app/hoarder/pkgs/container/hoarder/280396811)] the save action worked. It doesn't appear any event is firing, from what I could tell.

This was on Windows 11, using Chrome 129.0.6668.60. I didn't try another browser.

I looked in the console for an error but didn't see anything. Let me know if there is more information I can provide that would help.

**Comment by MohamedBassem** [comment]
can you explain a bit what you mean by and edit? Changing the name/parent etc?

**Comment by MohamedBassem** [comment]
Ok, I can repro. Seems to happen only when opening the editing dialog from the sidebar. Will look into it
