### ISSUE TITLE
[Feature request] Record the webpage's URL when adding text notes from a webpage.

### ISSUE THREAD

**Issue by CRISPserver** [hoarder-app/hoarder#448]
Currently, when selecting a piece of text and right-clicking "Add to Hoarder," Hoarder saves the text as a note but does not record the link to the text. I hope that notes added this way can also record the webpage's URL and use the webpage's title as the note's title (without scraping all the webpage content). This can bring several benefits:

1. It allows for recording the source of the added text, aiding in future tracking.
2. It serves as an alternative to webpage highlighting, as I add important content from the webpage to Hoarder.
3. Sometimes the added text is too long, making it difficult to understand the content intuitively on the Hoarder homepage. Adding the URL and webpage title helps quickly grasp the content.
4. Some internal websites cannot have their content scraped from the external network, and adding the URL may fail. I need to record the URL by adding text.
![image](https://github.com/user-attachments/assets/277ee977-ee6d-4fac-89fe-7287c7f30d16)

**Comment by CRISPserver** [comment]
I hope to add a link to the left of "Ocr 01" in the second note (just like the first one). If possible, use the title from the first note's content as the title for the second note as well.

**Comment by MohamedBassem** [comment]
That's a very reasonable feature request.

**Comment by MohamedBassem** [comment]
This is now implemented! Will be available in the next release :+1:
