### ISSUE TITLE
[Feature Request] Keyboard Shortcut & Search Improvements

### ISSUE THREAD

**Issue by lucius346346** [hoarder-app/hoarder#449]
I would like to suggest a few enhancements to improve the usability of the search functionality:

**Keyboard Shortcut for Search Bar:**
A dedicated keyboard shortcut to focus the search bar (e.g., pressing / or Ctrl + F) would make it easier to quickly start searching.

**Search as You Type:**
It would be even better if typing the first letter of a search prompt automatically focuses on the search bar and begins searching without the need for manual focusing.

**Escape Key to Clear Search:**
When the search bar is focused and contains text, pressing the Esc key should clear the search entry instead of just losing focus. This would improve the UX by allowing users to quickly reset the search.

**Comment by kamtschatka** [comment]
My take on this:

**Searching**
* Searching with "/": really uncomfortable if you are not using a certain keyboard layout (for english layout it works great, german layout, which I am using, requires "SHIFT+7"). The github search does not work for me with shortcuts for that reason (it also works with "/")
* Searching with CTRL+F: this is overriding the default browser behavior and REALLY annoying to me, as you can no longer search inside the page. 
* Docusaurus has the shortcut set to CTRL+K, I think that might be an option that works for everyone.

**Searching as you type**
not a big fan, especially if there is a shortcut for it

**Escape key to clear search**
Sounds good to me

**Comment by MyWay** [comment]
It would be cool if, like linkding, the browser extension could provide a custom **search engine** so that when you type in the address bar the key you set, eg. 'ho' or whatever, it will automatically go on Hoarder and search there for the specified keywords.

**Comment by lucius346346** [comment]
> It would be cool if, like linkding, the browser extension could provide a custom **search engine** so that when you type in the address bar the key you set, eg. 'ho' or whatever, it will automatically go on Hoarder and search there for the specified keywords.

Isn't this really easy to do in most browser? You can add custom engine by yourself.

**Comment by Inventhrice** [comment]
+1, I missed this issue while making my own (#545)

As I mentioned in that, we could maybe provide it as a setting per user?

**Comment by kamtschatka** [comment]
@Inventhrice : the keyboard shortcut on windows would actually be "CTRL+E" and not "windows + e", so there won't be an explorer window that opens. However, on Chrome this will also focus the searchbar currently.

I have created a PR to fix that and added CTRL+K and Escape handling to the searchbar
