### ISSUE TITLE
Feature request: improve tagging by providing existing tags to LLM tags-extraction prompt 

### ISSUE THREAD

**Issue by alexkutsan** [hoarder-app/hoarder#457]
The current prompt for extracting tags from a link (see [here](https://github.com/hoarder-app/hoarder/blob/main/packages/shared/prompts.ts#L14)) works well but tends to generate slightly different tags for links with similar content.

To improve the quality of the tags and reduce redundancy, I suggest modifying the prompt to include any existing tags. It should instruct the model to reuse these tags if they match the content. This would help maintain consistency and avoid generating too many unique tags for a single link

<img width="1325" alt="изображение" src="https://github.com/user-attachments/assets/82b45de5-1a04-4c40-b414-7b497a96b688">

**Comment by kamtschatka** [comment]
already exists in https://github.com/hoarder-app/hoarder/issues/111
I have also opened a PR yesterday that will allow you to do just that with the new custom prompts feature
