### ISSUE TITLE
Make the controls for bulk editing sticky at the top of the page

### ISSUE THREAD

**Issue by kamtschatka** [hoarder-app/hoarder#459]
As mentioned in https://www.youtube.com/watch?v=dklvlJ4YDtM:
The bulk edit controls are at the top of the page, so if you want to bulk edit bookmarks at the bottom of the page, you'll have to scroll up and down a bunch of times. 
If the controls were sticky, this would be much more user friendly.

**Comment by argash** [comment]
+1 for this feature!

**Comment by kamtschatka** [comment]
has been addressed recently and the whole searchbar + bulk edit options are now always on top
