### ISSUE TITLE
[Bug] [Browser Extension] List of Lists rides to high when long

### ISSUE THREAD

**Issue by argash** [hoarder-app/hoarder#475]
![VJ5FCIRpvY](https://github.com/user-attachments/assets/55d3c9c2-93b8-4e94-a546-4a8f5db364fc)
Hopefully my screen shot shows what I am talking about. Basically after creating a few lists, now when I try to hoard something the list scrolls up out of view. There does not seem to be a way to force it to show me everything. Scrolling up does not help.

**Comment by MohamedBassem** [comment]
Thanks for the report, will tackle this as part of: #431
