### ISSUE TITLE
[Feature Request] Log failed login attempts for fail2ban implementation 

### ISSUE THREAD

**Issue by timmish** [hoarder-app/hoarder#477]
Hi there,
thanks for the great project, started using it a few days ago and already loving it.

I'm not using any SSO provider, but exposing behind a firewall with geo-ip blocking and a fail2ban implementation. 
It would be great if Hoarder had a log-file accessible in the data folder in which failed login attempts are logged, including the ip of the attempt. 
This way I could easily implement fail2ban.

Thanks for looking into it!

**Comment by thiswillbeyourgithub** [comment]
Hi @timmish, would you mind sharing your fail2ban filters for karakeep?
