### ISSUE TITLE
No such table: tasks error when saving entry

### ISSUE THREAD

**Issue by starlord998** [hoarder-app/hoarder#479]
I am running the docker container on a synology NAS. I am able to get to the login page and create a user. I am getting a popup error "no such table: tasks" when I try to save an entry. Not sure where this is coming from.

**Comment by kamtschatka** [comment]
sounds like you have a problem with your filesystem. the tasks table should be part of the "queue.db" file, which gets generated in your data folder (which you attach to the docker container). Either you have not attached it, don't have permissions, or maybe you have attached different data folders to the web and worker container (if you are using the old  containers, where they were separated)

**Comment by kamtschatka** [comment]
closing as there was no response. We can reopen if there is a response
