### ISSUE TITLE
Feature Request: Admin Control Over User Registration Access

### ISSUE THREAD

**Issue by ljq29** [hoarder-app/hoarder#493]
#### Description
It would be useful to have an option that allows the admin to control whether user registration is open or closed. This would give admins more control over who can access the platform, enhancing security and managing user flow more effectively.

#### Benefits
- **Security**: Admins can prevent unauthorized or unwanted registrations by disabling open registration.
- **Control**: Admins will have more control over how and when new users can join the platform.
- **Flexibility**: The option to toggle open or closed registration would allow admins to manage the registration process according to their specific needs.

#### Proposed Solution
Add a toggle or setting in the admin panel that allows the admin to:
- Enable or disable user registration.
- Customize a message to display when registration is closed.
- Optionally, allow invite-only registration or other selective methods for managing new users.

#### Additional Context
This feature would improve the management of user accounts and enhance the overall security of the platform by giving admins greater flexibility in controlling who can register.

**Comment by kamtschatka** [comment]
Will be handled as part of https://github.com/hoarder-app/hoarder/issues/280.
Invite-only sign up is not on this list though, so if that is still wanted, please create a new issue
