### ISSUE TITLE
Request: Add Invite-Only Registration Option for Admins

### ISSUE THREAD

**Issue by ljq29** [hoarder-app/hoarder#495]
## Description

It would be useful to have an **invite-only registration option** in addition to open or closed registration controls. This would give admins more granular control over who can access the platform, further enhancing security and managing user flow more effectively.

### Benefits

- **Security**: Admins can prevent unauthorized or unwanted registrations by restricting new user sign-ups to invite-only.
- **Control**: Admins will have complete control over how and when new users join the platform, making it easier to maintain a secure and managed user base.
- **Flexibility**: The invite-only option adds an additional layer of flexibility for admins to manage new users according to specific requirements or events.

### Proposed Solution

In addition to open or closed registration controls, add an option for invite-only registration. This would allow admins to:

1. Enable or disable user registration.
2. Customize a message to display when registration is invite-only.
3. Manage invitation codes or links for new users to join the platform.
4. (Optional) Add a way to track or manage active invitations and their status.

### Additional Context

This feature would improve user account management by giving admins greater flexibility in deciding who can register. It would also increase the overall security of the platform by ensuring only authorized users can sign up. This option would be useful for platforms that want to control the onboarding process or limit access to specific users.

---

This suggestion stems from the feedback in #280, where invite-only registration was not included. If invite-only registration is still desired, it can be managed as a separate issue from #280.

**Comment by MohamedBassem** [comment]
Thanks for the detailed feature request. Invite only registration makes sense, but it's a lot of work without a lot of demand. I think the potentially simpler approach would be to allow admins to create users from the admin panel, and give that user the creds (they can change the password afterwards).
