### ISSUE TITLE
Issues related to self-signed certificates

### ISSUE THREAD

**Issue by anselor** [hoarder-app/hoarder#500]
I've run into a number of issues on my home LAN related to self-signed certificates. At a minimum these should be added to the documentation but, perhaps, may be desirable to have the defaults do something similar to this.

The node.js environment appears to have its own list of root CAs that is separate from the host environment it operates in.
To have node.js share the same list of root CAs as its host environment (on debian-based linux distros, at least), this environment variable needs to be added to the container:
```
NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
```

In my specific case where I have self-hosted a certificate authority with a self-signed root cert in my LAN, I've registered this cert to the docker host environment and it just needs to be mapped into the hoard container's environment with this:
```
    volumes:
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
```

Additionally, on the mobile app, it's unable to connect even when the root CA has been added to the phone's trusted store.

**Comment by anselor** [comment]
It appears this PR may address the last point: https://github.com/hoarder-app/hoarder/pull/416

**Comment by MohamedBassem** [comment]
I've just merged #416, sorry it took that long. It'll be available in the next mobile release.

**Comment by anselor** [comment]
@MohamedBassem I don't think this is resolved. The docker compose file still needs updates to pick up the host environment's certificate store.

**Comment by MohamedBassem** [comment]
@anselor Hoarder doesn't deal with certs and ssl at all. The hoarder server always responds with http and I don't think you can configure it to serve https. The recommendation is to put a reverse proxy in front of hoarder that does the ssl termination and proxies to hoarder in http.

**Comment by anselor** [comment]
@MohamedBassem 
The problem isn't it serving https. The problem is it refuses to connect to an authentication server with https because it doesn't use the system root certificate store. When running hoarder on a private LAN with a self-signed certificate, hoarder is unable to authenticate users.
