### ISSUE TITLE
Save PDF annotations.

### ISSUE THREAD

**Issue by nicktheone** [hoarder-app/hoarder#506]
Maybe I'm misunderstanding this feature but if I upload a PDF file it offers me to annotate and write on it but it's not sticking. The next time I reopen the PDF there are no edits. Am I doing something wrong?

**Comment by kamtschatka** [comment]
where are you annotating? in the pdf itself? 
Or do you mean you are adding a note to the pdf?

**Comment by kamtschatka** [comment]
Must be a browser thing/browser plugin then? Hoarder simply embeds the pdf in an iframe, we are not supporting this annotation thing, you can "only" add notes

**Comment by nicktheone** [comment]
I see. I suspected it was Firefox and not Hoarder offering this feature. Thank you for the explanation.

**Comment by thiswillbeyourgithub** [comment]
Btw hoarder is working on implementing highlights and I made a bounty so don't hesitate to help fund it!
https://github.com/hoarder-app/hoarder/issues/620
