### ISSUE TITLE
Firefox Bookmarks Backend Feature Request/Idea

### ISSUE THREAD

**Issue by phillippradoxyz** [hoarder-app/hoarder#514]
Not sure how difficult this would be to implement, but would it be possible in the future to just make our browser bookmarks the backend for Hoarder? What I mean is that Firefox (for example) already has a robust bookmarking system. It's just ugly and hard to navigate/organize visually. And Hoarder is beautiful and easy to navigate and organize. I would love to just sync my bookmarks via Firefox, and use something like Hoarder to manager and edit them. It seems like this solution would be a good alternative to self-hosting, and in my mind, sounds like a great idea.

**Comment by kamtschatka** [comment]
What do you mean with "a good alternative to self-hosting"?
You'd still have to self-host hoarder as a backend.
Theoretically it would be possible to create and modify bookmarks in firefox or forward them to hoarder, but we'd have to keep it in sync with a permanent connection to hoarder make it seemless and if the connection is lost, have it sync again.

**Comment by phillippradoxyz** [comment]
Well let me clarify, I have no idea if this is possible or even worth the effort given the payoff. But what I am suggesting would be just using the Hoarder apps and extensions to query existing bookmarks via something like your Firefox account by hooking into the API or something without using the Hoarder sync server. So instead of connecting to your instance of Hoarder, you just sign in to your Firefox account and pull in bookmarks from there. Then people could use Hoarder as a front end without needing to host anything, and they could just work with their existing bookmarks. The obvious downside to this is that your Hoarder settings, tags, and lists wouldn't sync to other devices without hosting a sync server since those won't sync with Firefox. Again, not sure if it's possible or worth it since I don't know the technical details about Hoarder, but it was just an idea I had.

**Comment by DeCodeTheWeb** [comment]
There are no bookmark extensions like this that I have found, and none that allow tag searching like hoarder
