### ISSUE TITLE
iOS app JSON parse error

### ISSUE THREAD

**Issue by katosdev** [hoarder-app/hoarder#542]
Hi gang! 👋🏻 

When I try to log into the Hoarder iOS app (iOS 18.1) I am getting an error of:
**JSON Parse error: Unexpected character: <**

Neither my email address nor my password contain this character.

**Comment by kamtschatka** [comment]
the endpoint you are reaching is not returning json, but some HTML. So you have an issue in your setup.

**Comment by katosdev** [comment]
> the endpoint you are reaching is not returning json, but some HTML. So you have an issue in your setup.

Very interesting, I've only just configured this and have it working on the web side - Will dig into that, any pointers of where are the usual suspects to check please ?

**Comment by kamtschatka** [comment]
so far it was mostly proxies/VPNs

**Comment by katosdev** [comment]
> so far it was mostly proxies/VPNs

Ahh that could be it actually, the site runs behind Cloudflare.
I’ll do some digging and see what’s what. Thanks!
