### ISSUE TITLE
Update meilisearch

### ISSUE THREAD

**Issue by wuast94** [hoarder-app/hoarder#543]
There is already an issue #426 but without any usefull information.

my main reason is security. running old containers (v1.6 is 9month old and v1.9 what i use is 3month old).
running old containers is always a bad advice becouse they also have all the security issues of the base image, all old dependencys and app. 

also recource usage, speed improvements etc are some things that are always nice to have.

**Comment by dtomlinson91** [comment]
The Meilisearch upgrade procedure (when running in a container) is a massive [pain in the arse](url) (and I say this as someone who uses it daily).

For a project like this upgrading it in-place is practically impossible. It is going to be far easier to have people re-create their Meilisearch index on the new version and re-index.

Does the reindex all bookmarks button in the admin interface do this?

**Comment by MohamedBassem** [comment]
> Does the reindex all bookmarks button in the admin interface do this?

That's exactly what it does yes.

**Comment by wuast94** [comment]
so clearing the meilisearch data, start with new version, and then reindex all bookmarks should work?

**Comment by dtomlinson91** [comment]
Yeah bring the whole stack down, backup & delete the `data.ms` directory (so the Meilisearch volume), bump the Meilisearch image tag and bring it back up and re-index.

**Comment by MohamedBassem** [comment]
@wuast94 as long as newer version of mellisearch work with their old clients (they are keeping client backward compatibility), this should work yes. Reindexing is extremely fast.

**Comment by wuast94** [comment]
then i will try it the next days and report back :)

**Comment by wuast94** [comment]
i can report it works without any issues, maybee we could update the version in the compose for new users?

**Comment by MohamedBassem** [comment]
@wuast94 thanks for reporting back! Sure we can update the compose version then.

**Comment by wuast94** [comment]
well then i will do a PR :)
