### ISSUE TITLE
[Bug] Unable to recover password

### ISSUE THREAD

**Issue by Inventhrice** [hoarder-app/hoarder#544]
## Issue

I have forgotten the password to my account, which was a bit silly. However, this is what made me realize that we do not have a way to recover a password authenticated account.

![image](https://github.com/user-attachments/assets/84f712cc-1f72-4187-a0a5-544131188065)

## Expected Outcome

There ideally should be a "Forgot Password" button, or maybe some other way to regain access to an account lost

## Potential Solutions

This is a bit of a tricky problem to solve i realize, because unless we implement some sort of email sending method, we cannot email out a link to reset the password (which I would think would be the best way to implement this).

Maybe we could have a default admin page with a stern reminder to a) backup your bookmarks and b) write down the password somewhere safe?

I'd love to hear thoughts on this! I do not require a solution, as I somehow had the foresight to backup my bookmarks while playing around with this, so I will just be spinning up a new instance.

**Comment by kamtschatka** [comment]
You can set the password again in the database: https://discord.com/channels/1223681308962721802/1288282511495008378
But overall, a reset password button the admin can use might be a good solution. If we ever get the possibility to send out emails, a password reset button might be an option

**Comment by Inventhrice** [comment]
Unfortunately, I do not have access to that channel. Having said that, just an idea, it may be worth transferring that knowledge from discord to the documentation! I'd be happy to help out with this task :)

**Comment by kamtschatka** [comment]
I have updated the docs to contain an FAQ section where you can find the instructions to reset a password. (I am not sure when the rollout happens, you can look at the PR in the meantime: https://github.com/hoarder-app/hoarder/pull/590/files)

**Comment by MohamedBassem** [comment]
@kamtschatka https://docs.hoarder.app/next/FAQ
