### ISSUE TITLE
Git Sync

### ISSUE THREAD

**Issue by haildriver** [hoarder-app/hoarder#548]
To create and sync bookmark with git provider, because self-host isn't fesiable for most user.
Example app: https://github.com/stride-tasks/stride

**Comment by kamtschatka** [comment]
Please explain further what you mean?
"self-host isn't feasible for most users": who determined that? How would you use this app then, if you do not host it yourself? Do you expect us to host it for everyone and you connect your own git provider?
A git provider can not crawl anything, it would just be possible to store files there, so what do you expect here?

I have no idea what kind of system you are imagining from the 2 lines you have provided.

**Comment by MohamedBassem** [comment]
@haildriver Unfortunately, I don't think this is something we'll ever implement. Hoarder relies significantly on having a backend (much more than just for storage).
