### ISSUE TITLE
Single linebreaks are lost when viewing textnote card

### ISSUE THREAD

**Issue by tainio** [hoarder-app/hoarder#549]
When creating a new note and adding line breaks, the formatting is not preserved when viewing the note. The entire text is displayed on a single line.

Steps to reproduce:
1. Create a new note.
2. Enter text with multiple lines.
3. Save the note.
4. View the note. The text is displayed on a single line.

Note that editing the saved note displays line breaks correctly.

Running v0.18.0 with docker
 
Expected behavior:
The note should be displayed with roughly the same formatting (considering limited space) as it was entered, including line breaks.

![image](https://github.com/user-attachments/assets/8f6640b1-ddc2-4e87-858e-6e412559bb3c)
![image](https://github.com/user-attachments/assets/077b4f61-3b07-43a4-bc23-a6a9b489d94c)
![image](https://github.com/user-attachments/assets/b9523c7c-8987-4a38-8dd4-5bbb409a5f21)

**Comment by kamtschatka** [comment]
indeed, that is quite inconsistent. I have created a PR to fix it.
