### ISSUE TITLE
Make Myself an Admin

### ISSUE THREAD

**Issue by digisavvy** [hoarder-app/hoarder#560]
My account doesn't have admin privileges so I can't initiate a search re-index
![Screenshot](https://s3-us-west-1.amazonaws.com/imgcaps/Hoarder_2024-10-17_10-03-53.jpg)

How can I modify my account to be an admin?

**Comment by MohamedBassem** [comment]
The account automatically becomes an admin account if it's the first created account. If you want to promote another account to be an admin you'll have to modify the database to do this (as of now).

Basically, run the following query against the sqlite database in the DATA_DIR:

```
update user set role='admin' where id='<USER_ID>'
```

If this doesn't make sense to you, you can join the discord server and we can give you a step by step guide on how to do it.

**Comment by digisavvy** [comment]
Perfect! That did it. =)
Thank you.

**Comment by kamtschatka** [comment]
changing roles is now possible in the UI by Admins on the "Admin Setting" page
