### ISSUE TITLE
[Feature Request] Filtering with Multiple Tags

### ISSUE THREAD

**Issue by Inventhrice** [hoarder-app/hoarder#563]
I don't think there's an previous issue made about this. I'm looking to see if we can have multiple tag filtering. Example, if I have three tags "Fiction", "Art", "Writing", I'd like to filter bookmarks with "Fiction" and "Art", etc. Thanks!

**Comment by kamtschatka** [comment]
I am closing this issue as duplicate, as there is already an idea that will solve this. Please have a look at this comment: https://github.com/hoarder-app/hoarder/issues/65#issuecomment-2142707271
With those searches, you would then be also able to filter by multiple tags.

If you have any concerns about this, please post in the other issue, so we can keep the discussion together.
