### ISSUE TITLE
Getting logged out all the time

### ISSUE THREAD

**Issue by wouldntyouknow** [hoarder-app/hoarder#564]
Hi!
Love the app but I am having an issue with it. After logging in successfully, I get logged out automatically after a minute or two (seemingly random). When I try to get back it, sometimes it fails a few times, sometimes it lets me in instantly. Running the app in Docker, locally.
Here is a log excerpt. This chunk comes up 6-7 times (same) in a row after getting kicked out.
```
s [TRPCError]: UNAUTHORIZED

    at /app/apps/web/.next/server/chunks/815.js:1:2403

    at a (/app/apps/web/.next/server/chunks/105.js:4:32966)

    at Object.next (/app/apps/web/.next/server/chunks/105.js:4:33078)

    at /app/apps/web/.next/server/chunks/815.js:1:2337

    at a (/app/apps/web/.next/server/chunks/105.js:4:32966)

    at p (/app/apps/web/.next/server/chunks/105.js:4:33305)

    at h (/app/apps/web/.next/server/chunks/105.js:7:4283)

    at /app/apps/web/.next/server/app/api/trpc/[trpc]/route.js:1:4249

    at Array.map (<anonymous>)

    at g (/app/apps/web/.next/server/app/api/trpc/[trpc]/route.js:1:4183) {

  code: 'UNAUTHORIZED',

  [cause]: undefined

}
```
What can I do here? THank you.

**Comment by MohamedBassem** [comment]
do you have something in front of hoarder? A reverse proxy with any special configuration for example?

**Comment by wouldntyouknow** [comment]
Hi! No, not yet at least. I am trying to access it on my internal docker IP (something like 'http://192.168.0.25:portnum')

**Comment by MohamedBassem** [comment]
that's weird. Is this happening with other browsers as well? Also are you using passwords or oauth?

**Comment by wouldntyouknow** [comment]
Also an addition I missed: In the same browser (Brave), the Hoarder extension is installed and active. Configured via username and password as well. It works, adds the resource properly to Hoarder.

**Comment by MohamedBassem** [comment]
The extension uses a different authentication mechanism (API key based). How did the testing go with chrome?

**Comment by wouldntyouknow** [comment]
Okay, so Chrome is still in, while Brave had me kicked. Clearing cookies and retest did not seemed to help - same issue for some reason... Strange. Anyways, I guess this means it does not have to do anything with Hoarder, the issue is on my end.
Thanks for such quick replies!

**Comment by MohamedBassem** [comment]
@wouldntyouknow to give you some leads. This behavior you're seeing means that brave for some reason is not sending/corrupting the the JWT in the cookie that hoarder sets. If the JWT is corrupt, hoarder fails to authenticate you and just logs you out.

**Comment by wouldntyouknow** [comment]
Thanks again! Whatever it is, it is local to this particular installation as it seems. Fired up a W10 VM that has the same brave version - it works there perfectly.

**Comment by MohamedBassem** [comment]
Could be some extensions you have or something. Closing this issue for now, as it seems resolved. Feel free to reopen if you have more questions.
