### ISSUE TITLE
unable to manual setup on my local

### ISSUE THREAD

**Issue by mrkirthi-24** [hoarder-app/hoarder#565]
getting **no such table: user** error while signing up on local. please help
<img width="729" alt="Screenshot 2024-10-18 at 12 29 25 PM" src="https://github.com/user-attachments/assets/36043f29-1b97-4113-b3fc-61a13eddb439">

**Comment by kamtschatka** [comment]
sounds like you might not have mounted the data directory correctly? that usually causes the database to be missing and resulting in this error (might be other cases as well, i have only seen this one so far)

**Comment by mrkirthi-24** [comment]
is this correct @kamtschatka ?

**Comment by kamtschatka** [comment]
are you setting up a development environment?

**Comment by mrkirthi-24** [comment]
i did run `pnpm run db:migrate`. you can see db.db file in the image.

**Comment by mrkirthi-24** [comment]
> see https://docs.hoarder.app/Development/setup, you have to run `pnpm run db:migrate`, to actually get the database set up

i followed the whole setup guide. but still getting the error

**Comment by kamtschatka** [comment]
but what about the other 2 projects that also need this .env variable?

**Comment by mrkirthi-24** [comment]
> but what about the other 2 projects that also need this .env variable?

i actually want to use web only. so are you saying that i also create an .env file in web folder

**Comment by kamtschatka** [comment]
yes, those are the first 3 steps in the instructions in the documentation. did you do that?

**Comment by ryands17** [comment]
The trick here is to use an absolute path and not a relative one for the `DATA_DIR` and if you're using the script to run locally, then load the env file beforehand using `dotenv-cli`
