### ISSUE TITLE
Import from Pocket: Pocket now mails you zipped CSV files

### ISSUE THREAD

**Issue by daniel-l** [hoarder-app/hoarder#570]
After being unable to export my pocket saves with their export tool (way more than the tool's limit of 5000 saves) I contacted the Pocket support. They then revamped the export tool: upon requesting an export they now mail you a zip file which contains csv files, each containing 10.000 pocket saves + the first row containing the column's titles.

Hoarder's import tool still expects Pocket's old html format; this needs to be updated.

The csv files are comma separated and formatted like this:

```
title,url,time_added,cursor,tags,status
Hoarder App,https://github.com/hoarder-app,1728576752,7187623980,,unread
"hoarder-app/hoarder: A self-hostable bookmark-everything app (links, notes and images) with AI-based automatic tagging and full text search",https://github.com/hoarder-app/hoarder,1728576752,7187623980,opensource|withÄumlaut|with space,unread
Some Website Title,"https://somewebsite.com/with,commas,in,the,url",1728576752,7187623980,,unread
```

Multiple tags are separated by the pipe symbol "|". Tags can contain german umlauts (e.g. äÄöÖüÜ) and spaces (see example above). If some part of the saved item (e.g. title, url) contains a comma, the whole part is enclosed in quotation marks (again, see examples above).

**Comment by jacobslusser** [comment]
I'll note that the Pocket website still says the export will be in HTML format, but the file you actually receive is a .csv in a .zip as described by @daniel-l. It took me a while to figure out that I wasn't doing something wrong -- it was Pocket that changed.

**Comment by daniel-l** [comment]
Thanks for the clarification. I wasn't quite sure whether there was a threshold of saved websites below which Pocket still generates the old HTML format or now always sends out zipped csv files vie e-mail. I guess it's latter. Here's a full quote of the mentioned support ticket which explains the new process:

> I’m happy to let you know that our developers have updated the export tool! You can now export your Pocket data without any size limitations here: https://getpocket.com/export
>  
> When you initiate the export, a zip archive will be sent to your Pocket email. If you’ve previously requested an export for your lists, please try again now.
>  
> During the export, you will be provided with a tracking ID. If you don’t receive the export after 30 days, please share this ID with us, and we'll be happy to assist you further.

**Comment by Austinzveare** [comment]
I just set up Hoarder with the intention of importing from Pocket and just found this issue. Is there a way to import the CSV Pocket sends?

**Comment by fingon** [comment]
Not officially. I ran a shell command to add links and then produced sql with Python which updates create time and archive flag. Tags I do not use much so I left them for later.

**Comment by MohamedBassem** [comment]
I can't seem to export an export with multiple tags, can someone show me how they export a bookmark with multiple tags? What's the delimiter used between the tags?

**Comment by daniel-l** [comment]
See the example in my initial post. The delimiter is the pipe symbol (""):
`tag1|tag with spaces|another tag`

**Comment by kavlito** [comment]
> I just set up Hoarder with the intention of importing from Pocket and just found this issue. Is there a way to import the CSV Pocket sends?

I found 2 references to convert the .csv to .html - I used the PowerShell code and it worked. Hope this helps...

Example PowerShell Code:

$csvData = Import-Csv -Path "C:\Path\To\Your\Pocket\CSV\File.csv"
$htmlTable = $csvData | ConvertTo-Html -AsTable
$htmlTable | Out-File -FilePath "C:\Path\To\Output\File.html"

Example Python Code:

import pandas as pd
df = pd.read_csv("C:/Path/To/Your/Pocket/CSV/File.csv")
html_table = df.to_html(table_id="my-table")
with open("C:/Path/To/Output/File.html", "w") as f:
    f.write(html_table)

https://www.google.com/search?q=convert+pocket+.csv+to+html
