### ISSUE TITLE
Mark Articles as Read/Viewed and Organize Them

### ISSUE THREAD

**Issue by jezlo** [hoarder-app/hoarder#579]
### Describe the feature you'd like

I would like to propose a feature that allows users to mark articles as read or viewed when they open them. This functionality would help users manage their reading list more effectively.

Proposed Features:

    Mark as Read/Viewed: When an article is opened, there should be an option to mark it as read or viewed.

    Reorganize Articles: Once marked, the article should either be sent to the end of the list or automatically moved to a separate section for read articles, allowing users to focus on unread items.

    Automatic List Creation: Additionally, it would be beneficial to have an automatic list that compiles all the read articles for easy reference. This list could be accessed from the main interface, providing a quick way to review previously read content.

### Describe the benefits this would bring to existing Hoarder users

Benefits:

    Improved user experience by allowing easier navigation through articles.
    Enhanced organization of content, making it simple to distinguish between read and unread items.
    Provides users with a sense of accomplishment as they can easily track what they have already read.

### Can the goal of this request already be achieved via other means?

I believe these features would significantly enhance the usability of Hoarder and help users manage their articles more efficiently. Thank you for considering this request!

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

**Comment by MohamedBassem** [comment]
Closing this for now. Feel free to open it again if you still have questions.
