### ISSUE TITLE
Question: Logging security related events

### ISSUE THREAD

**Issue by thedom4302** [hoarder-app/hoarder#582]
Great Project firstly!
I cannot seem to find if login events are logged anywhere? I could not see any environment variables related to logging and when I simulate failed logins I cannot see it in my docker console log events. Where are these being sent to?

**Comment by MohamedBassem** [comment]
Hi, this was implemented last week (https://github.com/hoarder-app/hoarder/commit/0debc6b415baa466245901fb52c009d09ef3ba15) and will be coming in the next release.
