### ISSUE TITLE
Hoarder Melisearch Usage

### ISSUE THREAD

**Issue by acelinkio** [hoarder-app/hoarder#588]
Hey!  Trying to understand how Melisearch is used by Hoarder.  Let's say I just deleted the Melisearch instance and started fresh, what would happen with Hoarder?

I say this because Melisearch is still pretty new technology and  I am a lazy homelab administrator.  Do I need to worry about taking regular backups of Melisearch?  Hoping that I can just rely upon the application take care of repopulating Melisearch.  Otherwise I would need to have data volume/Melisearch backups on the same schedule. (edit this project does not use Postgres)

Thanks!

**Comment by MohamedBassem** [comment]
@acelinkio you don't need to backup meillisearch if you don't want. If its data is lost, you can run a full re index from the admin panel which would be extremely fast.

**Comment by MohamedBassem** [comment]
it won't happen automatically, but you can manually trigger the reindex.

**Comment by acelinkio** [comment]
One follow up question to that.  Is there any plans to move the rest of the state from the filesystem into a datastore (postgres/s3/etc)?

**Comment by MohamedBassem** [comment]
@acelinkio it's unlikely. If anything I'm trying to reduce the dependencies of Hoarder. So it's unlikely I'll be adding anymore dependencies anytime soon.
