### ISSUE TITLE
Import from omnivore

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [hoarder-app/hoarder#602]
### Describe the feature you'd like

Hi,

With omnivore [getting sold to ElevenLabs](https://blog.omnivore.app/p/omnivore-is-joining-elevenlabs) and adding the ability to [fully export our data](https://docs.omnivore.app/using/exporting.html) I was wondering wether it was possible to import their export format into hoarder?

### Describe the benefits this would bring to existing Hoarder users

Create a ton of new hoarder users :)

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

**Comment by kamtschatka** [comment]
There is already an old issue about omnivore: https://github.com/hoarder-app/hoarder/issues/455
It has a script on how to export the data into a netscape format 
Alternatively the omnivore documentation already describes how to create a csv file out of it, which you can use to get the URLs into hoarder as well.

**Comment by MohamedBassem** [comment]
@kamtschatka Omnivore only recently added an export mechanism. I think we can now support them natively.

**Comment by kamtschatka** [comment]
yes, that is what I said. They document how you can transform it into a CSV: https://docs.omnivore.app/using/exporting.html#converting-exported-data-to-csv
You can already just open the csv with excel and copy out all the links

Uploading the whole zip file doesn't sound like it makes sense?

**Comment by thiswillbeyourgithub** [comment]
Oh indeed if hoarder does not support highlights then yeah I guess there's nothing more to import.

**Comment by MohamedBassem** [comment]
This is coming in the next release (hopefully this week). You'll need to merge all the json files into one and then upload it to hoarder:

Run: 
```
$ jq -r '.[]' *.json | jq -s > omnivore.json
```
Then upload `omnivore.json` to hoarder.

**Comment by thiswillbeyourgithub** [comment]
FYI for anyone stumnling into this: I also did a script to import the highlights from omnivore directly into karakeep: https://github.com/thiswillbeyourgithub/karakeep_python_api/tree/main/community_scripts/omnivore2karakeep-highlights

It uses a probabilistic matching and ignores pdf but worked well for me.
