### ISSUE TITLE
iOS App Connection Test Failed

### ISSUE THREAD

**Issue by LightningMarshal** [hoarder-app/hoarder#616]
### Describe the Bug

When attempting to use the iOS app and pointing it at the hoarder server address I get an error message that reads "Network connection failed: The file "health" couldn't be opened because there is no such file. I am able to hit the app using a web browser with the same address, however I am not to able to log in via the app and receive the network request failed error. I am wondering if anyone else is able to reproduce this or if this is user error on my part at some point in the process?

I have a docker container running on a Raspberry Pi and I am able to view and use the Hoarder from multiple devices, but not through the iOS app.

### Steps to Reproduce

1. Take a deep breath
2. Verify that the docker container on and running.
3. Verry that you are to use and view Hoarder using an alternative method such as a web browser.
4.  Open the Hoarder iOS app
5. Enter in your server address where hoarder can be accessed
6. Press the next button
7. Enter in hoarder credentials: username and password 
8. Press sign in
9. Stare at "Network request failed" text in confusion

### Expected Behaviour

Pressing the sign in button would allow the user access to their saved material and the ability to save new material and the core functionality of the app would be enabled.

### Device Details

iOS 18.0.1

### Exact Hoarder Version

v0.18.0

**Comment by MohamedBassem** [comment]
@LightningMarshal In the first screen where you enter your server address there's a connection debugging tool. Can you give it a try and share its output?

**Comment by LightningMarshal** [comment]
@MohamedBassem Thank you for taking a look at this. 

Here is the output from the diagnostic tool:
![image](https://github.com/user-attachments/assets/2b7e66f6-efb9-488a-805b-78fc86fc1323)

**Comment by MohamedBassem** [comment]
can you try adding 'http://' at the beginning of the server address?

**Comment by LightningMarshal** [comment]
That was the issue. I had tried https, but was confused when just the IP worked in other browsers.

![image](https://github.com/user-attachments/assets/d051aadc-5b8e-41df-abee-185b9bad7e94)

I might fork a branch to create  simple documentation to help out other idiots like me. Thank you for your help. Closes #616

**Comment by cevatkerim** [comment]
this is still an issue. I use it with cloudflare and iOS app fails even though I ahve no issue connecting via web over cellular connection.

**Comment by MohamedBassem** [comment]
@cevatkerim If by cloudflare you mean with "Cloudflare access", allowlisting the `/api/.*` endpoints are the only option right now.

**Comment by Cycledudebcn** [comment]
It did the trick for me too. 
This also happens on Android. 
I had to define the /api 'hole' in a new hoarder app specific policy (Cloudflare ZT).  
Not super comfortable leaving this open slot, I'd prefer to use a Service Token or something, but at the very least I could narrow it a bit by country access filer.)

**Comment by Franktek** [comment]
@Cycledudebcn Can you expand on how you set up the /api app specific policy in Cloudflare?
