### ISSUE TITLE
Filter by tag when viewing a list

### ISSUE THREAD

**Issue by dtomlinson91** [hoarder-app/hoarder#617]
### Describe the feature you'd like

When I view a list, I should be able to filter by tags.

### Describe the benefits this would bring to existing Hoarder users

Hoarder is amazing and it's completely tansformed my knowledge base in Trilium by having everything archived and sorted away in its own list.

For me, the biggest drawback is lack of filtering/searching. I know this is somewhat covered in #454 where a simple search query language is planned, but it would be nice if this applied to list views as well as the homepage.

Currently I cannot search for all #python tags in my Trilium list for example - it just returns all links across all lists.

### Can the goal of this request already be achieved via other means?

Not currently

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

**Comment by kamtschatka** [comment]
please comment that on https://github.com/hoarder-app/hoarder/issues/65
we have the plan to allow filtering using search queries and also using a UI.
