### ISSUE TITLE
Feature Request: Add highlighting support for text

### ISSUE THREAD

**Issue by flintstones-fred** [hoarder-app/hoarder#620]
### Describe the feature you'd like

Users are able to highlight certain snippets of text. 

### Describe the benefits this would bring to existing Hoarder users

Many articles are saved because they have some relevant/useful information. But more times than not, you want to recollect specific important piece of information from that article (e.g. key takeaways, a specific issue that author had faced from a list of issues). Highlight support in hoarder will really be a very useful feature for users to retrieve the most useful information very quickly. Especially useful for long-form text articles. Many Read it later apps make their living on this. Hoarder has the ability to take it to the next stage as it also captions text. 

### Can the goal of this request already be achieved via other means?

No. The closest feature is the powerful search that hoarder already has implemented. However, searching something still requires you to remember the correct words. I think the two features (search and highlight) will best work hand in hand. Let's say the search gets you to a couple of useful articles you have saved. And then the user has highlighted the most relevant text to them that they are now able to quickly retrieve. 

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

**Comment by npnpatidar** [comment]
Would love this.

**Comment by thiswillbeyourgithub** [comment]
I desperately need to hoard AND highlight too.

I'm thinking a good part of the code could be directly taken from the omnivore self hosted fork no?

**Comment by flintstones-fred** [comment]
Omnivore has(had) the best UI for the reader view in my opinion. If it's easy to implement something like this for the hoarder cachee content, that would be super awesome

**Comment by MohamedBassem** [comment]
I'm working on this right now :)

<img width="538" alt="Screenshot 2024-12-26 at 10 06 44 PM" src="https://github.com/user-attachments/assets/85b0399a-747b-4c27-8353-56cb8d6335bf" />

though, to be honest, it's not very easy, so let's see how far I'll be able to go.

**Comment by flintstones-fred** [comment]
Oh, that's great! Is there some things that I can help with? I am not a programmer but happy to take something simpler on so that you can focus on the harder part

**Comment by thiswillbeyourgithub** [comment]
Oh wow, this is so nice to hear!

If I may, when a while back I was developing something for Omnivore's API, I ran into a weird issue that if I recall correctly were due to them storing only a processed string of the text content. Like you can choose to either store the raw mathjax formulas inline a text string or first turn them into Unicode symbols. But if the highlight text you store is not strictly a part of the parsing because you interpreted the mathjax to unicode then other devs might run into issues writing API tools. So yeah if you can store the unprocessed highlight content that'll be swell :))) That would help me avoid having to code [weird parsers](https://github.com/thiswillbeyourgithub/LogseqMarkdownParser/blob/167cf3c24215dd87a7e5590bb08d46ab5d3b3456/examples/omnivore_to_anki.py#L684)

Do you accept bounties? I'm ready to give you $50 if you pull off an omnivore highight importer in the future :)

**Comment by MohamedBassem** [comment]
https://github.com/user-attachments/assets/b3f89f32-fc6e-442b-a71c-839d9de05089

I think I might have something that works!

**Comment by MohamedBassem** [comment]
Ok folks, I've just merged support for this in https://github.com/hoarder-app/hoarder/commit/86d74e3f32dd5bccc8df195b55391e206df9a1c4 and it'll be coming as an experimental feature in the next release (expect bugs, it wasn't a trivial feature). Give it 15mins and it'll be available in the nightly build. I'd appreciate if you folks can give it a try and report bugs before the next release (in around a week from now)!

Notable missing features:
1. A highlights page that shows all highlights across bookmarks.
2. API support for manipulating highlights.
3. Attaching notes to the highlights.

1 & 2 will be implemented before the release. 3 will depend on how important it is for you.

**Comment by thiswillbeyourgithub** [comment]
What a beast! What a feat!

What are the supported filetypes for annotation? Omnivore allowed annotating both webpages and pdfs.

And can we expect an omnivore highlight import? I offered $50 for it :)

Thanks a lot!

**Comment by MohamedBassem** [comment]
@thiswillbeyourgithub Currently, I've only added support for annotating webpages. To do pdfs, I'll need to change the pdf viewer used by hoarder which is a bigger change.

As for the omnivore highlights import, I probably won't have the bandwidth for it. So let's keep the bounty for someone else to claim it :)

**Comment by thiswillbeyourgithub** [comment]
Alright thank you so much!

**Comment by MohamedBassem** [comment]
Both the API and the "All highlights" page are now available in the nightly build.

**Comment by flintstones-fred** [comment]
@MohamedBassem I was able to spin up a new container to try out the latest build. I am not using the API for hoarder as much, so, I will stick to my feedback on the web version (I am assuming the cached content will eventually come to the mobile app). 
1. Highlighting works great! Very intuitive. Consider adding a few more colors. 
2. I like how the highlights show up on the right pane of the article you are viewing. 
3. A couple of requests on the highlights page: First, is it possible to show highlights grouped by the article in which they were made? This will help visualize all highlights from an article no matter the time order in which they were created. 
4. A second potential request (this might be useful once thousands of articles have been hoarded) is to implement a search just within the highlights. 

Thank you again for your work on this.

**Comment by MohamedBassem** [comment]
Thanks for giving it a try and for the feedback @flintstones-fred! Glad that the feature works well!
1\. Regarding the few colors, I'm curious, what functionality do you usually get out of those colors. Because so far, I implemented them to be just a visual thing and nothing more.
3\. Regarding grouping by article, I feel like this will make the ordering (and pagination very weird). How do you sort the groupped highlights in that case?
4\. Yeah, search is something that I anticipate will be needed, but will probably ship the feature without it as a start. It seems that omnivore survived for long without it?

**Comment by flintstones-fred** [comment]
1. Colors: mainly just preference. More is better. Honestly, 99% of the time, I just use yellow and red. 

3. I was thinking that the structure of the highlights page could look something like below - 
- Article 1
	-- Highlight 1
	-- Highlight 2
- Article 2
	-- Highlight 1
	-- Highlight 2
	-- Highlight 3
And so on!

4. That's fair.

**Comment by thiswillbeyourgithub** [comment]
By the way, I know this is still experimental, but I think it would be worth adding it to the repository description

**Comment by flintstones-fred** [comment]
@MohamedBassem This works as intended on desktop browsers. However, I can't get the highlighting functionality in Safari on iPadOS. The normal context menu shows up if I select any text from the cached text.

**Comment by bonnebulle** [comment]
I frenetically use https://addons.mozilla.org/en-US/firefox/addon/histre/ ( histre.com )
highlights multicolors make my day a better rainbow
Maybe some more colors for a next update ?
Yellow Orange Green Blue Purple Red ?
<img width="198" height="34" alt="Image" src="https://github.com/user-attachments/assets/14f3bdae-a282-4ea2-9fa3-f0e65b67dec6" />

Saving my highlights is a gem.
Thanks a lot
