### ISSUE TITLE
As an admin I would like to manually add new users when `DISABLE_SIGNUPS=true`

### ISSUE THREAD

**Issue by maxiride** [hoarder-app/hoarder#631]
### Describe the feature you'd like

With an internet exposed instance I don't want new users to singup so `DISABLE_SIGNUPS=true` allows me to enforce this behaviour.

However, I would like to give access to the instance to family and friends. As of now the stack needs to be rebooted with `DISABLE_SIGNUPS=false`, register the new users and then reboot again to disable new singups.

### Describe the benefits this would bring to existing Hoarder users

Simplify new users registration allowing the admin to manually enter their infos, afterwards the user can change its password.

### Can the goal of this request already be achieved via other means?

Not that I know.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

**Comment by kamtschatka** [comment]
Already added with https://github.com/hoarder-app/hoarder/pull/567 and available in latest

**Comment by MohamedBassem** [comment]
This is coming in the next release this weekend. So should be here very soon.
