### ISSUE TITLE
Add customized cookie support

### ISSUE THREAD

**Issue by Gnosnay** [hoarder-app/hoarder#648]
### Describe the feature you'd like

Add customized cookie support to make it possible that get the page which only is allowed access from logged users.

### Describe the benefits this would bring to existing Hoarder users

more pages will be hoardered.

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

**Comment by Gnosnay** [comment]
https://pptr.dev/api/puppeteer.cookieparam

we may use this method to do so

**Comment by MohamedBassem** [comment]
I think we're more likely to do #172 instead.

**Comment by chenyucheng0503** [comment]
> I think we're more likely to do #172 instead.

Can REST API user also use #172 extension's method without opening Chrome?
