### ISSUE TITLE
Feature: Minimal install, no AI, no crawler. Hoarding only!

### ISSUE THREAD

**Issue by rowanfuchs** [hoarder-app/hoarder#650]
### Describe the feature you'd like

A minimal install of Hoarder without the fuss of features like AI or crawling. No need for fetching images or contents, I prefer a clean clutterless collection of notes/bookmarks with basic search.

### Describe the benefits this would bring to existing Hoarder users

The ability to run it on lower end devices or just run it as a simple hoarding solution

### Can the goal of this request already be achieved via other means?

not that I am aware of.

### Have you searched for an existing open/closed issue?

- [x] I have searched for existing issues and none cover my fundamental request

**Comment by kamtschatka** [comment]
just don't add a chrome container and do not configure AI?
If you do not add any URLs that should be fine. But then I am wondering why you are going for Hoarder and not something like Google Keep?

**Comment by MohamedBassem** [comment]
@kamtschatka this seems like something that we can support fairly easily. Basically if chrome url is not set, rely on the curl request only and just accept the fact that this won't render JS or take screenshots, etc. I actually don't mind the idea.

**Comment by rowanfuchs** [comment]
> just don't add a chrome container and do not configure AI? If you do not add any URLs that should be fine. But then I am wondering why you are going for Hoarder and not something like Google Keep?

Hoarder spams the log with this error when you install it without a headless chrome instance, and why Hoarder > Google Keep ofcourse, one reason: private and selfhosted.

```
2024-11-12T18:32:28.448Z error: [Crawler] Failed to connect to the browser instance, will retry in 5 secs
2024-11-12T18:32:33.449Z info: Launching a new browser instance
```
