### ISSUE TITLE
Serendipity Mode

### ISSUE THREAD

**Issue by Pasithea0** [hoarder-app/hoarder#655]
### Describe the feature you'd like

A page to review a random assortment of saved tiles that the user can choose to delete or keep

### Describe the benefits this would bring to existing Hoarder users

This is by far my favorite feature in Mymind and helps me remember to look at my previous bookmarks

### Can the goal of this request already be achieved via other means?

not that i am aware of

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

**Comment by MohamedBassem** [comment]
Planning to do this as part of #435
