### ISSUE TITLE
Add hooks for plugins to process/munge data

### ISSUE THREAD

**Issue by joestump** [hoarder-app/hoarder#658]
### Describe the feature you'd like

I would like to be able to do additional processing on things I hoard. Specifically:

* URL replacement (e.g. redirect to my local Invidious)
* Integrations with 3rd party apps (e.g. Reddit – but pull in the actual content directly rather than the Reddit post)

### Describe the benefits this would bring to existing Hoarder users

It would enable people to extend Hoarder for their specific use cases and it would unlock the ability for other applications to enable Hoarder integrations by releasing Hoarder plugins. 

### Can the goal of this request already be achieved via other means?

Yes, with scripts/services running outside of Hoarder and integrating with Hoarder's API. That just feels really heavy when all I want to do is replace `www.reddit.com` with `reddium.local`. 

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

**Comment by kamtschatka** [comment]
how is it different to https://github.com/hoarder-app/hoarder/issues/638 ?
