### ISSUE TITLE
Issues Crawling Youtube Shorts link because of cookies consent banner.

### ISSUE THREAD

**Issue by gercollo** [hoarder-app/hoarder#663]
### Describe the Bug

The crawler is unable to properly scrape YouTube Shorts links due to the cookie consent banner that appears for EU/EEA users. This banner blocks access to the content and prevents successful crawling of Shorts videos.

### Steps to Reproduce

- Cookie consent popup appears when accessing YouTube Shorts links
- Crawler cannot bypass or handle the consent banner
- Content behind the banner is inaccessible
- Crawling returns inaccurate metadata

### Expected Behaviour

Tag Generation based on the youtube title

### Screenshots or Additional Context

<img width="1311" alt="image" src="https://github.com/user-attachments/assets/1c52b98d-b857-4cf9-928c-17953f813300">

### Exact Hoarder Version

v19

**Comment by MohamedBassem** [comment]
Yeah, this is getting annoying. I'm planning to better tackle them hopefully sometime soon. Let's track this in #414 instead

**Comment by Eragos** [comment]
I have the same problem :-/
