### ISSUE TITLE
Import RSS Feeds via OPML File

### ISSUE THREAD

**Issue by rolltidehero** [hoarder-app/hoarder#669]
### Describe the feature you'd like

First off, I love this tool! Great Job. For those of us who have hundreds of RSS Feeds we follow, it would be great if we could import all of our feeds at once via OPML file since almost all RSS Feed Readers have an "Export Feeds to OPML" option. 

### Describe the benefits this would bring to existing Hoarder users

You currently have to add RSS feeds one at a time. Many users have hundreds of RSS feeds that we've followed over the years and since most RSS Readers offer the "Export Feeds to OPML" option, then that would allow us to import all of our feeds at the same time.

### Can the goal of this request already be achieved via other means?

No. The only option to add RSS feed is manually.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### Additional context

OPML would be ideal but any option to bulk import would be much appreciated.

**Comment by MohamedBassem** [comment]
thanks for the request. Let's track it in #657
