### ISSUE TITLE
Unlock easy Self hosting via a hoarder Nextcloud app release

### ISSUE THREAD

**Issue by menelic** [hoarder-app/hoarder#673]
### Describe the feature you'd like

Hoarder has great potential in the read it later space - please consider making it easier the people to self host the app by releaseing a nextcloud app version.

### Describe the benefits this would bring to existing Hoarder users

It would make hoarder easy to deplay, could more easily unlock multi-account and collaborative features for hoarder 

### Can the goal of this request already be achieved via other means?

No, because Nextcloud is widely used and the ease-of-instal for Nextcloud apps is unparalleled in the self hosting space. There could also be integrations with other nextclud app such as the news reader app (RSS reader) or the eBook app (turn articles to epub and send to ebook reader)

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

**Comment by kamtschatka** [comment]
From what I see, there is no way to deploy docker containers into nextcloud. So you'd still have to somehow deploy the docker containers with meilisearch and chrome somewhere, which would make the nextcloud app just a lot of extra work for absolutely no gain?
Additionally, from what I know, most people who are deploying nextcloud are also deploying it via docker, so what would be the advantage of deploying hoarder in nextcloud, when you can simply deploy it in docker?

**Comment by kamtschatka** [comment]
closing since it is neither feasible nor does it offer any advantage
