### ISSUE TITLE
REST API can only get 100 items

### ISSUE THREAD

**Issue by yinan-c** [hoarder-app/hoarder#675]
### Describe the feature you'd like

Max limit is 100 per page, however no pagination imlemented. It would be good to have a umilimited per page parameter or set the pagination.

### Describe the benefits this would bring to existing Hoarder users

API users will be able to get all links

### Can the goal of this request already be achieved via other means?

For now, hoarder cli can get all bookmarks but not REST API

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

**Comment by MohamedBassem** [comment]
The api does support pagination. The response contains a 'nextCursor' which if you send back as the 'cursor' search param you should get the next page. Does it not work?

**Comment by yinan-c** [comment]
The cursor works thanks!
