### ISSUE TITLE
Use existing tags for new AI tags

### ISSUE THREAD

**Issue by robvanvolt** [hoarder-app/hoarder#678]
### Describe the feature you'd like

Whenever new tags are generated, it could happen that a synonym tag is used for a new tag, instead of an already existing tag that would also fit.

### Describe the benefits this would bring to existing Hoarder users

The tags would be overall more streamlined.

### Can the goal of this request already be achieved via other means?

No.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### Additional context

One could simply add one rule to the prompt as follows that uses a set of all already existing tags:
`- if one of the following tags fits the [image/document], you can use that as well to reduce fragmentation: ["already existing tag 1", "already existing tag 2", ...]`

**Comment by kamtschatka** [comment]
See https://github.com/hoarder-app/hoarder/issues/111
