### ISSUE TITLE
Failed to connect to the browser instance

### ISSUE THREAD

**Issue by JOKER120YL** [hoarder-app/hoarder#682]
### Describe the Bug

**hoarder-web-1:**
2024/11/21 12:49:05  2024-11-21T04:49:05.442Z [31merror[39m: [Crawler] Failed to connect to the browser instance, will retry in 5 secs
2024/11/21 12:49:03  2024-11-21T04:49:03.895Z [32minfo[39m: [Crawler] Successfully resolved IP address, new address: http://172.18.0.4:9222/
2024/11/21 12:49:03  2024-11-21T04:49:03.893Z [32minfo[39m: [Crawler] Connecting to existing browser instance: http://chrome:9222
2024/11/21 12:48:58  2024-11-21T04:48:58.892Z [31merror[39m: [Crawler] Failed to connect to the browser instance, will retry in 5 secs
2024/11/21 12:48:57  2024-11-21T04:48:57.332Z [32minfo[39m: [Crawler] Successfully resolved IP address, new address: http://172.18.0.4:9222/
2024/11/21 12:48:57  2024-11-21T04:48:57.330Z [32minfo[39m: [Crawler] Connecting to existing browser instance: http://chrome:9222
2024/11/21 12:48:52  2024-11-21T04:48:52.329Z [31merror[39m: [Crawler] Failed to connect to the browser instance, will retry in 5 secs
2024/11/21 12:48:50  2024-11-21T04:48:50.683Z [32minfo[39m: [Crawler] Successfully resolved IP address, new address: http://172.18.0.4:9222/
2024/11/21 12:48:50  2024-11-21T04:48:50.681Z [32minfo[39m: [Crawler] Connecting to existing browser instance: http://chrome:9222
2024/11/21 12:48:45  2024-11-21T04:48:45.680Z [31merror[39m: [Crawler] Failed to connect to the browser instance, will retry in 5 secs
2024/11/21 12:48:43  2024-11-21T04:48:43.984Z [32minfo[39m: [Crawler] Successfully resolved IP address, new address: http://172.18.0.4:9222/
2024/11/21 12:48:43  2024-11-21T04:48:43.982Z [32minfo[39m: [Crawler] Connecting to existing browser instance: http://chrome:9222
2024/11/21 12:48:38  2024-11-21T04:48:38.980Z [31merror[39m: [Crawler] Failed to connect to the browser instance, will retry in 5 secs
**hoarder-chrome-1:**
2024/11/21 12:45:48  [1121/044548.690175:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping recommended platform policies because no policy file was found at: /etc/chromium/policies/recommended
2024/11/21 12:45:48  [1121/044548.690149:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping mandatory platform policies because no policy file was found at: /etc/chromium/policies/managed
2024/11/21 12:30:48  [1121/043048.590610:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping recommended platform policies because no policy file was found at: /etc/chromium/policies/recommended
2024/11/21 12:30:48  [1121/043048.586988:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping mandatory platform policies because no policy file was found at: /etc/chromium/policies/managed
2024/11/21 12:15:48  [1121/041548.476387:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping recommended platform policies because no policy file was found at: /etc/chromium/policies/recommended
2024/11/21 12:15:48  [1121/041548.476365:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping mandatory platform policies because no policy file was found at: /etc/chromium/policies/managed
2024/11/21 12:00:48  [1121/040048.376775:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping recommended platform policies because no policy file was found at: /etc/chromium/policies/recommended
2024/11/21 12:00:48  [1121/040048.376707:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping mandatory platform policies because no policy file was found at: /etc/chromium/policies/managed
2024/11/21 11:45:48  [1121/034548.276719:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping recommended platform policies because no policy file was found at: /etc/chromium/policies/recommended
2024/11/21 11:45:48  [1121/034548.276641:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping mandatory platform policies because no policy file was found at: /etc/chromium/policies/managed
2024/11/21 11:30:48  [1121/033048.308682:WARNING:dns_config_service_linux.cc(427)] Failed to read DnsConfig.
2024/11/21 11:30:48  [1121/033048.222909:WARNING:sandbox_linux.cc(418)] InitializeSandbox() called with multiple threads in process gpu-process.
2024/11/21 11:30:48  DevTools listening on ws://0.0.0.0:9222/devtools/browser/7c249364-7a6d-4c86-b71f-8000512c7784
2024/11/21 11:30:48  
2024/11/21 11:30:48  [1121/033048.179255:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
2024/11/21 11:30:48  [1121/033048.167776:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping recommended platform policies because no policy file was found at: /etc/chromium/policies/recommended
2024/11/21 11:30:48  [1121/033048.167748:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping mandatory platform policies because no policy file was found at: /etc/chromium/policies/managed
2024/11/21 11:30:48  [1121/033048.101007:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2024/11/21 11:30:48  [1121/033048.100940:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2024/11/21 11:30:48  [1121/033048.099027:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2024/11/21 11:30:48  [1121/033048.097807:WARNING:dns_config_service_linux.cc(427)] Failed to read DnsConfig.
**hoarder-meilisearch-1**
2024/11/21 12:40:53  [2m2024-11-21T04:40:53.532894Z[0m [32m INFO[0m [2mactix_server::server[0m[2m:[0m Actix runtime found; starting in Actix runtime
2024/11/21 12:40:53  [2m2024-11-21T04:40:53.532839Z[0m [32m INFO[0m [2mactix_server::builder[0m[2m:[0m starting 4 workers
2024/11/21 12:40:53  
2024/11/21 12:40:53  Discord:			https://discord.meilisearch.com
2024/11/21 12:40:53  Source code:			https://github.com/meilisearch/meilisearch
2024/11/21 12:40:53  Documentation:			https://www.meilisearch.com/docs
2024/11/21 12:40:53  Check out Meilisearch Cloud!	https://www.meilisearch.com/cloud?utm_campaign=oss&utm_source=engine&utm_medium=cli
2024/11/21 12:40:53  
2024/11/21 12:40:53  A master key has been set. Requests to Meilisearch won't be authorized unless you provide an authentication key.
2024/11/21 12:40:53  
2024/11/21 12:40:53  Anonymous telemetry:	"Disabled"
2024/11/21 12:40:53  Package version:	"1.11.1"
2024/11/21 12:40:53  Commit date:		"2024-11-06T11:35:26Z"

### Steps to Reproduce

docker compose：
version: "3.8"
services:
  web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - /tmp/zfsv3/nvme13/xxxx/data/Docker/Hoarder:/data
    ports:
      - 3100:3000
    env_file:
      - stack.env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      # OPENAI_API_KEY: ...
      DATA_DIR: /data
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - /tmp/zfsv3/nvme13/xxxx/data/Docker/Hoarder/meili_data:/meili_data

volumes:
  meilisearch:
  data:

env_file detail:
HOARDER_VERSION=release
NEXTAUTH_SECRET=2V8W1mZ3pLkXaY7fDqS4vRcNjO9gHuE1zB6xxxxxx
MEILI_MASTER_KEY=4hJ8uK3zX9bC2vL6fE5rQwG1sP0mT7yI9oN2axxxxxx
NEXTAUTH_URL=http://192.168.0.101:3100
OPENAI_BASE_URL=https://link/v1
OPENAI_API_KEY=sk-xxxxxxxxxxxxxxxxxxxxxx
INFERENCE_LANG=chinese
INFERENCE_TEXT_MODEL=gpt-3.5-turbo-0125

### Expected Behaviour

I configured hoarder using portainer. but it never seems to connect properly to chrome. i've tried searching for issues in github, but i still can't figure out why i'm like this. I plead for some help.

### Exact Hoarder Version

0.19.0

**Comment by MohamedBassem** [comment]
Let's track this in #674
