### ISSUE TITLE
Failed to connect to the browser instance, will retry in 5 secs

### ISSUE THREAD

**Issue by danndee1** [hoarder-app/hoarder#683]
### Describe the Bug

Failed to connect to the browser instance, will retry in 5 secs.

### Steps to Reproduce

I have an error with latest Hoarder version.The app can be used, but when I add a bookmark, it can't retrieve any image or description.

### Expected Behaviour

Are there any specific solutions to solve the problem of failing to connect to the browser instance?

### Device Details

QNAP

### Exact Hoarder Version

v.19.0

**Comment by MohamedBassem** [comment]
Let's track this in https://github.com/hoarder-app/hoarder/issues/674
