### ISSUE TITLE
Importing over 12,000 bookmarks from html file

### ISSUE THREAD

**Issue by nkj87lm9532** [hoarder-app/hoarder#693]
### Describe the Bug

Ok I am not a techie, just someone wanting to use this great software. I am trying to import an html file exported from Brave with over 12,000 bookmarks, with local ollama ai tagging. Hoarder seems to show it is importing all bookmarks (via the progress line), but when I go to Lists - Imported Bookmarks, and scroll all the way down, only about 1000 bookmarks seem to have been imported, and not all of those are tagged or even fetched from website, it seems. How to fix? Thank you. (If there is a better place to ask this question other than here on github, let me know.)

### Steps to Reproduce

1. import an html file exported from Brave with over 12,000 bookmarks
2. go to Lists - Imported Bookmarks, and scroll all the way down

### Expected Behaviour

I expect to see all 12,000+ bookmarks, fetched and ai tagged.

### Exact Hoarder Version

v0.19.0

**Comment by MohamedBassem** [comment]
@nkj87lm9532 Can you go the admin dashboard and see how many bookmarks got assigned to your user? And can you also screenshot the background jobs status?

**Comment by nkj87lm9532** [comment]
![background jobs](https://github.com/user-attachments/assets/430503c3-a84a-4210-9c47-9631b29f6183)

**Comment by MohamedBassem** [comment]
Ok, there's a lot of failures in your background workers. Can you share the logs of the web container to find out why?

**Comment by nkj87lm9532** [comment]
Yes, when I can I will be back. Thanks.

**Comment by nkj87lm9532** [comment]
How to stop and reset all background jobs?

**Comment by MohamedBassem** [comment]
you can stop hoarder and delete the 'queue.db' file in the data directory

**Comment by nkj87lm9532** [comment]
Now the question is, there are still many Queued and Pending jobs in Background Jobs. I would like to understand what is happening in Background Jobs, but I did not find an explanation in the Hoarder docs.
What is the difference between Queued and Pending?
Should I just let these jobs run? The numbers do seem to be diminishing, except Inference Jobs, which increases under Queued, but remains the same number 4044 under Pending.

**Comment by nkj87lm9532** [comment]
@MohamedBassem, I know you asked for a log file for the fails, so here is part of one. I did not realize my local ollama was not working at the time, but I have it up now. I am sending this log to see the crawling fails?
[hoarder-web-1 log.txt](https://github.com/user-attachments/files/17904627/hoarder-web-1.log.txt)

**Comment by nonsleepr** [comment]
> What is the difference between Queued and Pending?

I've been puzzled by those terms too. Looking at the was it works under the hood, "pending" is the total number of the links that weren't processed (crawled/indexed) yet. "Queued" is the number of the links in the task queue (`queue.db`).

> you can stop hoarder and delete the 'queue.db' file in the data directory

In my case of migrating 7000+ bookmarks from Omnivore I got the processing stuck several times (no changes for days with a few tasks in "running" state) with restarts doing nothing. Didn't try to delete the whole db yet but deleting records from it creates a situation of tasks being entirely forgotten (can't re-crawl pending, only re-crawl all).

**Comment by nonsleepr** [comment]
> you can stop hoarder and delete the 'queue.db' file in the data directory

Yeah, that doesn't work either. Now I'm just getting 0 queued and ~2,000 pending.
