### ISSUE TITLE
Improve note support : WYSIWYG markdown

### ISSUE THREAD

**Issue by Tukks** [hoarder-app/hoarder#701]
### Describe the feature you'd like

I made a similar app here https://github.com/Tukks/cogito but I don't have enough time to make new feature, and now I discovered Hoarder who is what I wanted for Cogito.
I think, the note part would need a little upgrade.

For the note-taking and editing part, I used the stackover flow markdown editor : https://editor.stackoverflow.design/ who is complete and very well-designed.

Here's how is integrated in cogito : 
![image](https://github.com/user-attachments/assets/8a3c001c-4bc9-4b92-8bf1-b00874564799)
![image](https://github.com/user-attachments/assets/139c1fb4-f089-430d-8743-46aca9ea4975)

### Describe the benefits this would bring to existing Hoarder users

add visual shortcut to bold/italic etc.
Support code
Support image
full-featured note-taking app
WYSIWYG

Upgrade : when we open a note card, open in Edit mode or add a button to edit in the big view (now we need to go : option > Edit)
![image](https://github.com/user-attachments/assets/b3a50c56-2293-4827-bbfb-3436e83ff66d)

### Can the goal of this request already be achieved via other means?

We can note-take today but some features are not implemented like code support or visual shortcut

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### Additional context

I can try to work on that if validated
I'm open to other editor BTW like tiptap/Lexical (https://lexical.dev/)/mdx (https://mdxeditor.dev/editor/demo)
We can add a toolbar to the existing react-markdown too.

**Comment by MohamedBassem** [comment]
Stacks Editor looks indeed very cool, and I'be be up to adding support for it in hoarder.

> I can try to work on that if validated

I'd be more than happy to merge it if you send a PR for it. You can join us in the #development channel in discord in case you need any help with developing in hoarder as well.

**Comment by Gnosnay** [comment]
is that possible to add support for `Text` bookmark also?

**Comment by Tukks** [comment]
> is that possible to add support for `Text` bookmark also?
> 
> for now it seems that hoarder only supports plain text

What is text bookmark? 
Hoarder actually support Markdown, but not in a wysiwig way.
If you put 

# title 1 

For example, you will see.

@MohamedBassem perfect, I will give it a try.
