### ISSUE TITLE
iOS sharing extension

### ISSUE THREAD

**Issue by nerdlich** [hoarder-app/hoarder#708]
### Describe the Bug

Cannot find the sharing extension on iOS which as of the app description should exist.

### Steps to Reproduce

1. open share menu in any app
2. try to find hoarder
3. go to 'edit' to see what else is available

### Expected Behaviour

hoarder should show up

### Exact Hoarder Version

iOS Hoarder App 1.6.5

**Comment by MohamedBassem** [comment]
If you've just recently installed the app, I've seen people say it takes a bit of time to appear for some reason. Some people find it after restarting their phone or something. I don't know why this happens, but I don't feel like this is a hoarder problem.

**Comment by nerdlich** [comment]
Reboot helps indeed. Thanks for your fast response! Awesome app btw.
