### ISSUE TITLE
OpenAI API has stopped working

### ISSUE THREAD

**Issue by danyonline64** [hoarder-app/hoarder#710]
### Describe the Bug

Hi :)

The OpenAI API for tags has stopped working for me since December 1st.

I'm using the latest version of Hoarder. On December 1st, I added a link, and the tags worked. A few minutes later, I added a second link, and that's when it completely stopped working.

I just deleted and created a new key, rebuilt my containers, but the issue is still there.

### Steps to Reproduce

1. Paste a link or a text.  
2. Wait for the process to complete.  
3. The link is added successfully.  
4. The tags fail to appear.  

### Expected Behaviour

When pasting a link or text, I expect the link to be added and the corresponding tags to be automatically generated and displayed.

### Exact Hoarder Version

Hoarder v0.19.0

![image](https://github.com/user-attachments/assets/0da765e0-eedc-4964-90e1-e88324e8249d)

**Comment by danyonline64** [comment]
@kamtschatka thanks, i understand now ! 

error: [inference][940] inference job failed: Error: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors

**Comment by makehavoc** [comment]
> please post the hoarder logs

HI There,
I'm trying to solve my own OpenAI issues. Is it possible for someone to point me in the direction of the hoarder logs?  I couldn't find them. (Hope it's not me being an ID10T).

Thanks
Mark

**Comment by MohamedBassem** [comment]
@makehavoc are you using docker? if you do, it will be in `docker logs hoarder-web-1`
