### ISSUE TITLE
Error when fetching every page: Failed to fetch link content ...

### ISSUE THREAD

**Issue by Deus-Glen** [hoarder-app/hoarder#720]
### Describe the Bug

When fetching each page, the following error is displayed after a short load:
Failed to fetch link content ...

### Steps to Reproduce

1. Paste a website link, and prees "save"

### Expected Behaviour

get the content of link

### Screenshots or Additional Context

my docker compose file:
![image](https://github.com/user-attachments/assets/fcaa1f2a-4fc9-42e3-9eb0-e4cc1058bd17)

logs of chrome:
![image](https://github.com/user-attachments/assets/c3e77bbd-49a6-4ce7-ad8d-94224339198b)

### Device Details

131.0.6778.109 64bit on Windows11

### Exact Hoarder Version

Hoarder v0.19.0

**Comment by MohamedBassem** [comment]
can you share the logs from the web container?

**Comment by Deus-Glen** [comment]
like this 
![image](https://github.com/user-attachments/assets/1f9d07ec-b760-45f8-bb0f-592fe1c26ee8)

**Comment by MohamedBassem** [comment]
yes, can you add a link and share what gets logged there after adding the link?

**Comment by Deus-Glen** [comment]
the chrome container change like this:
![image](https://github.com/user-attachments/assets/ac7af153-43c3-4cd5-ac6e-693a50a4a150)


no change in the web container

**Comment by MohamedBassem** [comment]
the chrome container doesn't matter. But I'm surprised that the web container doesn't change at all? Are you sure?

**Comment by Deus-Glen** [comment]
command:docker logs hoarder_web_1
it only changes when I delete the bookmark.
![image](https://github.com/user-attachments/assets/974bf0ad-86b7-48f1-859a-fb27dd3e6995)

**Comment by MohamedBassem** [comment]
Ah, I think I know what's going on. Can you try the nightly version? I landed some fixes there that clarifies the problem. Change hoarder version to "latest", repull the images and try again

**Comment by Deus-Glen** [comment]
I change the hoarder version to "latest" ,repull the images and try again, but it seems work the same, no change happens.
new log for web container:
![image](https://github.com/user-attachments/assets/6131b18d-e774-4254-b921-6a99594a8b4f)

**Comment by Deus-Glen** [comment]
I’m not sure exactly what happened, but today my Hoarder can fetch web pages normally. The web container is also outputting logs correctly. It seems that the issue has indeed been resolved in the latest version.

Thank you so much for your prompt and swift response!

**Comment by MohamedBassem** [comment]
@Deus-Glen The worker container on startup downloads ads blocklists from github. If you're in a country where github is blocked (or with internet restriction in general), the worker will take some time until it timesout and skips downloading the adblocker list (that was the fix in the last release). It'll however keep happening every time you restart the worker. So you might want to set `CRAWLER_ENABLE_ADBLOCKER=false` in your env file.
