### ISSUE TITLE
Define List for newly added items…

### ISSUE THREAD

**Issue by ctschach** [hoarder-app/hoarder#721]
### Describe the feature you'd like

When adding a new item (e.g. via the share sheet on iOS - Hoarder App) it would be perfect if we can assign a default list to the items (e.g. inbox). 

Alternatively there could also be a filter in the webapp that allow me to filter for bookmarks with no list assignment.

### Describe the benefits this would bring to existing Hoarder users

I started to using Hoarder a but more and found out that I just share a bunch of links over time without taking care of proper list assignment. Having an „inbox“ would be perfect to identify new items that needs to be organized.

### Can the goal of this request already be achieved via other means?

Not really. I currently use Apple Shortcuts to use the API for list assignment. But of course this only works on the mobile devices.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

**Comment by MohamedBassem** [comment]
Thanks for the request! If being able to search for items without any lists is going to achieve the same thing for you (specially that you'll also be able to save that search in a "smart list"), I think we can tackle this effort in #65.
