### ISSUE TITLE
Create a Separate Custom Network in docker-compose.yml for Better Isolation

### ISSUE THREAD

**Issue by Lumpish3007** [hoarder-app/hoarder#726]
### Describe the feature you'd like

I suggest creating a custom network in the docker-compose.yml for better isolation between containers, enhancing security and manageability of the Hoarder environment.

### Describe the benefits this would bring to existing Hoarder users

- **Improved Network Isolation**: Creating a separate custom network will allow Hoarder users to control and isolate the communication between the Hoarder services (e.g., `web`, `chrome`, `meilisearch`), preventing potential interference from other containers on the default Docker bridge network.
- **Custom IP Range Control**: Users can specify a custom subnet to avoid IP conflicts with other networks.
- **Security**: Limits communication to relevant containers, improving overall security.
- **Cleaner Configuration**: Simplifies networking management and troubleshooting between containers.

### Can the goal of this request already be achieved via other means?

Yes. Users can manually create a custom network in their own `docker-compose.yml`, but having a default custom network would make the process more streamlined and ensure consistent behavior across different environments without manual intervention.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### Additional context

A custom network could be added like this in the `docker-compose.yml`:

```yaml
networks:
  hoarder_network:
    driver: bridge

**Comment by MohamedBassem** [comment]
reference: https://docs.docker.com/compose/how-tos/networking/
