### ISSUE TITLE
Network connection failed: The Internet connection appears to be offline.

### ISSUE THREAD

**Issue by robalees** [hoarder-app/hoarder#732]
### Describe the Bug

Unable to connect iPad to server over `http` with local IP address. Network diagnostics show...
```
Running connection test ...
Using address: http://ip:3000
Network connection failed: The Internet connection appears to be offline.
```
I can connect with iOS on iPhone, I can use Firefox on the browser to connect to the server, but I cannot sign into the app via the same address (ip removed from copy and paste) in the iPad app. 

### Steps to Reproduce

1. Download app (latest version)
2. Enter IP address `http://ip:3000`
3. Before trying Next, hit the debug button and see error `Network connection failed: The Internet connection appears to be offline.`
4. If I hit Next and enter email/password or API Key, I'll see an error that says `Network request failed`
5. Confirmed internet connection and signed in via the Firefox browser on the iPad with the same connection and credentials

### Expected Behaviour

Connect to server and function like the iPhone app

### Device Details

iPad Pro 12.9 Inch (6th Gen)

### Exact Hoarder Version

v0.19.0

**Comment by kamtschatka** [comment]
sounds like this https://github.com/hoarder-app/hoarder/issues/679 ? 
error message might be different, due to an older version of your iphone?

**Comment by robalees** [comment]
> sounds like this https://github.com/hoarder-app/hoarder/issues/679 ? 
> 
> error message might be different, due to an older version of your iphone?

Thanks for the reply! I first commented on that issue and then made a new one when I noticed the difference in error message.

I am on the latest version, OS etc

**Comment by MohamedBassem** [comment]
@robalees are you using a local ip address? This seems to happen if you reject the permission request for connecting to the local network. Maybe check the permissions you gave to the app, and maybe also attempt to re-install trying to force the prompt to appear again.

**Comment by robalees** [comment]
> @robalees are you using a local ip address? This seems to happen if you reject the permission request for connecting to the local network. Maybe check the permissions you gave to the app, and maybe also attempt to re-install trying to force the prompt to appear again.

Hey @MohamedBassem it is a local IP, I just got back from traveling and checked the app settings and it looks like the permissions were turned on. I did update the app and it appears to be working now, so maybe it was a bug in that version not recognizing the permission. Either way, I'm glad it seems to be resolved.
