### ISSUE TITLE
AI Summarise throws an error

### ISSUE THREAD

**Issue by totalcaos** [hoarder-app/hoarder#733]
### Describe the Bug

I am trying to create a summary of an existing bookmarked page using the AI Summarise feature.  Workflow I followed:

- Click on the arrows button to expand the bookmark
- Click on the AI Summarise button

At this point, I get a pop up on the web interface notifiying me that there was an error.

I have verified
- Open API key is valid and working (tagging works)
- There is sufficient funds in the Open AI account
- The bookmark link is valid and still accessible

Error Log:
`web-1          | s [TRPCError]: No inference client configured
web-1          |     at /app/apps/web/.next/server/chunks/6815.js:1:30189
web-1          |     at h.middlewares (/app/apps/web/.next/server/chunks/440.js:4:33572)
web-1          |     at a (/app/apps/web/.next/server/chunks/440.js:4:32966)
web-1          |     at Object.next (/app/apps/web/.next/server/chunks/440.js:4:33078)
web-1          |     at /app/apps/web/.next/server/chunks/6815.js:1:17092
web-1          |     at async a (/app/apps/web/.next/server/chunks/440.js:4:32960)
web-1          |     at async t (/app/apps/web/.next/server/chunks/440.js:4:32333)
web-1          |     at async a (/app/apps/web/.next/server/chunks/440.js:4:32960)
web-1          |     at async a (/app/apps/web/.next/server/chunks/440.js:4:32960)
web-1          |     at async a (/app/apps/web/.next/server/chunks/440.js:4:32960) {
web-1          |   code: 'BAD_REQUEST',
web-1          |   [cause]: undefined
web-1          | }
`

### Steps to Reproduce

- Click on the arrows button to expand the bookmark
- Click on the AI Summarise button

### Expected Behaviour

See a summary of the bookmarked article in question

### Device Details

Safari on Mac OS 15.2

### Exact Hoarder Version

v 0.19.0

**Comment by kamtschatka** [comment]
are you maybe on the old compose file, where there is a web and worker container and you did not add the openAI information to the web container?

**Comment by totalcaos** [comment]
Yes, that was it.  I'd just run a docker pull & not removed the worker / added the OpenAI key to the web container.

- Removed worker & modified docker-compose.yml

All fixed now.  Thanks for your help!
