### ISSUE TITLE
Hoarder-Chrome Failed to  Read DnsConfig

### ISSUE THREAD

**Issue by RJDavison** [hoarder-app/hoarder#737]
### Describe the Bug

Hoarder has been working perfectly until i tried to capture something this morning when I cant get through to the server. I've logged onto the server to read the logs to notice that hoarder-chrome is giving errors failing to read DnsConfig.

_Failed to read DnsConfig._

Thre are also errors in connecting to the socket:

_Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory_

as well as these errors....

_components/policy/core/common/config_dir_policy_loader.cc(118) Skipping recommended platform policies because no policy file was found at: /etc/chromium/policies/recommended_

Anyone got an idea whats going on?

### Steps to Reproduce

Open hoarder

### Expected Behaviour

Expected it to work normally

### Exact Hoarder Version

0.19.0

**Comment by kamtschatka** [comment]
this happens for everyone.
Additionally this is happening in chrome, so you will be better off to ask in the chromium project about these logs, instead of here.

**Comment by MohamedBassem** [comment]
@kamtschatka The `DnsConfig` part is indeed happening to everyone, but @RJDavison is still not able to capture stuff into hoarder. Let's help them with that.

@RJDavison can you share the logs of the web container when you save stuff to debug what problem you're facing?

**Comment by RJDavison** [comment]
Thanks but dont worry about it. One the basis of the kurt response i would rather delete the app

**Comment by MohamedBassem** [comment]
@RJDavison I understand your frustration, I think we  just missed the question in the issue itself as we usually get questions about this dns errors a lot.

If you decide to continue using hoarder, and still need help figuring out what's wrong, we'd be more than happy to help you if you just provide us with the web container logs.

**Comment by RJDavison** [comment]
Appreciated......

Looks like its actualllly a problem with cloudflare and hoarder. Been working perfectly for  the last six months until this morning. All the other sites going through cloudflare work.

I've moved it through a locally hosted caddy server and all is working fine.

**Comment by Eragos** [comment]
@MohamedBassem I appreciate much how u handle that case. Good job 👍

**Comment by chicuongle** [comment]
> Appreciated......
> 
> 
> 
> Looks like its actualllly a problem with cloudflare and hoarder. Been working perfectly for  the last six months until this morning. All the other sites going through cloudflare work.
> 
> 
> 
> I've moved it through a locally hosted caddy server and all is working fine.

Do you have any solution for cloudflare configuration in oder to get hoarder run properly?
