### ISSUE TITLE
[Bug] https://www.get-youtube-thumbnail.com/ is down

### ISSUE THREAD

**Issue by maya329** [hoarder-app/hoarder#744]
### Describe the Bug

Hoarder is throwing SSL error because the site is down and cert is no longer valid

### Steps to Reproduce

Add a youtube link.

### Expected Behaviour

It should return youtube's thumbnail.

### Exact Hoarder Version

nightly

**Comment by maya329** [comment]
Sorry, it was an accidental bookmark that's causing this. It's my own issue. Closing this.

**Comment by MohamedBassem** [comment]
Not sure what this is about? What errors are you referring to?
