### ISSUE TITLE
I can't import html bookmarks

### ISSUE THREAD

**Issue by cfjuan** [hoarder-app/hoarder#750]
### Describe the Bug

When I'm trying import html bookmarks file, I don't find how to do... in the settings options.
Thanks for your job

### Steps to Reproduce

1. I go to settings
2. I can't see the import option

### Expected Behaviour

Import bookmarks file

### Exact Hoarder Version

v.0.20

**Comment by cfjuan** [comment]
I don't see in my dashboard
![Screenshot 2024-12-23 at 09 31 24](https://github.com/user-attachments/assets/2a8fd680-9cb8-4581-9bfa-9fe684f8f6bd)

**Comment by MohamedBassem** [comment]
this is the homepage. You need to click on the circle top right (containing your initials), and you'll find user settings tab there

**Comment by cfjuan** [comment]
Jajajaja, sorry. I must had be blind, I see it now
