### ISSUE TITLE
[Android] Support for Boox devices

### ISSUE THREAD

**Issue by ant1fr** [hoarder-app/hoarder#755]
### Describe the feature you'd like

Hi,
On my Boox Note Air 4C, the Hoarder Android app is listed as unavailable in the Google Play Store.
![Screenshot_20241224-094857](https://github.com/user-attachments/assets/b9eb6a27-f132-4519-bf71-ef18474999b9)

Is there a known incompatibility or is this is just due to a blacklist/whitelist issue on the Play Store Console ?

### Describe the benefits this would bring to existing Hoarder users

Ability to access Hoarder and enjoy reading content on a distraction free color rink device.

### Can the goal of this request already be achieved via other means?

Yes but not convenient. Download the apk somewhere and manually install the app.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

**Comment by MohamedBassem** [comment]
hmmm, this is not intentional and probably is whatever default the play console defaults to. I wonder if the app is not available for tables in general. I'll check and report back to you.

**Comment by MohamedBassem** [comment]
Ok, so I checked why it's excluded and it's because:

> Doesn't support required feature: android.hardware.camera

Will check why google thinks that the camera is required for the app.

**Comment by MohamedBassem** [comment]
This will hopefully be fixed in the next mobile app release.
