### ISSUE TITLE
Attach extra files to entry

### ISSUE THREAD

**Issue by dionorgua** [hoarder-app/hoarder#759]
### Describe the feature you'd like

I would like to be able to attach some random files to entries. Similar to existing thing with full page and video:
![image](https://github.com/user-attachments/assets/949b4676-44f8-497c-ac01-87dbcb3dd965)

Why? To archive some related information. For example archived web page has link to `.zip` archive with code example. Or extra `pdf` or `xlsx` data, etc. No need to parse/display it. Just store together and download when needed.

For my current 'workflow' with just SingleFile html files I can put them together.

### Describe the benefits this would bring to existing Hoarder users

Ability to store web page with related data

### Can the goal of this request already be achieved via other means?

no

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

**Comment by dionorgua** [comment]
Note: It's purely about manual upload by user. Just "+" button in attachment list

**Comment by MohamedBassem** [comment]
That makes sense. Let's track this as part of #284. I'll modify it to be more generic (instead of being only about notes).

**Comment by dionorgua** [comment]
Sorry for dupe. Missed that!
