### ISSUE TITLE
Archived but not in list query

### ISSUE THREAD

**Issue by dionorgua** [hoarder-app/hoarder#760]
### Describe the feature you'd like

I often add pages from phone or using browser extension. So 'Home' page is like inbox that I want to keep clean. Everything in 'Home' is like a TODO list. I want to verify every entry that it was correctly downloaded, add it to one or more lists and then Archive.

Due to #757 I've some entries that are archived but not in list. It would be cool to have a way to query for Archived items that don't have List assigned.

Maybe filter in 'Archived' view. Or maybe some more advanced search query.

PS. I'm not sure that my workflow is expected. Please suggest.

### Describe the benefits this would bring to existing Hoarder users

It will simplify 'Home' == TODO list workflow

### Can the goal of this request already be achieved via other means?

check manually?

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

**Comment by MohamedBassem** [comment]
I have a PR for advanced search queries (https://github.com/hoarder-app/hoarder/pull/753) and we're planning to allow you to have lists from "saved searches". This will help you achieve what you want. The filters now don't have a `no_list` filter, but I'm planning to add it.

**Comment by MohamedBassem** [comment]
Let's track this in the parent saved search issue (#65)
