### ISSUE TITLE
Can't run docker compose because the env file is never found

### ISSUE THREAD

**Issue by rightsaidfred99** [hoarder-app/hoarder#764]
### Describe the Bug

No matter where I put the env file, 

le /volume1/docker/hoarder/.env not found: stat /volume1/docker/hoarder/.env: no such file or directory

### Steps to Reproduce

Use docker compose

### Expected Behaviour

The path is correct

### Exact Hoarder Version

Latest public release

**Comment by MohamedBassem** [comment]
The env file should live in the same directory where you're invoking `docker compose up` from

**Comment by rightsaidfred99** [comment]
It wouldn't work at all - I had to modify docker compose with help of gpt4

`services:
  web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - /volume1/docker_conf/hoarder/data:/data  # Mount host path to /data in the container
    ports:
      - 3000:3000
    environment:
      - HOARDER_VERSION=release
      - NEXTAUTH_SECRET=super_random_string
      - MEILI_MASTER_KEY=another_random_string
      - NEXTAUTH_URL=http://localhost:3000
      - MEILI_ADDR=http://meilisearch:7700
      - BROWSER_WEB_URL=http://chrome:9222
      - DATA_DIR=/data  # Data directory inside the container

  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars

  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=another_random_string
    volumes:
      - /volume1/docker_conf/hoarder/meilisearch:/meili_data  # Mount host path for meilisearch data

volumes:
  # No need to define volumes for 'data' here, as we're using host paths
  meilisearch:
`
