### ISSUE TITLE
Search bookmark in the browser search bar

### ISSUE THREAD

**Issue by hugoo10** [hoarder-app/hoarder#771]
### Describe the feature you'd like

Hi, thanks for this project i'm migrating my tools to it! It allows me to merge feedly + linkding.
My request is the following: add the possibility to search while writing in the browser search bar (like linkding (ld mytext) or raindrop (rd mytext)) 

![image](https://github.com/user-attachments/assets/c27e410e-d988-4be1-b1ec-e382f6e800fa)

### Describe the benefits this would bring to existing Hoarder users

Generally i use the website of my bookmark manager to manage my bookmark, but to be faster i uses this feature in the other tools

### Can the goal of this request already be achieved via other means?

no

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### Additional context

I looked in the manifest.json of linkding,it seems that it is configured through:

  "omnibox": {
    "keyword": "ld"
  }

**Comment by kamtschatka** [comment]
This can already be done.
* Go to chrome://settings/searchEngines, 
* scroll down to site search and press "add"
* Add a name, give it a shorcut (e.g. hoarder) and then put the URL of your instance with %s as the placeholder for your query (so "https://<yourinstance>/dashboard/search?q=%s")

**Comment by hugoo10** [comment]
Ok thanks i didn't know this feature. But it's not what i'm looking for: i'd like to display the filtered list directly in the suggestions so i can select it and go to the selected url. The solution you gave me will redirect me to the search page of my instance

**Comment by MohamedBassem** [comment]
This will be possible I guess with #712 let's track that there.

**Comment by hugoo10** [comment]
Yes it seems it could match my need, although i don't use floccus, i'll follow this feature, thanks!
