### ISSUE TITLE
API Methods for Creating or Updating Bookmarks Do Not Accept String for createdAt field

### ISSUE THREAD

**Issue by coltoneakins** [hoarder-app/hoarder#772]
### Describe the Bug

API methods such as 'Create a new bookmark' do not allow strings for date-type fields like createdAt. API reference:
https://docs.hoarder.app/api/create-a-new-bookmark

There is no coercsion on the date fields. See: https://stackoverflow.com/questions/75157299/how-can-zod-date-type-accept-iso-date-strings

Example request:

PATCH http://localhost:3000/api/v1/bookmarks/ht4h5o9t1uderpcqcl1k17hw

Body:

{
  "createdAt":  "2019-07-07T00:31:0.000Z"
}

Response:

{
  "code": "ParseError",
  "message": "createdAt: Expected date, received string"
}

This is a problem with the way dates are stored or a problem with validation on the API via zod. This effectively makes it so there is no way to import bookmarks via the API with createdAt dates.

### Steps to Reproduce

1. Set up Hoarder
2. Attempt to use any API call for creating or updating a bookmark where you specify the createdAt field
3. Notice that the API always responds with a ParseError

### Expected Behaviour

API methods can accept strings for date fields. This is proper JSON. 'date' data types are not valid JSON sent over the wire---so, they must be sent as strings.

### Screenshots or Additional Context

![api-date-string-bug](https://github.com/user-attachments/assets/72083168-e993-46b3-ade2-3fd7c1a45169)

### Exact Hoarder Version

v0.20.0

**Comment by MohamedBassem** [comment]
Yeah, those dates should have had a coerce indeed. I can send a fix.

**Comment by MohamedBassem** [comment]
Fixed in a1a3a7e. Thanks for the report!
