### ISSUE TITLE
Confirmation before deleting item

### ISSUE THREAD

**Issue by bverkron** [hoarder-app/hoarder#776]
### Describe the feature you'd like

Seems there is currently no confirmation required before deleting an item. This could be catastrophic if an item is deleted accidentally and the original source of the item is no longer available on the web and can't be re-added.

### Describe the benefits this would bring to existing Hoarder users

Avoids accidental and permanent deletion of an item that can no longer be found online 

### Can the goal of this request already be achieved via other means?

Not AFAIK.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

**Comment by lexafaxine** [comment]
Hello @MohamedBassem , I just found this repo and very interested in its concept. I am going to add a `DeleteBookmarkConfirmationDialog` component in the bookmarks components to handle this. I could open a PR in 24h, could you please assign this issue to me? Thanks!

**Comment by MohamedBassem** [comment]
@lexafaxine thanks for picking this up, looking forward to the PR!
