### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by elegast-me** [hoarder-app/hoarder#780]
### Describe the Bug

search results are not produced.
meilisearch-1  | [2024-12-28T15:12:07Z INFO  actix_web::middleware::logger] 172.27.0.3 "POST /indexes/bookmarks/search HTTP/1.1" 200 89 "-" "node" 0.006102
meilisearch-1  | [2024-12-28T15:12:07Z INFO  actix_web::middleware::logger] 172.27.0.3 "POST /indexes/bookmarks/search HTTP/1.1" 200 90 "-" "node" 0.000350

please disregard if user error suspected. 

### Steps to Reproduce

any search yield the following in console

meilisearch-1  | [2024-12-28T15:12:07Z INFO  actix_web::middleware::logger] 172.27.0.3 "POST /indexes/bookmarks/search HTTP/1.1" 200 89 "-" "node" 0.006102
meilisearch-1  | [2024-12-28T15:12:07Z INFO  actix_web::middleware::logger] 172.27.0.3 "POST /indexes/bookmarks/search HTTP/1.1" 200 90 "-" "node" 0.000350

### Expected Behaviour

search results displayed

### Exact Hoarder Version

v0.20.0

**Comment by MohamedBassem** [comment]
Did you by any chance wipe the meillisearch storage (or put it on a non persistent storage?). Try triggering a "reindex" from the admin panel and see if results in search results to show up?

**Comment by elegast-me** [comment]
welp that worked.
I was following https://discord.com/channels/1223681308962721802/1231891149673992253 to try and get it working. 
I guess I didnt reindex after deleting.
But that worked and search is working.

cheers!
