### ISSUE TITLE
See bookmarks without any list

### ISSUE THREAD

**Issue by Fr0sk** [hoarder-app/hoarder#794]
Is there any way to see all the bookmarks that don't have any list associated? It would be helpful to add a bunch of bookmarks from the mobile app and then organize them in the computer.

**Comment by MohamedBassem** [comment]
I'm working on this as we speak. Should be in nightly today, and will be available in the next release as part of the advanced search capabilities.

**Comment by Fr0sk** [comment]
Wow, that's incredible! Thank you so much for this software, it's amazing!

**Comment by MohamedBassem** [comment]
Just pushed 96cc11e which implements this feature. It'll be in the nightly build in ~15 mins. To search for bookmarks without any lists you can query `-is:inlist`. I still haven't published the documentation for the advanced search terms, but you can see some examples in the test file here (https://github.com/hoarder-app/hoarder/blob/96cc11ef321b4580430c05f9344c6eb7dbddcf23/packages/shared/searchQueryParser.test.ts). Keep in mind that once you go to nightly, you want be able to go back to the release version until next release.
