### ISSUE TITLE
[Feature request] Netscape HTML format import/export

### ISSUE THREAD

**Issue by vk2r** [hoarder-app/hoarder#96]
Hi there !
I've been using Linkding (another bookmarking application) for a while and I've found that Hoarder has what Linkding lacks, however I've run into a problem.

It happens that for both importing and exporting, Linkding takes the Netscape HTML Format and not only Linkding, but other applications too.

I would like to know if it is possible to do this implementation, as it would substantially improve the way bookmarks can be managed in the application.

**Comment by MohamedBassem** [comment]
Hello, I'm glad that you found in Hoarder what you're lacking!

I wonder if the importing docs here for chrome: https://docs.hoarder.app/import works for the linkding export. I'm currently on the phone and quick googling shows that it might. But will check when I'm on the laptop.

**Comment by MohamedBassem** [comment]
if it's the same, I'll add official support to it in the CLI :)

**Comment by MohamedBassem** [comment]
Ok, I checked the netscape format and it's also what chrome uses. So the wiki page I shared should work for you, but I'm also planning to add support for it in the CLIs given that it's a common format :)

**Comment by kamtschatka** [comment]
Since the CLI requires you to do quite a few manual steps, I created a PR to allow importing bookmarks file directly in the UI. Worked just fine for my chrome bookmarks. It is just extracting URLs using regex, so I don't expect that it does not work with your linkding export, but I don't have access to that, so I can't verify.

**Comment by MohamedBassem** [comment]
@kamtschatka added support for this and it's currently already released. Just drag and drop the html file and it'll get parsed and the bookmarks will get added!

**Comment by Airradda** [comment]
Unless I missed it here in the issues and in the application, only the import portion of this request was added and exporting in Netscape HTML format has not been added.
